### ISSUE TITLE
WebResponse instances must be disposed.

### ISSUE THREAD

**Issue by jonpryor** [Azure/azure-mobile-services#20]
[WebResponse](http://msdn.microsoft.com/en-us/library/system.net.webresponse.aspx) implements `IDisposable` and provides a [WebResponse.Dispose()](http://msdn.microsoft.com/en-us/library/ff928381.aspx) method. However, not all instances are disposed, which can cause problems when repeated calls are performed without disposing the previous responses.

For example, [ServiceFilterRequest.GetResponseAsync()][1] calls `request.GetResponseAsync()`, which returns a `WebResponse` instance, stored in `response`. The `WebResponse` instance is not disposed anywhere, resulting in a "leak" (until the GC gets around to collecting things, if the GC gets around to collecting things...).

[1]: https://github.com/WindowsAzure/azure-mobile-services/blob/ad64844f/sdk/windows/src/Microsoft.Azure.Zumo.Windows.WinMD/ServiceFilter/ServiceFilterRequest.cs#L121

The source should be searched for all places that create a `WebResponse` instance to ensure that they are properly disposed.

**Comment by paulbatum** [comment]
Ancient bug regarding our WinMD implementation that no longer exists.
