### ISSUE TITLE
Managed unit tests fail with Newtonsoft.Json 6.0

### ISSUE THREAD

**Issue by advancedrei** [Azure/azure-mobile-services#227]
There are a number of tests that fail due to serialization issues with Newtonsoft.Json v6. These issues do not appear with V5.

In addition to correcting the tests, the NuGet package of the SDK should be updated to exclude version 6 from the dependencies until the issues can be resolved.

**Comment by paulbatum** [comment]
This was fixed ages ago and just never closed.
