### ISSUE TITLE
Android local item overwritten when testing optimistic concurrency

### ISSUE THREAD

**Issue by wesmc7777** [Azure/azure-mobile-services#259]
Optimistic Concurrency for Android

I'm seeing a strange behavior that I don't understand. In the code below, when the onCompleted callback occurs, my local item variable is somehow changed from my local version to the server's version of the ToDoItem instead of the local version that was just updated by the user. This prevents resolving the conflict with the local version.  I don't see why this is happening.  I'm using 1.1.5 of the Mobile Services SDK for Android. I can show this in the debugger if it will help.
 
 
        private void UpdateItem(final ToDoItem item)
        {
            mToDoTable.update(item, new TableOperationCallback<ToDoItem>() {
                public void onCompleted(ToDoItem entity, Exception exception, ServiceFilterResponse response) {
                    if (exception == null) {
                    } else {
                        if (exception instanceof MobileServicePreconditionFailedException)
                        {
                            MobileServicePreconditionFailedException conflictEx = (MobileServicePreconditionFailedException)exception;
                            ToDoItem serverSideItem = (ToDoItem)conflictEx.getItem(); 
                            ResolveConflict(item, serverSideItem);
                        }
                        else
                            createAndShowDialog(exception, "Error");
                    }
                }
            });
        } 

 
Attempting to debug this, it looks like this happens in

        public final class MobileServiceTable<E> extends
          MobileServiceTableBase<TableQueryCallback<E>> 
        {
          ...
          @Override
          public void onCompleted(JsonObject jsonEntity, Exception exception,
            ServiceFilterResponse response) 
          {
          ...
            entity = parseResults(ex.getValue()).get(0);					
            if (entity != null && mOriginalEntity != null) {
              copyFields(entity, mOriginalEntity); // <<-----
              entity = mOriginalEntity;
            }
          ...
          }
        }

**Comment by ysxu** [comment]
fixed with current SDK
