### ISSUE TITLE
[Android] Multiple issues in the documentation

### ISSUE THREAD

**Issue by carlosfigueira** [Azure/azure-mobile-services#265]
We now have the Android documentation (Javadocs) live at http://dl.windowsazure.com/androiddocs/, and while browsing it we can notice many issues with them. I'm listing many around here which I found in the [package page alone](http://dl.windowsazure.com/androiddocs/com/microsoft/windowsazure/mobileservices/package-summary.html), but we should perform a thorough scrubbing in the comments to make sure we have a good documentation for the SDK.

**Package overview** (http://dl.windowsazure.com/androiddocs/overview-summary.html)
- No descriptions

**Package com.microsoft.windowsazure.mobileservices:**

* Class / interface / enum definitions:
  - Missing documentation:
    * BuildConfig
    * Registration
    * MobileServiceException
    * MobileServicePreconditionFailedException
    * MobileServicePreconditionFailedExceptionBase
  - Wrong / bad descriptions:
    - MobileServicePush: "the notification hub client" --> not really
    - `MobileServiceTable<E>` and `MobileServiceJsonTable` - same description. The description should tell the difference between them.
    - QueryOrder: "Sort order values". We could reword it better as something like "The possible values to determine sort ordering." or something similar.
  - Grammar / typos:
    - MobileServiceClient: `Entry-point for Windows Azure Mobile...` --> remove `Windows`, remove `-` (hyphen) between "entry" and "point"
    - Missing articles (many places): for example: `GcmNativeRegistration`: "Represents GCM native registration". It would be better as something like "Represents a native registration with GCM" or at least "Represents a GCM native registration"

**Comment by ysxu** [comment]
@marianosz Let's hold off on this item until @RickSaling investigates in android studio javadocs first. Thanks!

**Comment by ysxu** [comment]
@RickSaling we will need to regenerate java docs for the latest android sdk and put it at http://azure.github.io/azure-mobile-services/ or a new github.io belonging to mobile apps since the zumo content got deleted from http://dl.windowsazure.com/androiddocs/ as well. I remember you were the contact for java docs, please let me know if I should redirect to someone else. Thanks!

**Comment by mamaso** [comment]
moved to https://github.com/Azure/azure-mobile-apps-android-client/issues/28
