### ISSUE TITLE
JWT Token Validation Managed Services & JS

### ISSUE THREAD

**Issue by Injac** [Azure/azure-mobile-services#271]
What about giving us a dedicated token-validator class? I know that this code was copied from an old repository (ASP .NET Sample that not exists anymore) https://github.com/Magenic/MyVote/tree/master/src/MyVote.AppServer/Auth

**Comment by paulbatum** [comment]
Addressed by https://www.nuget.org/packages/Microsoft.Azure.Mobile.Server.Login/0.3.36
