### ISSUE TITLE
[Windows 8.1] can't add an object with predefined Id with InsertAsync

### ISSUE THREAD

**Issue by Bathilde** [Azure/azure-mobile-services#273]
Hello,
I am currently using AzureMobileService version 1.2.0.0.

When I try to insert an object, that already have an Id, I have the following error:
"Insertion impossible si le membre id est déjà défini. Parameter name: instance"
This means: the id member is already defined, insertion can't be completed.

However, the javascript part of the program is able to insert object with predefined id.
Did I miss something? Or is it impossible to insert object with predefined id only in C#?

Thanks.

**Comment by adrianhall** [comment]
moving to azure-mobile-apps - if this is still an issue, please re-file.
