### ISSUE TITLE
[iOS] Facebook loginWithProvider using ACAccountStore token does not call callback

### ISSUE THREAD

**Issue by napoleone1981** [Azure/azure-mobile-services#280]
The loginWithProvider:token:completion: completion block is never called if it's inside the ACAccountStore requestAccessToAccountsWithType:options:completion: completion block.
Workaround is to wrap the loginWithProvider call inside a dispatch_async(dispatch_get_main_queue()) block.

See http://social.msdn.microsoft.com/Forums/windowsazure/en-US/da56ab31-878a-4085-95f5-a1e256bf2f37/ios-facebook-login-using-accesstoken?forum=azuremobile for reference.

**Comment by phvannor** [comment]
This should be possible now.  Closing.
