### ISSUE TITLE
[iOS][Offline] Offline feature utilising NSManagedObject subclasses rather than NSDictionary

### ISSUE THREAD

**Issue by damienpontifex** [Azure/azure-mobile-services#287]
I've been testing out the offline branch for iOS and followed the walkthrough in the [ToDoOffline](https://github.com/Azure/mobile-services-samples/tree/master/TodoOffline/iOS) sample. Firstly Thank You :), you guys are amazing. Secondly, I was wonder about using NSManagedObject instances as the items vended through the service class. 

Providing a superclass, let's call it 'SyncableEntity', that inherits from NSManagedObject we can override the `-[NSManagedObject willSave]` method for any entities to be synchronised with the offline feature. As shown in the brief implementation below (pardon the Swift code, I know the rest of the project is in Objective-C, but my test project was in Swift), we can get this call after a `-[NSManagedObjectContext save:]` call. All of our model classes would then inherit from this class and enable strong typing rather than key-based use with NSDictionary.

By doing this, we can also continue to utilise classes like NSFetchedResultsController and any saves, deletes, updates etc are handled without any modification to the presentation code.

```
extension SyncableEntity {
	override func willSave() {
		
		// Don't execute if it isn't writing to the top most parent context
		if self.managedObjectContext.parentContext != nil {
			super.willSave()
			return
		}
		
		var changedKeys = self.changedValues().allKeys as String[]
		
		if changedKeys.count > 0 {
			// Ensure id is included if we are going to send changes
			changedKeys.append("id")
			
			let dataService = DataService()
			let syncTable = dataService.client.syncTableWithName(self.entity.name)
			let itemDictionary = self.dictionaryWithValuesForKeys(changedKeys)
			
			if self.objectID.temporaryID {
				// Newly inserted
				syncTable.insert(itemDictionary) { item, error in
					// Handle item/error
				}
			} else if self.deleted {
				// Deleting object
				syncTable.delete(itemDictionary) { error in
					// Handle error
				}
			} else {
				// Updating object
				syncTable.update(itemDictionary) { error in
					// Handle error
				}
			}
		}
		
		super.willSave()
	}
}
```

Changes would need to also be made in the MSSyncContext class to avoid the upsert and/or delete operations that occur in the method `-(void) syncTable:(NSString *)table item:(NSDictionary *)item action:(MSTableOperationTypes)action completion:(MSSyncItemBlock)completion` but this could easily be refactored to allow both the NSDictionary and NSManagedObject versions to operate

**Comment by mikaelbartlett** [comment]
What's the status on this feature? I would love to use mobile services with NSFetchedResultsController.

**Comment by damienpontifex** [comment]
@mikaelbartlett I have it working by using another class in my application very similar to the one here https://github.com/Azure/azure-mobile-services/blob/multiple-contexts/sdk/iOS/src/MSManagedObjectObserver.m

I register my main context I'm using with the NSFetchedResultsController and then this observes the context and makes the appropriate mobile services calls.

i'd have to have a further look on the differences between my current implementation and that one, but it would be very close

**Comment by phvannor** [comment]
Moving to new repo: https://github.com/Azure/azure-mobile-apps-ios-client/issues/28.
