### ISSUE TITLE
[Feature request] Support for store JS apps on Win Phone 8.1? 

### ISSUE THREAD

**Issue by rohitpagariya** [Azure/azure-mobile-services#299]
AMS only supports the store JS apps on Windows 8.1 as of now. I tried using the AMS js files in a Win Phone 8.1 project and it throws due to calls to deprecated APIs. JS universal apps using AMS don't work on phone as a result. 

Is the support for JS apps on phone in the works?

**Comment by adrianhall** [comment]
we are not updating AMS any more.  Closing.
