### ISSUE TITLE
[JavaScript] Suggestion - use Grunt for building the HTML/JS SDK

### ISSUE THREAD

**Issue by joewood** [Azure/azure-mobile-services#319]
The build process for JavaScript is dependent on Visual Studio and focused Windows 8 store development. To better support regular HTML/JS development I would suggest adopting more widely adopted web based tools - such as Grunt.

Additionally, consider distributing the client SDK over bower and npm.

**Comment by paulbatum** [comment]
Dupe of https://github.com/Azure/azure-mobile-apps-js-client/issues/47
