### ISSUE TITLE
IMobileServiceTable.MobileServiceClient should be IMobileServiceClient

### ISSUE THREAD

**Issue by powerdude** [Azure/azure-mobile-services#320]
Hi,

I don't believe the interface should have a property this property that returns the concrete type.  It makes it difficult to complete a mocking scenario.

**Comment by paulbatum** [comment]
I want to track fixing this the next time we do a breaking change release of our new managed client SDK so moving to: https://github.com/Azure/azure-mobile-services/issues/320
