### ISSUE TITLE
Microsoft ASP.NET Web API 2.2 5.2.0 breaks Azure Mobile Services .NET Backend Tables 1.0.342

### ISSUE THREAD

**Issue by apollyonbob** [Azure/azure-mobile-services#325]
I just spent several hours diagnosing this particular problem. In the SelectExpandWrapperConverter in the Azure Mobile Services .NET Backend Tables package, there's this problematic constructor:
```C#
/// <summary>
/// Initializes a new instance of the <see cref="ODataReflectedTypes"/> which looks into the OData
/// assembly for internal types required to modify the serialization.
/// </summary>
public ODataReflectedTypes()
{
       Assembly odataAssembly = typeof(SingleResult).Assembly;
       this.dictionaryConvertible = odataAssembly.GetType("System.Web.Http.OData.Query.Expressions.IDictionaryConvertible");
       MethodInfo toDictionaryMethod = this.dictionaryConvertible.GetMethod("ToDictionary");

       this.toDictionary = TypeUtils.CreateInvoker<IDictionary<string, object>>(this.dictionaryConvertible, toDictionaryMethod);
       this.jsonConverter = odataAssembly.GetType("System.Web.Http.OData.Query.Expressions.SelectExpandWrapperConverter");
}
```
So, other than just the general principles violations involved with calling GetType on a foreign assembly using a string for a class name, there's something else that could have been done to avoid this: Marking the specific assembly that you needed as a dependency in NuGet so that it wouldn't get updated. I note that the assembly that this reference is found in isn't even listed as a dependency.
Also, yes, if you check [the resolution for Issue 1676] (https://aspnetwebstack.codeplex.com/SourceControl/changeset/a31eab7e87ca865aacad01944b5f2ef32e7764e6) on CodePlex, you'll see the IDictionaryConvertible was renamed.

As it stands, if you upgrade your NuGet packages to the latest version, then the Azure Mobile Services .NET TableController will throw exceptions whenever you try to return an object that requires serialization. So, basically, any time I try to use your service to retrieve data. So. Kind of a sev 1 issue.

I've got two small projects with identical code - one has Web API 5.1.2 (aka, prior to issue 1676 being checked in) and the other 5.2.0 - the 5.1.2 works, 5.2.0 breaks. Let me know if you can't repro, and I'll send 'em to ya.

**Comment by cloudish** [comment]
Is this issue being addressed? Looked at? Does anyone care?

**Comment by apollyonbob** [comment]
Yes, I should've closed this actually. For a current thread about some of the general updating problems, there's this: https://github.com/Azure/azure-mobile-services/issues/551
But this specific problem was fixed.
