### ISSUE TITLE
Using Facebook login via JS SDK does not use "popup" display format

### ISSUE THREAD

**Issue by kamranayub** [Azure/azure-mobile-services#350]
I tried searching around for a solution to this but no dice. I'm using the Azure Mobile Services SDK for WinJS and I am prototyping an app that uses Facebook login. It works fine but the OAuth popup when logging in is not using Facebook's recommended "popup" display format (it even displays a big warning if you're the admin of the app), so the user has to scroll the window to use it properly which is definitely less than ideal.

Is there a way to fix it so it uses the right kind of display format?

**Comment by ysxu** [comment]
I will remove the Android tag with the above commit.

**Comment by phvannor** [comment]
Moved remaining parity for iOS to https://github.com/Azure/azure-mobile-apps-ios-client/issues/10
