### ISSUE TITLE
wp8 client logout should use WebBrowserExtensions.ClearCookiesAsync to dispose cookie

### ISSUE THREAD

**Issue by xqiu** [Azure/azure-mobile-services#37]
bBrowserExtensions.ClearCookiesAsync Method
http://msdn.microsoft.com/en-us/library/windowsphone/develop/jj571211(v=vs.105).aspx

From Randall: 
When the user authenticates with Google, Google is dropping a cookie on the phone with an opaque token that points to the authenticated user. When the user logs out via the MobileService Logout() method we throw away the userId that the client is holding on to, but we don’t dispose of the cookie. So when the user goes to log in again, the cookie gets picked up and used in the login flow before Google ever asks for the user’s credentials.

On the phone, we use a phone WebBrowser control to do the login dance with Google. The developer might be able to clear the Google cookie his/herself and then the user would be able to sign in with a different account.

**Comment by phvannor** [comment]
For now we've decided to leave this as is.  May revisit clearing cookies later on. Closing issue.
