### ISSUE TITLE
Parser error with Cordova on android

### ISSUE THREAD

**Issue by layinka** [Azure/azure-mobile-services#375]
When the javascript version( the MobileServices.Web.min.js) is used with cordova in an android app, it have a parser error, as android cannot load the encoding of the file.

**Comment by shrishrirang** [comment]
This is a stale issue and looks like it was fixed long time back but this issue wasn't updated/closed.
I have verified that the latest version (beta3) of the Azure Mobile Apps Cordova plugin (https://www.npmjs.com/package/cordova-plugin-ms-azure-mobile-apps) works fine on Android. If you still see any issues, feel free to re-activate the issue.
