### ISSUE TITLE
White page flashes on screen if the user has previously logged in via Twitter

### ISSUE THREAD

**Issue by yavorg** [Azure/azure-mobile-services#40]
I think in our current multi-auth implementation, we will always pop up a browser control when the login method is called. In some cases, the user has already logged in and checked the "remember me" box, so the browser control immediately disappears and the user is logged in correctly.

Is there a way to prevent the browser from popping up in that case while maintaining the current (correct) behavior?

**Comment by phvannor** [comment]
Flash is caused most likely due to the cookie being picked up and finishing the login process with the need for the UI to show.
