### ISSUE TITLE
Update quickstart to support futures/Android Studio

### ISSUE THREAD

**Issue by yavorg** [Azure/azure-mobile-services#428]
In our private branch, update the quickstart: https://github.com/Azure/azure-mobile-services/tree/master/quickstart/android/ZUMOAPPNAME to support futures and Android Studio. I've already done most of the work here: https://github.com/yavorg/samples/tree/master/AndroidStarter

**Comment by ysxu** [comment]
@aziel is looking at the commit at https://github.com/ysxu/azure-mobile-services/commit/315b030e739279b029cbf390c5bc22045b1ead74 and I will submit a pull request then close this item if all looks fine by tomorrow.

**Comment by ysxu** [comment]
Quickstart updated at https://github.com/Azure/azure-mobile-services/pull/590
