### ISSUE TITLE
[iOS] Remove login methods from MSClient

### ISSUE THREAD

**Issue by damienpontifex** [Azure/azure-mobile-services#450]
I was investigating creating a Mac OS X target for the mobile services SDK.

There are obviously some class inheritance differences, but the best way to maximise reusability would be to remove any UIKit references from the core classes. To this end a change to remove any references to MSLoginController from MSClient would simplify this. Then a standalone MSLoginController inheriting from NSViewController for the mac could be used when building the mac framework vs iOS.

I would assume this would be a breaking change, but could be implemented before the full release of the v2.0 iOS version.

**Comment by phvannor** [comment]
With the conditional compiles for os x upcoming that you are adding, I think this can be closed now.

**Comment by damienpontifex** [comment]
Agreed
