### ISSUE TITLE
DbUpdateException when using migrations

### ISSUE THREAD

**Issue by powerdude** [Azure/azure-mobile-services#466]
Hello,

When following what's outlined [here](http://weblogs.asp.net/fredriknormen/azure-mobile-service-and-manual-database-migrations?__r=8d1c15ea5fbb28f) and trying to seed your database in the Configuration.Seed() method, you get the following error 

Modifying a column with the 'Identity' pattern is not supported. Column: 'CreatedAt' in TodoItem

First, why is CreatedAt set as an identity column if you already have an Id column to use as the primary key.  Second, can this be changed so that the user can set their own identity column.

thanks

cliff

**Comment by adrianhall** [comment]
There was a historical reason on this.  However, we have moved all our attention to the azure-mobile-apps SDK.  So this isn't going to be fixed in this SDK.
