### ISSUE TITLE
Swift code in Swift quickstart does not compile anymore

### ISSUE THREAD

**Issue by krisragh** [Azure/azure-mobile-services#482]
See the comment at http://azure.microsoft.com/en-us/documentation/articles/mobile-services-ios-get-started/#comment-1660728934 which says: "You should update the project sample code in Swift to fix the errors that occur with the current compiler version :)"

Once you've updated the quick-start so it compiles, please respond to the commenter via Disqus and let them know it's fixed!

**Comment by neman** [comment]
Swiftproject is still not buildable!
You shoud revert to
    cell.textLabel?.text = item["text"] as? String
    cell.textLabel?.textColor = UIColor.blackColor()

**Comment by phvannor** [comment]
Yes it looks like Apple has changed the syntax for this back to what it was.

**Comment by phvannor** [comment]
This is back in a happy state again.
