### ISSUE TITLE
Inserts with soft delete enabled have issues when deleted record already present.

### ISSUE THREAD

**Issue by jcmm33** [Azure/azure-mobile-services#492]
If soft deletes are enabled and a previously 'deleted' record is attempted to be reinserted from a client, then the Insert fails to occur.

I suspect that the InsertAsync methods for domainManagers needs to be adjusted for this.  My version (which works for me) is shown below:

        public async override Task<TData> InsertAsync(TData data)
        {
            if (data == null)
            {
                throw new ArgumentNullException("data");
            }

            // now then, if we have soft delete enabled & data has been provided with an id in it 
            if (EnableSoftDelete && data.Id != null)
            {
                // now look to see if the record exists and it is deleted

                // record old value of deleted, since need to query to see if deleted.
                var oldIncludeDeleted = IncludeDeleted;

                try
                {
                    IncludeDeleted = true;
                    var existingData = await this.Lookup(data.Id).Queryable.FirstOrDefaultAsync();

                    // if record exists, and its soft deleted then truly delete it
                    if (existingData != null && existingData.Deleted)
                    {
                        // now need to remove this record...
                        this.Context.Set<TData>().Remove(existingData);
                    }
                }
                finally
                {
                    IncludeDeleted = oldIncludeDeleted;        
                }
            }

            return await base.InsertAsync(data);
        }

I would expect however for this to be implemented in all of the default DomainManagers that are currently available.

**Comment by adrianhall** [comment]
This is fixed in the Azure Mobile Apps SDK.
