### ISSUE TITLE
Cancel pending operations

### ISSUE THREAD

**Issue by jcmm33** [Azure/azure-mobile-services#493]
Is there no way to cancel pending operations other than spinning up a new database?

We have the requirement for the mobile user to sometimes say 'just refresh from the server and loose anything I've done locally'.  Is the only way of doing this is spin up a new database ?

**Comment by phvannor** [comment]
Following commit in the 1.3.0 release: https://github.com/Azure/azure-mobile-services/commit/aa51d9fae89d734e8ef515501c37a79c67ef81a9
Allows purge to abort all pending operations on the table.

**Comment by patsissons** [comment]
I noticed today that I am able to purge the pending changes, but it won't let me JUST purge the pending changes and not the actual table data. i.e.,
```
// this will delete pending changes, and then purge all rows in table
table.PurgeAsync("queryid", null, true, cancel).Wait();

// this will run if there are no pending changes
// if there are pending changes this throws an InvalidOperationException:
// "The table cannot be purged because it has pending operations."
table.PurgeAsync("queryid", "$filter=false", true, cancel).Wait();
```
I'm not sure why you can't force purge with a filter, anyone care to explain?

**Comment by phvannor** [comment]
The general idea, to update purge to run the filter to get record Ids, purging just those pending ops, then purging the associated table data is possible.  The main complication would be how to deal with deletes in the queue. Since those are not in the SQL db, we'd need to figure out if we try to run the query against the stored items in the pending ops queue or ignore them and leave them pending.

At this time, it was mainly left out for simplicity reasons and to wait to see if it was a requested feature.

**Comment by patsissons** [comment]
what do you recommend to simply wipe out any pending changes? I can manually scan the operations table to see which entities should be deleted and delete them before finally clearing the operations table (and errors table too?). I'm not sure if that is the best approach though, I was mostly hoping that your purge pending changes code would be available to call directly.

**Comment by phvannor** [comment]
Ideally you could call the syncContext CancelAndUpdateItemAsync or CancelAndDiscardItemAsync for each op.  It looks like for some reason that takes an error and not an operation... Those two give you control over what you want to end up in the local db, while (hopefully) hiding implementation details.  Sadly you need to make an op error and probably get the op by doing a manual read.  Something we should improve here to make it easier to scan your ops, and handle them w/o triggering a push in this case.

**Comment by patsissons** [comment]
I have ended up going with the simpler route and just allowing force purge (and immediate resync) to do it's thing and simply restrict that operation to only tables that I can detect pending operations on. I do think there is some value in automating the purge of pending ops and re-download of potentially deleted rows.

As a user of the SDK it's pretty low level to make this happen efficiently, but with access to all the internals it might be a little easier (not to mention familiarity with code). I'll keep my eye on this issue for sure though.

**Comment by Jinger8910** [comment]
I encounter similar problem with patsissons. No way to modify pending content is really annoying. hope you could improve this soon

**Comment by maxlazarev** [comment]
Would be great if there was a possibility of cancelling a specific pending operation that was not synced yet. Do you plan to implement it?

**Comment by dillondrobena** [comment]
I also would be very interesting in canceling or clearing pending operations. I'm having a problem right now with a user adding an item to a table and later trying to remove it. The operations clash and cause issues

**Comment by shrishrirang** [comment]
Performing selective canceling of pending operations is on our backlog currently. Can you elaborate the clash you mentioned?

**Comment by dillondrobena** [comment]
I've been having instances where I'll delete an item and later try to re-add the same item (with the same Id) and get the exception **a delete operation on the item is already in the queue** which I know is thrown in the **Validate** function in **DeleteOperation** class. Of course it makes sense to throw that exception during normal operations since it no longer exists, but adding the same item back into queue shouldn't have this effect.

**Comment by phvannor** [comment]
If the delete of record id X hasn't been synced to the server, the code can't tell if the reuse of the id is an undelete or a new item with an id clash.  Exposing the undelete method on the synctable API, could help with that case, and do the right thing (cancel the pending delete action, and replace it with an update operation instead (or no action if no changes exist between the old & new local items))

An insert + delete without a sync in the middle should result today like no action was taken, if this is not happening that should be a separate bug from this issue.

**Comment by adrianhall** [comment]
We are not accepting nor working feature requests on azure mobile services.  All attention has been moved to azure mobile apps.
