### ISSUE TITLE
[Feature request]: Client libraries should handle 401 response and automatically retry a login

### ISSUE THREAD

**Issue by ggailey777** [Azure/azure-mobile-services#495]
When authentication is used, an token can expire at any time. This either requires you to be able to handle a 401 response everywhere you make a request, or else do something in the messaging pipeline. 
We have guidance on how to handle expired tokens by using ServiceFilters in the Android client documented here: http://azure.microsoft.com/en-us/documentation/articles/mobile-services-dotnet-backend-android-get-started-users/#refresh-tokens. This is frankly a lot of customized code that users have to add themselves every time that they want to correctly do authentication. We need to make this easy by moving this 401 handling filter code into the MobileServiceClient class itself.

Scenario:
When the MobileServiceUser is not null: 
1. Cache the login type being used.
2. Detect for 401 responses.

When a 401 response is detected:
1. Automatically retry LoginAsync using the type of authentication as in the original request.
2. Block outgoing requests until login succeeds.

There must be a way provided to turn this autologin off, of course, in the MobileServiceClient.

**Comment by adrianhall** [comment]
We are not doing any work on azure-mobile-services.  However, do checkout AppServiceHelpers, which has this logic.
