### ISSUE TITLE
Cancellation Tokens & IMobileServiceClient

### ISSUE THREAD

**Issue by jcmm33** [Azure/azure-mobile-services#524]
Whilst the IMobileServicesSyncTable interface defines methods which take a CancellationToken, none of the InvokeApiAsync methods on IMobileServiceClient do.

Is this deliberate?

**Comment by jcmm33** [comment]
Has the ability to provide cancellation tokens to InvokeApiAsync made it onto any backlog ?

**Comment by Reminouche** [comment]
Hi, I also looking how cancel an InvokeApiAsync. Any ideas ?

**Comment by jcmm33** [comment]
We implemented cancellation "ish" by using a task extension 

        /// <summary>
        /// Enable cancellation for a task for which cancellation tokens can't be specified.
        /// </summary>
        /// <typeparam name="T"></typeparam>
        /// <param name="task"></param>
        /// <param name="cancellationToken"></param>
        /// <returns></returns>
        public static async Task<T> WithCancellation<T>(this Task<T> task, CancellationToken cancellationToken)
        {
            var tcs = new TaskCompletionSource<bool>();
            using (cancellationToken.Register(
                        s => ((TaskCompletionSource<bool>)s).TrySetResult(true), tcs))
                if (task != await Task.WhenAny(task, tcs.Task))
                    throw new OperationCanceledException(cancellationToken);
            return await task;
        }
 
You apply this to the task you which to cancel (but which doesn't take cancellation tokens) . Your original task still executes if the cancellation token is raised but it does give you the flow you require.

**Comment by paulbatum** [comment]
InvokeApiAsync now has overloads that accept cancellation tokens.
