### ISSUE TITLE
Why MobileServicePushFailedException is derived from Exception?

### ISSUE THREAD

**Issue by IlyaTsilikov** [Azure/azure-mobile-services#528]
I mean that it complicates to handle it 'cause it hinders to specify one or few exceptions to handle all exception from Microsoft Azure Mobile Services. E. g. in WCF I had to specify only CommunicationException and TimeoutException to catch and all remote exceptions were derived from them. I thought that I can use only MobileServiceInvalidOperationException and TaskCancelledException to handle but now I've encountered one more that isn't derived even from InvalidOperationException not mentioning MobileServiceInvalidOperationException.

**Comment by paulbatum** [comment]
We will try to do a better job as we introduce more exception types, but I don't think we should be making any changes to existing exceptions at this point.
