### ISSUE TITLE
SQLite 3.8.7.2 support is needed

### ISSUE THREAD

**Issue by paulirwin** [Azure/azure-mobile-services#529]
I recently installed the latest version of SQLite for Windows Runtime (8.1) which is version 3.8.7.4. I then built a Windows Runtime app against it, with SQLitePCL version 3.8.5.1 and Azure Mobile Services SQLite Store version 1.0.0. The app fails WACK certification. I cannot tell if that is due to the PCL version or the SQLite version, but the certification failing is what made me look into which version of SQLite the Azure Mobile Services SQLite Store was targeting.

Since I cannot go back and install an old version (3.8.5) of the SQLite extension (unless someone can tell me how to do this?), the Azure Mobile Services SQLite Store package needs to be updated to support SQLitePCL 3.8.7.x.

**Comment by raketenhunddev** [comment]
I would appreciate this also! Any news on this?

**Comment by thor089** [comment]
I also ran into this issue and would appreciate an update

**Comment by paulbatum** [comment]
This is done as of version 1.0.4 of the SQLiteStore.
