### ISSUE TITLE
[javascript] gruntfile.js case incorrect

### ISSUE THREAD

**Issue by joewood** [Azure/azure-mobile-services#538]
The file `Gruntfile.js` is not recognized by `grunt` and should have its case corrected to `gruntfile.js`.

**Comment by phvannor** [comment]
The getting started guide seems to recommend using Gruntfile.js: http://gruntjs.com/getting-started and I'm not seeing an issue with v0.4.5.

From the logs, it looks like v0.4.1 of Grunt allowed the name to be case insensitive. 

Are you required to use an older version of Grunt?

**Comment by joewood** [comment]
You're right, updated grunt seems to work now. Thanks.
