### ISSUE TITLE
Suggestion - add external dependencies as npm dependencies

### ISSUE THREAD

**Issue by joewood** [Azure/azure-mobile-services#539]
The external dependencies in the JavaScript SDK `esprima` and `queryjs` should be added as dependencies in the `package.json` file.  These could then be incorporated into the build process from `node_modules`. 

Additionally, the build process could use **browserify** rather than a proprietary requirejs implementation.

**Comment by phvannor** [comment]
Opened new issue on queryjs to be an npm module (https://github.com/Azure/queryjs/issues/13)  Looks like there is already a queryjs module that is unrelated on npm.

**Comment by joewood** [comment]
Great, any thoughts of using commonjs/browserify ?

**Comment by phvannor** [comment]
I need to familiarize myself with the QueryJS codebase again.  It makes some assumptions on require, that need reviewed before I could say how reasonable this is to use.  

It seems using browserify is possible for the main code base, but does require minor modifications to all the files.  Only issue I see is redoing the build to dynamically rename the platform specific files so browserify can pick up the right one dynamically.

**Comment by joewood** [comment]
Any progress on this? Seems like there's still no easy to use npm package for Azure Mobile Services.

**Comment by joewood** [comment]
Any progress on this? It would be great to install the JS SDK from npm and use webpack or browserify. This must be possible now that there's a Cordova SDK.

**Comment by phvannor** [comment]
Yes we have moved the main build over to browserify and consuming the dependencies that way now.   @shrishrirang can we port that portion from offline only onto the main (or at least MobileApp) branch?

**Comment by paulbatum** [comment]
@shrishrirang @phvannor This is now done, right?

**Comment by phvannor** [comment]
I dont think it can be unless we made QueryJS an npm module when I wasnt looking :)  The grunt file (https://github.com/Azure/azure-mobile-apps-js-client/blob/master/sdk/package.json) doesn't look like its using esprima from npm either yet.

**Comment by phvannor** [comment]
Offline has the esprima change, and consuming queryjs off its GitHub branch directly: https://github.com/Azure/azure-mobile-apps-js-client/blob/offline/sdk/package.json

Im still a little worried on always using the head of a repo in, but since we own both repos for now, it seems safe enough.

**Comment by joewood** [comment]
It'll work, but for those of us behind a proxy that blocks the git ssh port, you have to make sure you configure npm to modify the url. HTTPs would be better, or npm better still.

**Comment by phvannor** [comment]
I think since both node.js server and client consume queryjs making some kind of npm package to consume will work best for everyone.

**Comment by shrishrirang** [comment]
https://github.com/Azure/azure-mobile-apps-js-client/commit/0bbc06dd681b21c5d1b550413b54c4e066baa049 does away with the custom javascript bundler and instead uses browserify. Also, git submodules are now npm dependencies. 

I need to address the https issue pointed out above yet.

**Comment by shrishrirang** [comment]
The queryjs npm dependency will be pulled using the git:// protocol. So I am assuming the ssh concern mentioned above does not apply. I am closing this. Feel free to file a separate issue for any concerns you may have about usage from behind a proxy.

https://github.com/Azure/azure-mobile-apps-js-client/commit/0bbc06dd681b21c5d1b550413b54c4e066baa049 closes this for Azure Mobile Apps.
Note: This does not change anything for Azure Mobile Services.

**Comment by joewood** [comment]
@shrishrirang any reason why queryjs cannot be published to npm? Is it just the naming conflict?
