### ISSUE TITLE
[javascript] The .gitignore in the generated directory causes issues with npm local install

### ISSUE THREAD

**Issue by joewood** [Azure/azure-mobile-services#540]
The `.gitignore` file in the javascript `src/generated/` directory is picked up by npm when doing an `npm install` from the git repository file.  This means that generated files are not copied over as part of the npm install.  I'm using npm install to pull the files into a separate project as part of the build process:

```cmd
cd myproject
npm install ../azure-mobile-services/sdk/javascript
```

By adding an `.npmignore` to the root of `azure-mobile-services/sdk/javascript/` the generated files can be added to the local npm package. This will override the `.gitignore` settings (although it will be ignored by `npm install`).

**Comment by adrianhall** [comment]
Transitioned bug to azure-mobile-apps-js-client#3

**Comment by joewood** [comment]
is that a private repo?

**Comment by adrianhall** [comment]
Yes.  We are splitting up the azure-mobile-services repo into individual SDKs.  The original membership will be restored once we have the SDKs building and have finished the conversion.

**Comment by joewood** [comment]
Great! +1
