### ISSUE TITLE
AutoMapper 3.3.0 bug seems to be not fixed

### ISSUE THREAD

**Issue by IlyaTsilikov** [Azure/azure-mobile-services#542]
I've tryed Microsoft Azure Mobile Services .NET Backend 1.0.447 and seen that I have a query error:
`{"message":"An error has occurred.","exceptionMessage":"Method not found: 'System.Linq.IQueryable``1<!!0> AutoMapper.QueryableExtensions.IProjectionExpression.To()'.","exceptionType":"System.MissingMethodException","stackTrace":"   at Microsoft.WindowsAzure.Mobile.Service.MappedEntityDomainManager``2.Query()\r\n   at Microsoft.WindowsAzure.Mobile.Service.TableController``1.Query()"}`

This error occured in previous versions when I used AutoMapper 3.3.0. So it seems I have still to use older versions without new AutoMapper features. I hope to some version of Microsoft Azure Mobile Services .NET Backend with AutoMapper 3.3.0 support to be released soon. AutoMapper 3.3.0 new features are useful.

**Comment by paulbatum** [comment]
If you switch to using the new version of our .NET server SDK (for Mobile Apps) you should find that you have much more flexibility in terms of which libraries you use.
