### ISSUE TITLE
Make sure all projects are updated to target API 21

### ISSUE THREAD

**Issue by ysxu** [Azure/azure-mobile-services#553]
Per the meeting on content freshness, we want to make sure we target the newest Android API in every release. Quickstart is targeting 19 (is there a reason for this?), and I haven't looked into other files. But we want to make sure everything targets the latest ver unless an older ver is justified. @soninaren @marianosz

**Comment by ysxu** [comment]
didn't realize there can only be one assignee. I meant for us to all keep track of this and we want everything to be updated before GA.

**Comment by aziel** [comment]
Closed with PR #561
