### ISSUE TITLE
[offline][iOS] Item already inserted doesn't create operation message

### ISSUE THREAD

**Issue by damienpontifex** [Azure/azure-mobile-services#568]
I have previously been using the iOS offline SDK. Although I use actual NSManagedObject instances in my view controllers and override the `-[NSManagedObject willSave]` method which I then do the appropriate insert/update/delete on the syncTable with entityName.

This being the case, the new code in `MSSyncContext` at https://github.com/Azure/azure-mobile-services/blob/offline/sdk/iOS/src/MSSyncContext.m#L160-L176 throws an error when an insert occurs but the item already exists in the local store.

Could these two case statements be merged seeing as the actual operation is just an upsert? i.e.

```objective-c
case MSTableOperationUpdate:
case MSTableOperationInsert:
                    [self.dataSource upsertItems:[NSArray arrayWithObject:itemToSave] table:table orError:&error];
                    break;
```

And then the data source will continue to do the appropriate insert into the operation table for the server push to occur.

**Comment by phvannor** [comment]
Throwing an error when inserting an existing item that already was present locally, was a purposeful bug fix.  I see how this breaks your usage pattern though.  

If the insert read set the includesPendingChanges to NO in its fetch request, that would also fix this for you correct?  (Although, that probably requires a new method in MSSyncContextDataSource)

You are using the same MOC in your ViewControllers and the MSSyncConext?

**Comment by damienpontifex** [comment]
Just tried adding that to the fetch request in `-[MSCoreDataStore getRecordForTable:itemId:asDictionary:orError:]` but it still returned the object in the results. Hence, same problem for me.

For reference, this insert is called in my custom subclass will save method but before `[super willSave]` so not sure why this object still wouldn't be pending as I haven't completed the will save method flow.

Also, yes the MSCoreDataStore is instantiated with the managedObjectContext property of the saving object, so same context.

**Comment by damienpontifex** [comment]
@phvannor is there any updated guide for using NSManagedObject instances in code rather than the NSDictionary approach? I was trying to attain automatic saving to server messages. As a save to the context can cause a save of all objects in memory, sometimes it is troublesome to determine which objects to actually call the save method with the MSCoreDataStore to create the message.

I had also previously raised #287 but can see problems now with my implementation this case plus purge operations (which with my current setup will actually cause a remote delete, not just a local purge).

**Comment by damienpontifex** [comment]
I have been testing having two data stacks. One for application notification saves, updates, deletes which registers for NSManagedObjectContextDidSaveNotification on the context object that is used throughout the app. This uses the keys in the userInfo dictionary of NSInsertedObjectsKey, NSUpdatedObjectsKey and NSDeletedObjectsKey and then sends the appropriate message to the MSCoreDataStore for the objects.

When I do a push and/or pull, I utilise a completely new stack (model, persistent store coordinator and context) that is hooked up to the MSSyncContext. This seems to be working so far with having application level saving and messaging isolated from server saves/operations. 

I still can't seem to get around the issue with the item already being inserted though when the MSSyncContext checks for the existing item for a MSTableOperationInsert case.

Was your prototype similar to this setup? Or different?

**Comment by phvannor** [comment]
I'm hoping you don't need a new full stack (model and PSC), just a context.

Either way, the issue you hit will require a tweak in the store implementation. With the recent changes in the code, my original plan is now more complicated than I thought, so I am looking at adding a flag to the store that lets it opt out of local changes instead, like so:

https://github.com/phvannor/azure-mobile-services/commit/b00ec0acf36b961d651a01482d78113d88f025a8

I'll try to flush this out more in my free time, but I think that is the missing piece you would need. 

Then I thinking to add a helper class to generalize the context saving observation so everyone didn't need to do that parsing/etc.

**Comment by damienpontifex** [comment]
The mentioned commit seems to be about what I thought. @phvannor have you had any chance to work on this further? Or a branch that you are working on this that I could fork, test etc?

**Comment by phvannor** [comment]
Sadly, I haven't.  The commit I showed is on its own branch on my fork: 
https://github.com/phvannor/azure-mobile-services/tree/multiple-contexts

I do need to rebase back onto dev probably now that I merged offline into Dev.  I still need to try and flush out the observer, but I think you said you already had that piece so maybe what's there is good enough for your purposes.

**Comment by phvannor** [comment]
If you want, I can put it as a real branch off the mobile services repo, if you think you will want to contribute, as that may make things easier.

**Comment by damienpontifex** [comment]
Yes, integrating into the main repo and I can try and work out my use case and contribute back if it all works. Just let me know the branch you put it on

**Comment by phvannor** [comment]
ok, pushed to main repo now: https://github.com/Azure/azure-mobile-services/tree/multiple-contexts.

**Comment by damienpontifex** [comment]
@phvannor you mentioned about speaking to other customers about this. Has there been further feedback for features to be integrated with the multiple-contexts branch? 

I have continued using/testing this in one of my applications and seem to be without issue so far.

**Comment by phvannor** [comment]
So the far the main feedback has been on customization around the conversions between managed objects to dictionaries & back, essentially better support for adding/removing custom columns/properties/relationships to each object.  I haven't heard any issue with the main approach, I'll loop back with my team and if all looks good I will look at taking this into Dev early next week.

**Comment by damienpontifex** [comment]
That support could be added via optional methods on a protocol that the NSManagedObject subclass would have to conform to and could be called to get its configuration?

Assuming the entity has a class, such a protocol conformance would also indicate a mobile service entity to be synced and could get around the current check of ms_version property on the entity as well from [`-[MSManagedObjectObserver entityHasRemoteStoreAttributes]`](https://github.com/Azure/azure-mobile-services/blob/multiple-contexts/sdk/iOS/src/MSManagedObjectObserver.m#L55-L60) method we are currently doing as well.

**Comment by damienpontifex** [comment]
@phvannor is it possible to merge this into the MobileApp branch? It would be great to have this along with migrations to the new app services system.

**Comment by phvannor** [comment]
I wanted to take a deeper look at the context observing pattern, I was only able to get the items to update if I used the same context, which was causing pull to infinite loop (as the pull actions would be observed)  Can you add a snippet for how you are initializing the store and the observer.

**Comment by damienpontifex** [comment]
Here we go. Tried to extract out just the minimal needed to have this setup. Let me know if there's anything unclear or any suggested improvements.

```objective-c
// I have a class that wraps setting up of MSClient so it's init implementation is roughly
@interface DataService : NSObject
- (instancetype)initWithContext:(NSManagedObjectContext *)context;
@property (strong, nonatomic, readonly) MSClient *client;
@end

@implementation DataService
- (instancetype)initWithContext:(NSManagedObjectContext *)context
{
	if (self = [super init])
	{
		MSClient *client = [[MSCLient alloc] initWithApplicationURL:url applicationKey:key];
		MSCoreDataStore *store = [[MSCoreDataStore alloc] initWithManagedObjectContext:context];

		MSSyncContext *mainSyncContext = [[MSSyncContext alloc] initWithDelegate:nil dataSource:store callback:nil];

		mainClient.syncContext = mainSyncContext;
		
		self.client = client;
	}
	return self;
}
@end

NSManagedObjectContext *mainQueueContext; // This is the primary context setup for fetching objects for UI and then subsequent saves to be called on. Normaly setup with Xcode templates

DataService *mainDataService = [[DataService alloc] initWithContext:mainQueueContext];
MSManagedObjectObserver *saveObserver = [[MSManagedObjectObserver alloc] initWithClient:mainDataService.client]; // This is stored on a singleton somehwere. I store it on a singleton that handles synchronisation, but could also be on the UIApplicationDelegate instance

// This context has a shared persistentStoreCoordinator with the mainQueueContext. Will be used in all calls to push/pull
NSManagedObjectContext *syncContext = [[NSManagedObjectContext alloc] initWithConcurrencyType:NSMainQueueConcurrencyType];
syncContext.persistentStoreCoordinator = mainQueueContext.persistentStoreCoordinator;

DataService *syncService = [[DataService alloc] initWithContext:syncContext]; // It is with this data service/client instance that I use for all calls for table push/pull to avoid the observer also observing changes coming from the server

// Example of pull being...
MSSyncTable *todoSyncTable = [syncService.client syncTableWithName:"ToDo"];
MSQuery *query = [todoSyncTable query];
[todoSyncTable pullWithQuery:query queryId:queryId completion:completionBlock];
```

**Comment by phvannor** [comment]
Ok, I wasn't think of using 2 MSClient objects, which was why my original version had the observer take an array of contexts vs picking up the context from the client.  Do you end up doing much with the mainDataService that it has value to keep it around?

**Comment by damienpontifex** [comment]
No I don't keep it around/retain it anywhere. Just using it to handle the setup logic for the client in that instance. Under ARC, I assume it would be release at the end of the function call, although the client property would be retained by the observer and so hangs around there.

So no, no retention of the mainDataService.

**Comment by phvannor** [comment]
I think in order to play nice with future designs, I want these actions to be controlled by the same operation queues as the pulls/pushes.  So I will make a tweak to have the initializer take the context to observe directly and either modify the normal client / throw if the client is not configured to ignore sync table ops.  

After a pull / push finishes, what are you doing to get the changes back into the main queue context?  Do you observe in the reverse direction as well?  Just refresh objects / the context as needed?

**Comment by damienpontifex** [comment]
The call to insert/update/delete eventually goes onto the `writeOperationQueue` anyway.

On the observers: yes, I setup the same observers for context save (although nil for the object to be observed) on the view controllers and either refetch/refresh object/context as appropriate. Not sure what you mean by the reverse direction? The MSManagedObject observer will observe any user effect changes. And the observers in the view controllers will observe changes for the push/pull. Seems to be keeping everything in sync at the minute.

**Comment by phvannor** [comment]
I think I would need to make the writeOperationQueue a singleton for that to be true.  Both would have their own unique writeOpQ I think.  I did a quick PR to move to taking a context.  However, now the updates to copyWithZone and causing some internal test issues.  For a copy to get a new context, I need to update the internal queues to be the same between copies and tweak the clientWithFilter logic.  (Also cleanup the get next id logic for operations as that should also be shared between copies)

**Comment by damienpontifex** [comment]
Closing this as we can now define/manage this with #707 and #727
