### ISSUE TITLE
Incremental Pull feature: Query updates

### ISSUE THREAD

**Issue by ysxu** [Azure/azure-mobile-services#573]
1.
The following are not allowed on the query (or in the custom parameters in some cases): 
    __includeDeleted 
    __systemProperties 
    totalCount (although on Managed it's allowed but we just set it to false internally no matter what) 
    $select 
    $skip 
    $top 
    $orderby

2.
The following are automatically set for the query: 
    __includeDeleted=true  Note: make sure this is 'true' and not '1' 
    __systemProperties=__deleted,__updatedAt 
    $orderby=__updatedAt asc 

3.
Custom parameters are allowed should be appended to the automatically-created ones (__includeDeleted and __systemProperties)

**Comment by icsd** [comment]
How can i append the custom parameter __includeDeleted = false?
Should i do it in the push function?
