### ISSUE TITLE
Package could not be registered. version="1.0.1" 

### ISSUE THREAD

**Issue by rtroupin** [Azure/azure-mobile-services#576]
Added package to new xamarin PCL solution that built and deployed, compiled , tried deploying to emulator. results from output log below.

Any thoughts as to what issue might be?

1>------ Deploy started: Project: CC.HCApp.WinPhone, Configuration: Debug x86 ------
1>Deploying C:\Users\Rick\Source\Workspaces\HCA1_POC1\CC.HCApp\CC.HCApp\CC.HCApp.WinPhone\Bin\x86\Debug\CC.HCApp.WinPhone_Debug_x86.xap...
1>Connecting to Emulator 8.1 WVGA 4 inch 512MB...
1>Installing the application...
1>Deployment of application to device failed.
1>Package could not be registered.
========== Deploy: 0 succeeded, 1 failed, 0 skipped ==========

packages:
<packages>
  <package id="Microsoft.Bcl" version="1.1.9" targetFramework="wp81" />
  <package id="Microsoft.Bcl.Build" version="1.0.14" targetFramework="wp81" />
  <package id="Microsoft.Net.Http" version="2.2.28" targetFramework="wp81" />
  <package id="Newtonsoft.Json" version="6.0.4" targetFramework="wp81" />
  <package id="SQLitePCL" version="3.8.7.2" targetFramework="wp81" />
  <package id="WindowsAzure.MobileServices" version="1.3.1" targetFramework="wp81" />
  <package id="WindowsAzure.MobileServices.SQLiteStore" version="1.0.1" targetFramework="wp81" />
  <package id="WPtoolkit" version="4.2013.08.16" targetFramework="wp80" />
  <package id="Xamarin.Forms" version="1.3.1.6296" targetFramework="wp80" />
</packages>

**Comment by paulbatum** [comment]
This issue is quite old and we did not reproduce the error. Closing.
