### ISSUE TITLE
Facebook Authorize button cropped 

### ISSUE THREAD

**Issue by jasonleakey** [Azure/azure-mobile-services#577]
![device-2015-02-01-120538](https://cloud.githubusercontent.com/assets/2678449/5993630/eb8bdf3a-aa0b-11e4-9f6f-e38663c68bdb.png)
The Authorize button is cropped. Scrolling does not help. I guess the height of Webview is not computed correctly.

**Comment by jasonleakey** [comment]
version 1.1.5, Android sdk.

**Comment by ysxu** [comment]
Hi @jasonleakey We will follow up on this and keep you updated! Thanks!

**Comment by ysxu** [comment]
@jasonleakey 
Which Android device are you using this with?

Meanwhile, I recommend updating the SDK to ver 2.0.1 beta (link and changes at http://azure.microsoft.com/blog/2014/08/04/futures-support-and-breaking-changes-in-azure-mobile-services-android-sdk/), which introduces bug fixes to 1.1.5. We are working towards the general availability of this SDK in the upcoming weeks.

Thanks,
Mimi

**Comment by jasonleakey** [comment]
@ysxu I am using Nexus 4 Kitkat 4.4.4, and also Samsung Note 2 Jelly Bean 4.3. Both have this problem. It is around line 281 https://github.com/Azure/azure-mobile-services/blob/master/sdk/android/src/sdk/src/com/microsoft/windowsazure/mobileservices/LoginManager.java#L281. So please have a check. Thanks.

**Comment by ysxu** [comment]
@jasonleakey I am closing this issue with the above merged fix. Thanks.
