### ISSUE TITLE
MobileServiceSyncTable_IdMustBeString

### ISSUE THREAD

**Issue by nimatra** [Azure/azure-mobile-services#585]
What is this constraint about? 
It's breaking my app that was working just fine.

**Comment by phvannor** [comment]
There are a number of features that are required when using the sync table, for which the back end requires the Id to be a string.  Specifically optimistic concurrency, soft delete, and generally the system columns are driven off this concept.  

If you are using a .NET backend you can convert your actual Id into a string & back just for over the wire purposes.

For future relaxing of this constraint, what type are your Id columns and which backend are you using?

**Comment by nimatra** [comment]
I'm using Guid and long.
