### ISSUE TITLE
Add "PullAll" method to client SDKs

### ISSUE THREAD

**Issue by lindydonna** [Azure/azure-mobile-services#587]
Push pushes all changes. It would be useful to have a helper that would pull all sync tables (with their particular query).

**Comment by phvannor** [comment]
This would require a cache of all queries, and a plan to handle any dynamic pieces of the query.

**Comment by lindydonna** [comment]
Yeah, I was worried about that. I guess it's only easy if you are just querying all tables with no query. 

What should I do with the issue?

**Comment by lindydonna** [comment]
Closing because this is a non-trivial amount of work, for a very minor benefit. Developers should just put all of the pull calls in one method and call that when they want to pull everything.
