### ISSUE TITLE
Add pull handler to client SDKs

### ISSUE THREAD

**Issue by lindydonna** [Azure/azure-mobile-services#588]
When pulling a lot of data, there are 2 pieces of additional functionality that developers want: a) see what has changed after the last pull, and b) get notified during pull to display a progress bar.

For (a), it is possible to store the latest updatedAt and use that to find out what's changed (e.g., for updating the UI). For the second part, you'd have to add a delegating handler, but then also be able to distinguish offline-related requests (using a header?). 

A pull handler would accomplish both of these.

**Comment by paulbatum** [comment]
@lindydonna @fabiocav does the notifications API we added to the managed SDK address this? If so we could instead file new issues to track bring the equivalent functionality to other platforms and then close this.

**Comment by fabiocav** [comment]
Yes, the new notifications API we've added would address those requirements, so I think we can safely close this and open issues on the other platforms repositories to implement that functionality.

**Comment by phvannor** [comment]
I don't think a notification API covers the full use case of a Pull Handler, there remains a need to modify the data going into the store (before it saves) and the notification system would be after the fact that I'm not convinced actually works as needed.

**Comment by fabiocav** [comment]
@phvannor I agree that the notification API does not cover the full use case of the pull handler. But it does address the two requirements outlined by @lindydonna above, so for the scope of this issue, I think we have what we need.

**Comment by phvannor** [comment]
I think this is supposed to be the general issue for a pull handler, those are just the examples Donna particularly cares about.  I just dont think those are the only important ones.

**Comment by fabiocav** [comment]
If that's really the case, I agree that we should keep this open, but should also clarify the description to cover the additional cases.

**Comment by paulbatum** [comment]
@phvannor @lindydonna Please update this issue with scenarios for which the pull handler is still necessary so we can triage.

**Comment by phvannor** [comment]
A proper pull handler would allow:
- Modification & review of the data prior to insertion into the local store, which is required as a workaround if you want to follow a $expand, etc type entities.
- Ability to alter URLs/endpoints being hit (say use of a custom API for retrieving records/etc
- Required hook point for automated conflict resolution patterns, details should be in those docs/designs
- You'll get more accurate & better perf for cases a & b here than via notifications (esp once you consider the push portion of a pull and if you need any of the actual record data for these cases)

**Comment by lindydonna** [comment]
@phvannor The intent of the original issue was to handle the scenario that @fabiocav has already implemented with the notifications support. You're right that a proper "pull handler" would have the features you said, but I think I just used the wrong term. I think that we don't have enough evidence that a pull handler as you describe really addresses top customer issues.

**Comment by phvannor** [comment]
I need a generic pull handler issue opened on apps for tracking.  I also need more details on notifications handling of a & b, as I don't think it'd handle them quite right as is.

**Comment by lindydonna** [comment]
We could create an issue just for tracking, but is it a good idea to create issues we don't plan to fix anytime soon?  I think that the situations a & b in my example are covered by Fabio's notifications work, since he has a way of getting a batch notification and individual updates.

**Comment by phvannor** [comment]
Feature requests are quite common.  Plus we get more requests on conflict handling, relationships and configuring endpoints to be hit than I've seen on progress notifications.  Adding the right hooks in here is required to provide any workaround for those users until we get to said features.

**Comment by phvannor** [comment]
@fabiocav can you outline how you'd use notifications to implement b?

**Comment by paulbatum** [comment]
Since one way or another we don't plan on doing feature work like this on the old version of our SDKs, please file a new feature request issue against azure-mobile-apps outlining the net new features requested here beyond what notifications already covers, so we can close this issue.

**Comment by adrianhall** [comment]
We are moving all attention to azure-mobile-apps - closing this.
