### ISSUE TITLE
Support Request for Firefox OS App

### ISSUE THREAD

**Issue by iwate** [Azure/azure-mobile-services#589]
I am participating Firefox OS Hackathon now.
Firefox OS is very cool OS of open source! And I want to use it with Mobile Service!
 
I try connect them but it is impossible on mobile service's specification. Because `origin` property of Firefox OS App are like `app://xxx.contoso.com`.

I had success to connect them by using c# backend.(http://iwate.github.io/redfox/)

How do you feel about Firefox OS App support?

**Comment by adrianhall** [comment]
We will not be supporting the Firefox OS App.
