### ISSUE TITLE
Client UnAuthorized Handler - Javascript

### ISSUE THREAD

**Issue by nikatlas** [Azure/azure-mobile-services#593]
Maybe add Interception idea to WebRequests Callbacks. 

I mean it would be great to be able to handle all 401 responses in one place. 

PS: If its already implemented im sorry couldnt find it.

**Comment by phvannor** [comment]
You should be able to do this with the filter option off the client:
https://github.com/Azure/azure-mobile-services/blob/master/sdk/Javascript/src/MobileServiceClient.js#L85

Also, here's it in use in our test code to mock the server response: https://github.com/Azure/azure-mobile-services/blob/master/sdk/Javascript/test/winJS/tests/unit/mobileServicesClient.js#L59

If you make a filter on your top level client, and use that filtered client everywhere you should be able to handle all 401's in one place.  Let me know if it doesn't work for you.

**Comment by phvannor** [comment]
Closing for now, I'll reopen if you are unable to accomplish your goal with the filters.

**Comment by nikatlas** [comment]
Worked like a charm. :)
