### ISSUE TITLE
MSSyncTable.m and other Offline Sync files missing from repository.

### ISSUE THREAD

**Issue by j3rm** [Azure/azure-mobile-services#599]
The WindowsAzureMobileServices.framework source appears to still be the previous version (pre Sync Tables version)

Can you please update the WindowsAzureMobileServices.framework so it contains all the code for the MSSyncTables. 
Thanks

**Comment by phvannor** [comment]
While offline for iOS is in beta, the beta framework source is in the offline branch, https://github.com/Azure/azure-mobile-services/tree/offline.  

When it goes to GA it will be merged into the Dev & Master branches.
