### ISSUE TITLE
Datetime Problem on Where Clause Javascript

### ISSUE THREAD

**Issue by nikatlas** [Azure/azure-mobile-services#601]
```javascript
table.take(0).where(function (at) {
                                    return this.__updatedAt > new Date(at);
                                }, maxUpdatedAtSaved )
                        .includeTotalCount().read().then(function (results) { ... 
```

Using this code to get the number of updates since i last updated my data returns a 400 Bad Request with the message : 
{"message":"The query specified in the URI is not valid. A binary operator with incompatible types was detected. Found operand types 'Edm.DateTimeOffset' and 'Edm.DateTime' for operator kind 'GreaterThan'."}

Dunno how to get That dateTime switch to dateTime Offset...

**Comment by nikatlas** [comment]
I found on the js sdk the following code : 
<code>
 else if (_.isDate(value)) {
                /*
                 * Dates are expected in the format
                 *   "datetime'yyyy-mm-ddThh:mm[:ss[.fffffff]]'"
                 * which JSON.stringify gives us by default
                 */
                text = JSON.stringify(value);
                if (text.length > 2) {
                  text = text.slice(1, +(text.length - 2) + 1 || 9e9);
                }
                text = text.replace(/(T\d{2}:\d{2}:\d{2})Z$/, function(all, time) {
                  var msec;
                  msec = String(value.getMilliseconds() + 1000).substring(1);
                  return "" + time + "." + msec + "Z";
                });
                return "datetime'" + text + "'"; < ------------ Error!!!Should be datetimeoffset
              } 
</code>

**Comment by phvannor** [comment]
This is something we are aware of, for iOS we ended up making a DateOffset class, that we knew to convert to datetimeoffset vs datetime.   

For now, you can pass the raw oData query to your calls.  One option (for the short term) is to use a query, call query.toOData, and then replace datetime to datetimeoffset in the result.  Then pass that into the read call.  It should unblock you for now.

Another, if you don't need datetime support at all, is to copy the file from the cdn (http://ajax.aspnetcdn.com/ajax/mobileservices/MobileServices.Web-1.2.6.js) and tweak it / rebuild out of source.

**Comment by nikatlas** [comment]
Thx for the fast response :). 

I have already changed the source code to datetimeoffset since i dont really need datetime yet.
Though i had problem minifing the source if you can help me here ? 

Plz tell me if you intend to fix this in the short term cause we are building a commercial product and need the stable version.

**Comment by phvannor** [comment]
I'll try to take a look at this tomorrow and see if there is a quick fix we can do to solve this now to get an official fix in quickly.  

If you clone the JS repo, you should be able to use grunt to get the minified version, the default task should just work.  If not, let me know what issues you are seeing building.  I realize, we probably need to update the readme for ppl not familiar with using grunt.

**Comment by phvannor** [comment]
This will require updating the queryJS repo first: https://github.com/Azure/queryjs

**Comment by phvannor** [comment]
@nikatlas Did you close this as you have a workaround that works for you / no longer need it.  Or did you find a way to fix this w/o a code fix?
