### ISSUE TITLE
MobileServiceUser.UserId returned from MobileServiceClient.LoginAsync() is not an Active Directory ID

### ISSUE THREAD

**Issue by brbarnett** [Azure/azure-mobile-services#605]
I am authenticating a Universal App's Mobile Services using MobileServiceClient.LoginAsync(MobileServiceAuthenticationProvider.WindowsAzureActiveDirectory), which is working. It his, however, not returning any ID that I can find within our Azure Active Directory (I'm checking the UserId that returns against pretty much every string I can find in AD) on my record. What is the source of this ID? I would expect it to be something that I could find prior to actually logging in. 

For context, my UserId from LoginAsync() call: BN5IDltpjLY3vxvzqddPojKAF3nb64yy5FjaEikpuyU

**Comment by mattchenderson** [comment]
The ID is unique to the application registration in AAD - it is not a global property of the AAD user. If you want a global identifier, then you should look at the ObjectID property on the server (via a call to getIdentitiesAsync()).

**Comment by brbarnett** [comment]
OK - figured we could use this as a known value - we'll find a Graph-based workaround.  Thank you
