### ISSUE TITLE
Creating pending operations during in-flight PushAction has race conditions that cause several bugs

### ISSUE THREAD

**Issue by masojus** [Azure/azure-mobile-services#615]
Thanks all for the good work on AMS and for providing a lot of functionality that's easy to get working quickly. I wanted to get some feedback on some naughty behavior I'm seeing around Offline Sync when pending operations on the local store are created while a push is currently executing.

See #614 for a Unit Test that exhibits parts of this behavior.
Related issues: #413, #493, #612 

The short version is that if you generate pending operations while a push is in-flight, there are various race conditions that occur, which generate a plethora of bugs. We end up with stale versions, stale operations in the OperationQueue, erroneously-cancelled pending operations, false merge conflicts, inconsistency between local store and back-end, SyncErrors being swallowed and/or exceptions thrown for a variety of reasons.

The reasons are myriad, but fundamentally, the PushAction can fail to delete operations before subsequent operations look at the queue and try to Collapse(), and even if it does delete an operation, we can Enqueue() to the OpQueue at any time, even with an in-flight PushAction, and we Collapse() onto/Enqueue()/Update()/generally use operations that are stale without verification and without any synchronization. This is contrary to the comments in issue #413 indicating that we can't cause an operation to try to Collapse() onto a failed InsertOperation, because my unit test exhibits exactly that behavior. In the best case here, we see the behavior in Issue #612, where we operate with old version numbers for subsequent operations, because they were already waiting on the item lock, with the item version already captured, when the push may or may not have updated the version in the local store, so all waiting operations will cause a merge conflict with the back-end. In the worst case, we throw, or we cancel pending operations, delete SyncErrors from the errors list without notifying client code, end up with inconsistencies between the back-end and the local store, and put stale operations back into the OpQueue.

Please take a look at [this document](https://onedrive.live.com/?cid=3E227B64092E6F3B&id=3E227B64092E6F3B%21114133) for a full description of the 12-14 bugs that I found this afternoon while looking a little deeper into this odd behavior. Note that the document has call stacks in it, but if you scan down, you'll see the text "Bug #" along with a description of each bug as it occurs while walking through the scenario the unit test in pull request #614 encapsulates.

Thanks in advance for any feedback and/or advice!

**Comment by masojus** [comment]
Note that I pushed another commit to the fork for pull request #614, and this commit fixes part of the problem, but as stated in the comments for that commit, and the subsequent conversation with @phvannor, that fix commit can't be taken as-is since you can obliterate server changes.  However, it does demonstrate at least an idea for fixing the case where you're queuing up a bunch of operations from a single client, and it handles a lot of the effects of the race condition(s) described in this issue.  Thanks!

**Comment by lindydonna** [comment]
@masojus, thanks for the detailed issue write-up and the pull request!  We'll make sure to fix these bugs, though we don't have an ETA yet.
