### ISSUE TITLE
Using asynchronous operations in Android Offline SDK version 2.0.2beta causes race conditions in the local database

### ISSUE THREAD

**Issue by jonsheller** [Azure/azure-mobile-services#622]
Code such as the following:

    MobileServiceSyncTable<StringIdType> table2 = client.getSyncTable(StringIdType.class);

    ListenableFuture lookupResult;
    ListenableFuture deleteResult;
			
    lookupResult = table2.lookUp("an id");
    deleteResult = table2.delete(item2);

causes an exception to be thrown from the SQLiteDatabase because the database is closed from under the current operation.

The exception thrown is
    java.lang.IllegalStateException: Cannot perform this operation because the connection pool has been closed

In SQLiteLocalStore, the database handle is closed after each operation. Because Android shares the same database between all calls until it is closed, another in-flight call can have the database closed from under it. I frequently see this error in my app when deleting several items in succession.

The only workaround is to make all operations that use the table synchronous by immediately calling ListenableFuture.get with the result from the asynchronous operation.

**Comment by jonsheller** [comment]
Commit 08498e21f7ba667fe5515a00ef0965d357a8a6a5 shows a unit test that demonstrates this behavior.

**Comment by jonsheller** [comment]
And commit a02c879c9fde4ce1a753e05c278e7d6d001f7606 shows the same problem with simultaneous deletes.

**Comment by ysxu** [comment]
@marianosz per you chat with @phvannor and @soninaren, we will need to implement a lock mechanism on SQL lite store via Queue.

**Comment by jonsheller** [comment]
I just submitted a pull request that fixes the issue by protecting the database as long as there's a currently active thread that has a reference. There may be other reasons to prefer a queue, but this fixes at least this specific issue. Let me know what you think!

**Comment by phvannor** [comment]
No a Queue is not required, any locking type mechanism should work.

**Comment by jonsheller** [comment]
@phvanorr Do you guys feel that only one thread at a time should be allowed to access the SQLiteLocalStore? My pull request doesn't do this. It protects the database by keeping a count of concurrent users.

**Comment by phvannor** [comment]
@jonsheller not necessarily, I'm not familiar enough with the Android implementation to say.  I did a lot of the iOS implementation, where CoreData confinement requires all access from the same thread/queue, so its gotten into my head to think that way.

The locking/etc can be done at different levels, and while keeping Localstore access to 1 thread is an easy option, its not the only one. (I believe the way we accomplish this is done differently between the managed & iOS SDKs)

**Comment by ysxu** [comment]
Merged

**Comment by jonsheller** [comment]
I'm not seeing the fix for this change in any branch. Any idea where it's gone? The branch it was merged into has been deleted.

**Comment by phvannor** [comment]
@jonsheller not sure why it got opened (or merged) into that partcular branch.  I have moved it over to the Android branch from my local copy of that branch.  See: 
   https://github.com/Azure/azure-mobile-services/pull/667

to confirm it all looks ok.  Let me sync with @soninaren and @marianosz to see what happenend here.

**Comment by jonsheller** [comment]
@phvannor Looks good, thanks.

**Comment by phvannor** [comment]
OK this is merged correctly into Android now. FYI, over the next week or so, we expect Android will be merged back into Dev putting all 4 SDKs codebases back into 1 unified branch again.
