### ISSUE TITLE
PushAsync() not working when deployed to device

### ISSUE THREAD

**Issue by brbarnett** [Azure/azure-mobile-services#649]
I am using offline services with a custom SyncHandler : IMobileServiceSyncHandler, which is initializing OK.  When connected to emulator or device via VS 2013, PushAsync() calls ExecuteTableOperationAsync within the SyncHandler for each pending operation, and data uploads to my Mobile Service instance.

We added a bit of logging and found out that when we create an app package (Release - Device (ARM) configuration) and side-load using the Windows Phone Application Deployment (8.1) tool, PushAsync() does *not* call ExecuteTableOperationAsync, and therefore no data gets uploaded to our Mobile Service.  There are no exceptions in MobileServicePushCompletionResult, which completes and runs successfully.  Additionally, the PushAsync() task does not throw any exceptions at all.

Wondering if anyone had seen this behavior?  This is ONLY when deployed (debug or release) to a device using the deployment tool -- works fine while connected to VS.

**Comment by brbarnett** [comment]
A little more debugging, for what it's worth:

Prior to PushAsync():
CommandHandler:PushAllDataToServerCommand:SyncContext.IsInitialized = true
CommandHandler:PushAllDataToServerCommand:SyncContext.PendingOperations = 1

After calling PushAsync():
SyncHandler:OnPushCompleteAsync:MobileServicePushCompletionResult.Status = Complete
SyncHandler:OnPushCompleteAsync:Push complete
CommandHandler:PushAllDataToServerCommand:PushAsyncTask.IsCompleted = true
CommandHandler:PushAllDataToServerCommand:PushAsyncTask.IsFaulted = false
CommandHandler:PushAllDataToServerCommand:PushAsyncTask success

PushAsync() does call OnPushCompleteAsync, which suggests the SyncHandler is wired up correctly.  It does not hit my logging statement at the entry point of ExecuteTableOperationAsync, so it seems to me that it never invokes that method.

**Comment by brbarnett** [comment]
More information:

Creating an .appx package in x86 architecture and pushing to the emulator *does* work, but an .appx package in ARM architecture does *not* work.  This leads me to believe that the difference in build under the two different architectures is causing the problem -- perhaps it's an incompatibility issue.  I will say that when I open up the .appx files as .zip, the only real difference I can see is that the sqlite3.dll compiles to 1,034 KB in ARM, but only 845 KB in x86.  I'm not necessarily suggesting that is a problem, but it is a notable difference between the package types.

I have tried on 3 completely different devices, and it fails the same way each time -- therefore, I think we can rule out a specific device issue (so it's likely not a firmware bug, for example).

**Comment by phvannor** [comment]
To start, can you verify you followed the steps documented in SQLitePCL on https://sqlitepcl.codeplex.com/documentation, Windows Phone Runtime 8.1 (Universal App) Applications?

Typically, for PushComplete() to fire w/o firing a ExecuteTableOp() call, that would mean there are no pending operations in the Queue.  After you run Push(), your pending count is back to 0?

Relevant code should be here:
https://github.com/Azure/azure-mobile-services/blob/master/sdk/Managed/src/Microsoft.WindowsAzure.MobileServices/Table/Sync/Queue/Actions/PushAction.cs#L179

I'm not sure what can go wrong here that can cause it not be called and not raise an error.

**Comment by brbarnett** [comment]
Great questions, and thanks for your response!

We did follow that, and have SQLite 3.8.8.3 (Phone 8.1) + the SDK version you mentioned.  Also, v1.3.1 of Windows Azure Mobile Services.

Calling PushAsync() seems to return correctly, but does not return PendingOperations to 0 -- in fact, if I complete additional operations, it adds to that count.  So the Task returns OK, no exceptions thrown, and PendingOperations stays the same.

**Comment by lindydonna** [comment]
@brbarnett This might be related to a bug in the CLR having to do with loading localized resources. Are you building an 8.1 Silverlight app, or the new WinRT style?

**Comment by brbarnett** [comment]
@lindydonna - I'd seen the same resources bug before in version 1.3.0 (at least that you're referencing).  It's a Universal App, so WinRT.  We're not receiving an exception like I saw with 1.3.0, but I suppose that doesn't mean it's not throwing one somewhere along the async/await trail.  By all appearances, the PullAsync() task just never completes, regardless of debug/release builds.

**Comment by brbarnett** [comment]
I have also attempted giving the app *all* Requirements and Capabilities in the Package.appxmanifest, but that didn't change anything.  Figured it could be some sort of permissions issue, but that's not the case.  We're only using Rear Camera (barcode scanner), Internet and Webcam (also barcode scanner), which works for everything else.  No Declarations

**Comment by phvannor** [comment]
I believe we concluded this issue was due to the CLR core issue (#658), that we now have a workaround in place for with the 1.3.2 sdk & 1.0.4 store packages.   If not, let me know and I'll reopen.

**Comment by michalkovy** [comment]
I have started seeing the same behavior on release builds with .NET Native. I have recently upgraded Microsoft.Azure.Mobile.Client* from 2.0.1 to 2.1.0 and Microsoft.NETCore.UniversalWindowsPlatform from 5.2.0 to 5.2.2. I see that the related CLR core issue has been closed without resolution (with note that they will reopen if it reappears)

**Comment by lindydonna** [comment]
This looks like a duplicate of https://github.com/Azure/azure-mobile-apps-net-client/issues/185, which has detailed information about the potential root cause.
