### ISSUE TITLE
[iOS] Auto synthesised properties

### ISSUE THREAD

**Issue by damienpontifex** [Azure/azure-mobile-services#659]
More of a suggestion/question. Since Xcode and LLVM will auto synthesise properties, should we consider removing all explicit synthesise of these properties in the iOS SDK project?

This will move to a convention of a leading underscore in backing variable names vs the current use of trailing underscores. Google have also noted that they have updated their Objective-C [style guide](https://google-styleguide.googlecode.com/svn/trunk/objcguide.xml?showone=Trailing_vs_Leading_Underscores#Trailing_vs_Leading_Underscores) to reflect this change as well.

I don't mind doing this, but would consult before proposing the change if there is an existing pattern/convention in place for the project?

**Comment by phvannor** [comment]
moved to https://github.com/Azure/azure-mobile-apps-ios-client/issues/26
