### ISSUE TITLE
Insert 1:N relationship from iOS Azure Mobile Services

### ISSUE THREAD

**Issue by attiqeurrehman** [Azure/azure-mobile-services#664]
I have a offline sync enabled table Search that 1:N relationship with couple of tables like Criteria and Results. I want to insert Search object that contains it's fields and criteria object and results.

Here's my code:

NSDictionary *criteria = nil; //suppose it have keys and values
NSArray *results = nil; //array of dictionary
NSDictionary *item = @{@"title": @"Huray", @"userId":@"Facebook:1231231231232", @"favourite":@NO, @"criteria":criteria, @"results": results};

[self.searchService addItem:item completion:nil];

I know that I have to write some scripts for the Node.js backend and if my backend is .NET then I probably wouldn't have to write custom code but what do I have to do for local store

-(void)insert:(NSDictionary *)item completion:(MSSyncItemBlock)completion;

insert method only insert and send search table fields both on local store and server. What do I have to do to insert Search table with relationship on both local store and server?

**Comment by paulbatum** [comment]
We have received many requests for relationship support. We need to start consolidating this feedback into a single feature writeup. See https://github.com/Azure/azure-mobile-apps/issues/6.
