### ISSUE TITLE
is it possible that in iOS SDK "registerNativeWithDeviceToken" will cause duplication registration/notification problem?

### ISSUE THREAD

**Issue by airbob** [Azure/azure-mobile-services#668]
On our iOS client side, we use ```registerNativeWithDeviceToken``` method to register the device token with notification hub.

The problem we encounter now is that user receive duplicate notifications sometimes. 
So I want to check with you the implementation logic of  ```registerNativeWithDeviceToken``` in notification hub, is it possible that this method will cause the duplicate registration problem?

**Comment by phvannor** [comment]
When you say in notification hubs, did you mean the implementation in this repo (in MSPush off the MSClient) or the version in the notification hub repo (https://github.com/Azure/azure-notificationhubs/)?

If the latter can you open this issue against that repo?

The implementation in mobile services caches the registration, and updates it after that.  So you shouldn't get a duplicate unless you are clearing out the storage item we are using in your NSUserDefaults.  The implementation is here: https://github.com/Azure/azure-mobile-services/blob/master/sdk/iOS/src/MSPush.m#L32

The relevant look up from the cache is here:
https://github.com/Azure/azure-mobile-services/blob/master/sdk/iOS/src/MSRegistrationManager.m#L77

**Comment by airbob** [comment]
Thanks @phvannor , I checked the source code and it works as expected, so ```registerNativeWithDeviceToken ``` shouldn't be the cause of my problem.

You may close this issue, thank you for your answer.
