### ISSUE TITLE
[iOS] Add Objective-C language enhancements for nullability

### ISSUE THREAD

**Issue by damienpontifex** [Azure/azure-mobile-services#669]
In the [Objective-C Language Enhancements](https://developer.apple.com/library/ios/releasenotes/DeveloperTools/RN-Xcode/Chapters/Introduction.html#//apple_ref/doc/uid/TP40001051-CH1-SW10) for Xcode 6.3 release notes: parameters, return types and properties can now be annotated with their nullability. 

I have done an example on MSClient.h with this commit damienpontifex/azure-mobile-services@17fc313

Can this be implemented among the classes for the iOS SDK?

**Comment by phvannor** [comment]
Looks feasible, from what I can tell it shouldn't impact users of the fw on older platforms.

**Comment by damienpontifex** [comment]
I believe it is all just compiler checking (mainly for Swift, but also with ObjC benefits) so shouldn't effect older target platforms. Would require developers to be on Xcode 6.3 or above.

**Comment by damienpontifex** [comment]
Closing with integration of #715
