### ISSUE TITLE
Problem using the WindowsAzureMobileServices.framework target in a Swift Framework

### ISSUE THREAD

**Issue by AlexandreBoyerLaporte** [Azure/azure-mobile-services#670]
There is a difficulty using the WindowsAzureMobileServices.framework target in a Swift embedded framework. The problem arises from mixing Swift and Objective-C in an embedded framework. I worked around the issue by creating a new embedded framework project with the source code of Windows Azure Mobile Services and importing the framework into my Swift embedded framework. It is not a big issue but adding an Objective-C embedded framework when you checkout the project would be nice. 

Cheers,

**Comment by damienpontifex** [comment]
I have the WindowsAzureMobileServices solution linked against a Swift embedded framework by using Cocoapods and the `use_frameworks!` flag inside my Podfile. I have a custom Podspec as the repo here doesn't have one (and also allows me to develop against a custom branch of the repo and my own fork of it etc). Doing this, allows me to keep up to date with the work here and link against the Swift framework without any obj-c issues. My Podspec (linked to my fork at the moment) is:

```ruby
Pod::Spec.new do |s|
  s.name         = "WindowsAzureMobileServices"
  s.version      = "1.2.1"
  s.summary      = "Integrate with Azure Mobile Services"
  s.homepage     = "https://github.com/Azure/azure-mobile-services"
  s.license      = { 
    :type => "Apache", 
    :file => "LICENSE.txt" 
  }
  s.author       = { 
    "Damien Pontifex" => "damien.pontifex@gmail.com" 
  }
  s.platform     = :ios, "8.0"
  s.source       = { 
    :git => "https://github.com/damienpontifex/azure-mobile-services.git", 
    :branch => "multiple-contexts" 
  }
  s.requires_arc = true
  s.source_files = "Classes", "sdk/iOS/src/**/*.{h,m}"
  s.public_header_files = "sdk/iOS/src/**/*.h"
  s.private_header_files = "sdk/iOS/src/*Internal.h"
  s.requires_arc = true
end

```

**Comment by phvannor** [comment]
I have started on the inclusion of an official podspec on the new repo: https://github.com/Azure/azure-mobile-apps-ios-client/pull/1

I need to finalize a name yet, confirm we will go with AzureMobileApps, or stay with WindowsAzureMobileServices/etc.  

In my (limited) testing so far, this seems to work.  If you have issues do you mind opening on the new source repo instead?
