### ISSUE TITLE
Support for Relationships between entities (1:1, 1:m. m:n)

### ISSUE THREAD

**Issue by ltaljaard** [Azure/azure-mobile-services#671]
Hello, can I please have your opinion on the following workaround for the current lack of support for relationships in Azure Mobile Services?

At app startup on the mobile device, do the following query to the server to read all the ID's only of the related objects to the given Agent object that we're trying to pull into the mobile device's DB:

var agent_json = await mobileServiceClient.GetTable().ReadAsync( "$expand=Person,Roles,Agency,Agency/Candidates,Agency/Candidates/Person" +
"&$select=Person/Id,Roles/Id,Agency/Id,Agency/Candidates/Id,Agency/Candidates/Person/Id" +
"&$filter=Person/LogonId eq '" + userID + "'");

Agent agent_with_related_entities = Newtonsoft.Json.JsonConvert.DeserializeObject(agent_json.First.ToString());

Then loop through the returned object graph and call PullAsync() for each related object as follows - e.g. for Person:

mobileServiceClient.GetSyncTable ().PullAsync("PersonWithID" + [person ID obtained from traversing the above graph], mobileServiceClient.GetSyncTable ().Where(p => p.Id == [person ID obtained from traversing the above graph]));

Would that effectively give me incremental sync for all the related objects? And would that also "soft delete" (assuming that soft delete is turned on) any objects in the local device DB (and/or their relationships) that are NOT related anymore (i.e. where the related object was deleted on the server or where the relationship between the two objects were broken) ?

Could you also advise if and when you plan on incorporating official support for this? And if you are not planning on supporting it may I ask the reason for that decision? Would it then at least be possible to provide some guidance on how I should go about it to build this myself?

**Comment by paulbatum** [comment]
We have received many requests for relationship support. We need to start consolidating this feedback into a single feature writeup. Moved to https://github.com/Azure/azure-mobile-apps/issues/6.
