### ISSUE TITLE
Android "Invalid length" exception when parsing dates

### ISSUE THREAD

**Issue by lordjesus** [Azure/azure-mobile-services#694]
Using ``'com.microsoft.azure:azure-mobile-services-android-sdk:2.0.2-beta2'`` via Gradle.

There is a problem with the implementation of ``DateSerializer.deserialize(String strVal)`` where it assumes a string length of 28, which is not always the case.

Example: the string ``"19-05-2014 11:46:45"`` is parsed on the C# backend with the function

    public static DateTime ParseDateTime(string value)
        {
            var dt = new DateTime();
            try
            {
                dt = Convert.ToDateTime(value);
            }
            catch (FormatException)
            {
                dt = DateTime.ParseExact(value, "d-M-yyyy HH:mm:ss", System.Globalization.CultureInfo.InvariantCulture);
            }
            return dt;
        }

and is saved on an object via ``context.SaveChanges()``

The object is then queried from Android with

    Query q = mClient.getTable(Inspection.class).where().field("customerid").eq(cust.getId());
    MobileServiceList<Inspection> inspList = mInspectionTable.read(q).get();

but this results in the error message provided below.

When I try to debug the ``deserialize`` method, I can see that the variable ``s = "2014-05-19T11:45:49+00:00"`` and the argument ``strVal = "2014-05-19T11:45:49Z"``. Hence the substring operations (0,26) and (27) will throw the exception since ``s`` is only 25 characters long, even though the date is perfectly valid and is coming from the C# backend, stored as a normal Date in the Azure SQL database.

    05-06 12:15:52.957  15062-15062/app.dkh.azureprototype W/System.err﹕ java.util.concurrent.ExecutionException: com.google.gson.JsonParseException: Invalid length
    05-06 12:15:52.964  15062-15062/app.dkh.azureprototype W/System.err﹕ at com.google.common.util.concurrent.AbstractFuture$Sync.getValue(AbstractFuture.java:299)
    05-06 12:15:52.964  15062-15062/app.dkh.azureprototype W/System.err﹕ at com.google.common.util.concurrent.AbstractFuture$Sync.get(AbstractFuture.java:286)
    05-06 12:15:52.964  15062-15062/app.dkh.azureprototype W/System.err﹕ at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:116)
    05-06 12:15:52.964  15062-15062/app.dkh.azureprototype W/System.err﹕ at app.dkh.azureprototype.MainActivityFragment.initInspections(MainActivityFragment.java:222)
    05-06 12:15:52.964  15062-15062/app.dkh.azureprototype W/System.err﹕ at app.dkh.azureprototype.MainActivityFragment.fetchInspections(MainActivityFragment.java:155)
    05-06 12:15:52.964  15062-15062/app.dkh.azureprototype W/System.err﹕ at app.dkh.azureprototype.MainActivityFragment.init(MainActivityFragment.java:112)
    05-06 12:15:52.964  15062-15062/app.dkh.azureprototype W/System.err﹕ at app.dkh.azureprototype.MainActivityFragment.onResume(MainActivityFragment.java:318)
    05-06 12:15:52.964  15062-15062/app.dkh.azureprototype W/System.err﹕ at android.support.v4.app.Fragment.performResume(Fragment.java:1829)
    05-06 12:15:52.964  15062-15062/app.dkh.azureprototype W/System.err﹕ at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:993)
    05-06 12:15:52.964  15062-15062/app.dkh.azureprototype W/System.err﹕ at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1136)
    05-06 12:15:52.964  15062-15062/app.dkh.azureprototype W/System.err﹕ at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1118)
    05-06 12:15:52.964  15062-15062/app.dkh.azureprototype W/System.err﹕ at android.support.v4.app.FragmentManagerImpl.dispatchResume(FragmentManager.java:1937)
    05-06 12:15:52.964  15062-15062/app.dkh.azureprototype W/System.err﹕ at android.support.v4.app.FragmentActivity.onResumeFragments(FragmentActivity.java:444)
    05-06 12:15:52.964  15062-15062/app.dkh.azureprototype W/System.err﹕ at android.support.v4.app.FragmentActivity.onPostResume(FragmentActivity.java:433)
    05-06 12:15:52.965  15062-15062/app.dkh.azureprototype W/System.err﹕ at android.support.v7.app.ActionBarActivity.onPostResume(ActionBarActivity.java:146)
    05-06 12:15:52.965  15062-15062/app.dkh.azureprototype W/System.err﹕ at android.app.Activity.performResume(Activity.java:6076)
    05-06 12:15:52.965  15062-15062/app.dkh.azureprototype W/System.err﹕ at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2947)
    05-06 12:15:52.965  15062-15062/app.dkh.azureprototype W/System.err﹕ at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2989)
    05-06 12:15:52.965  15062-15062/app.dkh.azureprototype W/System.err﹕ at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2372)
    05-06 12:15:52.965  15062-15062/app.dkh.azureprototype W/System.err﹕ at android.app.ActivityThread.access$800(ActivityThread.java:148)
    05-06 12:15:52.965  15062-15062/app.dkh.azureprototype W/System.err﹕ at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1283)
    05-06 12:15:52.965  15062-15062/app.dkh.azureprototype W/System.err﹕ at android.os.Handler.dispatchMessage(Handler.java:102)
    05-06 12:15:52.965  15062-15062/app.dkh.azureprototype W/System.err﹕ at android.os.Looper.loop(Looper.java:135)
    05-06 12:15:52.965  15062-15062/app.dkh.azureprototype W/System.err﹕ at android.app.ActivityThread.main(ActivityThread.java:5274)
    05-06 12:15:52.965  15062-15062/app.dkh.azureprototype W/System.err﹕ at java.lang.reflect.Method.invoke(Native Method)
    05-06 12:15:52.965  15062-15062/app.dkh.azureprototype W/System.err﹕ at java.lang.reflect.Method.invoke(Method.java:372)
    05-06 12:15:52.965  15062-15062/app.dkh.azureprototype W/System.err﹕ at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:909)
    05-06 12:15:52.965  15062-15062/app.dkh.azureprototype W/System.err﹕ at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:704)
    05-06 12:15:52.965  15062-15062/app.dkh.azureprototype W/System.err﹕ Caused by: com.google.gson.JsonParseException: Invalid length
    05-06 12:15:52.965  15062-15062/app.dkh.azureprototype W/System.err﹕ at com.microsoft.windowsazure.mobileservices.table.serialization.DateSerializer.deserialize(DateSerializer.java:63)
    05-06 12:15:52.965  15062-15062/app.dkh.azureprototype W/System.err﹕ at com.microsoft.windowsazure.mobileservices.table.serialization.DateSerializer.deserialize(DateSerializer.java:94)
    05-06 12:15:52.965  15062-15062/app.dkh.azureprototype W/System.err﹕ at com.microsoft.windowsazure.mobileservices.table.serialization.DateSerializer.deserialize(DateSerializer.java:47)
    05-06 12:15:52.965  15062-15062/app.dkh.azureprototype W/System.err﹕ at com.google.gson.TreeTypeAdapter.read(TreeTypeAdapter.java:58)
    05-06 12:15:52.966  15062-15062/app.dkh.azureprototype W/System.err﹕ at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:95)
    05-06 12:15:52.966  15062-15062/app.dkh.azureprototype W/System.err﹕ at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:183)
    05-06 12:15:52.966  15062-15062/app.dkh.azureprototype W/System.err﹕ at com.google.gson.Gson.fromJson(Gson.java:805)
    05-06 12:15:52.966  15062-15062/app.dkh.azureprototype W/System.err﹕ at com.google.gson.Gson.fromJson(Gson.java:870)
    05-06 12:15:52.966  15062-15062/app.dkh.azureprototype W/System.err﹕ at com.google.gson.Gson.fromJson(Gson.java:843)
    05-06 12:15:52.966  15062-15062/app.dkh.azureprototype W/System.err﹕ at com.microsoft.windowsazure.mobileservices.table.serialization.JsonEntityParser.parseResults(JsonEntityParser.java:56)
    05-06 12:15:52.966  15062-15062/app.dkh.azureprototype W/System.err﹕ at com.microsoft.windowsazure.mobileservices.table.sync.MobileServiceSyncTable.parseResults(MobileServiceSyncTable.java:351)
    05-06 12:15:52.966  15062-15062/app.dkh.azureprototype W/System.err﹕ at com.microsoft.windowsazure.mobileservices.table.sync.MobileServiceSyncTable.access$000(MobileServiceSyncTable.java:44)
    05-06 12:15:52.966  15062-15062/app.dkh.azureprototype W/System.err﹕ at com.microsoft.windowsazure.mobileservices.table.sync.MobileServiceSyncTable$3.onSuccess(MobileServiceSyncTable.java:164)
    05-06 12:15:52.966  15062-15062/app.dkh.azureprototype W/System.err﹕ at com.microsoft.windowsazure.mobileservices.table.sync.MobileServiceSyncTable$3.onSuccess(MobileServiceSyncTable.java:146)
    05-06 12:15:52.966  15062-15062/app.dkh.azureprototype W/System.err﹕ at com.google.common.util.concurrent.Futures$6.run(Futures.java:1319)
    05-06 12:15:52.966  15062-15062/app.dkh.azureprototype W/System.err﹕ at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:457)
    05-06 12:15:52.966  15062-15062/app.dkh.azureprototype W/System.err﹕ at com.google.common.util.concurrent.ExecutionList.executeListener(ExecutionList.java:156)
    05-06 12:15:52.966  15062-15062/app.dkh.azureprototype W/System.err﹕ at com.google.common.util.concurrent.ExecutionList.execute(ExecutionList.java:145)
    05-06 12:15:52.966  15062-15062/app.dkh.azureprototype W/System.err﹕ at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:185)
    05-06 12:15:52.966  15062-15062/app.dkh.azureprototype W/System.err﹕ at com.google.common.util.concurrent.SettableFuture.set(SettableFuture.java:53)
    05-06 12:15:52.966  15062-15062/app.dkh.azureprototype W/System.err﹕ at com.microsoft.windowsazure.mobileservices.table.sync.MobileServiceJsonSyncTable$4.run(MobileServiceJsonSyncTable.java:179)
    05-06 12:15:52.966  15062-15062/app.dkh.azureprototype W/System.err﹕ at java.lang.Thread.run(Thread.java:818)

**Comment by soninaren** [comment]
The implementation of  DateSerializer.deserialize(String strVal) has been changed as a part of the release Android SDK 2.0.2 release.It no longer assumes string length 28. Here is the commit with that particular change https://github.com/Azure/azure-mobile-services/commit/cb3bb2038030a8fd091d2f93953ca7c71117def2#diff-c20d32e9b204e42119e15a90a4d92fd3

**Comment by lordjesus** [comment]
Okay, thank you. Where can I find a version of the SDK with this fix in?

**Comment by soninaren** [comment]
You can find it here http://aka.ms/iajk6q or if you have this string, if you are using android studio adding this line <b>compile 'com.microsoft.azure:azure-mobile-services-android-sdk:2.0.2'</b> in build.gradle file would automatically download it for you.
