### ISSUE TITLE
unable to clear  mobile service local  pending operation  changes

### ISSUE THREAD

**Issue by shibaditi** [Azure/azure-mobile-services#695]
Hi,

  I want to clear whatever changes I am doing or want to discard the all/specific changes in mobile service offline cache. i.e. I  do not to push sync some of records to sql azure by mobile service out of my all local changes (from pending operation queue).

Any help ?

Regards
Shib

**Comment by phvannor** [comment]
duplicate issue of https://github.com/Azure/azure-mobile-services/issues/493.  

For now you can use a force purge or something in your handlers.  Long term we will add the ability to cancel specific pending operations, but design is still in progress.

**Comment by shibaditi** [comment]
Hi,

 Thanks for reply.

 Force purge is doing clearing the complete table if there is no pending operation exist on that table. if I am going to do force purge then it have to pull all data again which will take some much time , so till then user has to wait. 

it is not allowing to purge the specific records from local if there is pending operation is on queue for this table, it throws exception.

Any Idea when it is going to be release ?

Thanks Again.
