### ISSUE TITLE
is it possible to get local pending operation items

### ISSUE THREAD

**Issue by shibaditi** [Azure/azure-mobile-services#696]
Hi,

is it possible to get  the local pending operations in mobile service SQLite which are going to push to azure.
 if yes, how can I get the pending list of items from mobile service sync context , it is providing only number of pending operations, not actual items.

Thanks. 
Shib

**Comment by phvannor** [comment]
Moving to tracking on the new overall apps repo: https://github.com/Azure/azure-mobile-apps/issues/2

Closing here.
