### ISSUE TITLE
[iOS][Offline] Fields with nil value are ignored on push operations

### ISSUE THREAD

**Issue by gsach** [Azure/azure-mobile-services#699]
When a record is updated locally, and an existing value is replaced with null, this change is not pushed to the server. This causes data loss. A workaround would be to use empty strings instead of null, but this solution doesn't work well for foreign keys.

I inspected the code and found the reason why that issue happens. In the class MSCoreDataStore, the method:

-(id) getRecordForTable:(NSString *)table itemId:(NSString *)itemId asDictionary:(BOOL)asDictionary orError:(NSError **)error

is using NSDictionaryResultType on the fetch request. As a result, the null values are not added to the dictionary which is used to push the changes to the server.

**Comment by phvannor** [comment]
The NSDictionaryResultType was used to support the "selectFields" property of the MSQuery object (via propertiesToFetch).  The readTable:withItemId:orError method appears to be using it for convenience to get a NSDictionary but a simple swap to using tableItemFromManagedObject: method should work here instead.

Also we should consider making tableItemFromManagedObject into an instance method, so MSCoreDataStore could be inherited from and the logic adjusted as needed by the developer better.

**Comment by phvannor** [comment]
This I believe is fixed with Shrirangs PR, closing issue.
