### ISSUE TITLE
Mobile App (App Service) MobileServicesClient with gateway parameter

### ISSUE THREAD

**Issue by ritdaw** [Azure/azure-mobile-services#700]
Hi,

When will we be able to use the new Mobile App services via android? As per some of the samples referenced online. http://azure.microsoft.com/en-gb/documentation/articles/app-service-mobile-dotnet-backend-migrating-from-mobile-services-preview/

MobileServiceClient MobileService = new MobileServiceClient(
    "https://contoso-code.azurewebsites.net", //URL of the Mobile App Code
    "https://contosogateway.azurewebsites.net", //URL of the App Service Gateway
    "983682c4-f043-483e-a75b-8a8545fc1846"
);

**Comment by ysxu** [comment]
Our team is working on making Android development with Mobile Apps available as soon as possible. Thank you for your interest and patience.

**Comment by ysxu** [comment]
This has been released with the Mobile Apps Android SDK.
