### ISSUE TITLE
Refused to get unsafe header "Location" when registering for gcm, unable to use push from cordova app

### ISSUE THREAD

**Issue by talarari** [Azure/azure-mobile-services#711]
i added cors support for my domain in azure mobile service in the azure management portal
but there should be an option to add a response header to expose this header
Access-Control-Expose-Headers: Location

PushHttpClient has these lines:
var locationHeader = request.getResponseHeader("Location");
                    callback(null, locationHeader.slice(locationHeader.lastIndexOf("/") + 1))

the code blows up so i basically its not  possible to register for gcm successfully from a cordova app.

 mobileServiceClient.push.gcm.registerTemplate(notification.regid,
                      'myTemplate', template, null)
                    .done(function() {
                      alert('Registered template with Azure!');
                    }).fail(function(error) {
                      alert('Failed registering with Azure: ' + error);
                    });

**Comment by phvannor** [comment]
What backend are you working with here (Node.js or .NET) and what version of cordova?

**Comment by talarari** [comment]
this problem happens when registering to gcm with azure mobile services. (which is the backend)
im going to use azure mobile services for push only and trigger notifications from a c# backend but its irrelevant  to the this issue.

as you can see the registerTemplate call itself fails, not triggering a notification.

would be happy to supply more info if needed,thanks

**Comment by phvannor** [comment]
The client code shown above is talking to your mobile service and the way to configure the response headers (Access-Control-*) differs between the two types (Node vs .NET), so we do need to know the type of mobile service backend to produce a repro and look into the issue.

**Comment by talarari** [comment]
the backend is javascript.
![image](https://cloud.githubusercontent.com/assets/4973087/7737728/2b83b104-ff56-11e4-81ce-d62e62b52705.png)

**Comment by courselogic** [comment]
I haven't gotten there yet, but I'm also using js backend for an ionic app. Please share your solution on here. Thanks.

**Comment by phvannor** [comment]
In my setup (Cordova & Mobile Services only), the code in question does not trigger a CORS flow, since the mobileservices JS file is hosted on a file:// path.  When using ionic, are you not consuming the mobile services cordova plugin and instead referencing the version on the CDN?  Is this a requirement for your workflow?

**Comment by talarari** [comment]
ok, that's interesting, now that you say that i think its probably because i was running the app with livereload.
which probablly means ionic cli opens a server on machine that the app connects to, whcih will trigger the cors flow.

i'll try running it without livereload soon and see if it works. would be cool if livereload could work aswell.


thanks

**Comment by phvannor** [comment]
I agree, the backend does need to be setup to echo out a Access-Control-Allowed-Headers: Location in this flow.  The Node.js backend will return the "Access-Control-Request-Headers" by default, so a quick workaround could be to setup a client filter to add that header on the outbound requests if you need a fix asap.

**Comment by phvannor** [comment]
Or modify your local copy here:  https://github.com/Azure/azure-mobile-services-cordova/blob/master/www/MobileServices.Web.js#L3078 and have the no cache header, also include the request headers header as well.

**Comment by scottopolis** [comment]
I'm seeing this issue as well, when registering for iOS notifications while on my device. Let me know if you guys found a fix.

Thanks!

**Comment by paulbatum** [comment]
Moved to https://github.com/Azure/azure-mobile-apps-js-client/issues/57

**Comment by shrishrirang** [comment]
https://github.com/Azure/azure-mobile-apps-js-client/issues/57 tracks this issue for Mobile Apps and has been closed. More details in the issue comments. If a fix is needed for Mobile Services as well, reactivate https://github.com/Azure/azure-mobile-services/issues/711.
