### ISSUE TITLE
Elements in the OperationErrorList table cause crash when getting sync table on Android SDK 2.0.2

### ISSUE THREAD

**Issue by jonsheller** [Azure/azure-mobile-services#718]
During poor Internet connectivity, elements are inserted in the OperationErrorList table. During the next app startup when these elements are loaded, the app crashes with the exception "java.lang.NumberFormatException" because the operationkind stored in the table is stored as a stringified float, and the code that loads it expects an integer.

Example of an item stored in the table:

{"statuscode":0.0,
"errormessage":"com.microsoft.windowsazure.mobileservices.MobileServiceException: There was an error executing the request",
"id":"fe4146fc-c377-47d7-a5aa-68ae69415f9c",
"serveritem":null,
"operationkind":"1.0",
"clientitem":
{
//our application data,
"id":"18cdc0bf-b231-4bf1-83f4-bcc146a699f3"},
"serverresponse":null,
"__createdat":"2015-05-29T11:39:22.374Z",
"tablename":"ourtablename",
"operationId":"0ba47125-d39a-4ba0-9be6-ae6d4cc1a131",
"itemid":"18cdc0bf-b231-4bf1-83f4-bcc146a699f3"}

Note that the stored operationkind is 1.0

Then when loading this item during the next app startup, OperationErrorList.deserialize calls

int operationKind = element.get("operationkind").getAsInt();

But getAsInt assumes that the  value can be parsed as an integer, which it cannot because it contains a decimal point, and at this point parseInt throws the aforementioned NumberFormatException.

**Comment by jonsheller** [comment]
Note that "Application startup" is because it's during application startup that I connect to Azure Mobile Services, so that's the point that the operations are deserialized; it's not that Azure is hooking application lifecycle events by itself.

**Comment by masojus** [comment]
Has anybody had a chance to take a look at this issue? It's very severe, and is a surprisingly easy scenario to hit. During our testing in places with shoddy cell signal and/or wifi, this happens consistently. What this means is that while using the app, if one generates operations in the OperationErrorList table, the app goes into an infinite crash cycle, crashing on boot every time we load up the local store and try to sync.

The potential solutions in client code are ugly. First we can try to infer from the exception type that it's this specific issue that we're hitting, assuming we're on the right thread; if this happens on background threads, then we can install a catch-all exception filter for all threads and try to inspect the call stack to glean info about whether it's this issue or not. When we detect this issue, we tried out going through and manually fixing up the type/format of fields in the OperationErrorList table, but that didn't yield the behavior we expected, and is super hacky. Another option is to entirely delete the offline sync db file, potentially losing all the user's cached data created during a given period without connectivity. 

Again, this is a super common scenario and isn't at all difficult to hit. I'm pretty surprised unit tests around the OperationErrorList didn't hit this. We'd love to get some traction, as it makes offline sync when semi-offline pretty unusable. Thanks!

**Comment by jonsheller** [comment]
Any more information I can collect to help out with this?

**Comment by soninaren** [comment]
We have a fix for this, should be checked in very soon.

**Comment by masojus** [comment]
Thank you. Let us know if we can be of any assistance.

**Comment by soninaren** [comment]
Fixes released in Android SDK 2.0.3
