### ISSUE TITLE
Error in generated query from pull during request

### ISSUE THREAD

**Issue by icsd** [Azure/azure-mobile-services#720]
The following request is generated from the Azure Mobile Services SDK  2.0.2 for Android, during pull. The results of the response are not correct because of the OR operator. It seems that a couple parentheses is missing.

GET /tables/groups?$filter= MY_QUERY%20
and%20__updatedAt%20gt%20(datetimeoffset'2015-05-29T13:25:07.312Z')%20
and%20(id%20ne%20('2E1487FC-D905-46B1-8B2D-FFB8D758553B'))%20
and%20(id%20ne%20('2E1487FC-D905-46B1-8B2D-FFB8D758553B'))%20
or%20(__updatedAt%20ge%20(datetimeoffset'2015-05-29T13:25:07.312Z')%20
and%20id%20gt%20('2E1487FC-D905-46B1-8B2D-FFB8D758553B'))
&$top=50&$orderby=__updatedAt%20asc,id%20asc&__includeDeleted=true&__systemproperties=__updatedAt,__version,__deleted HTTP/1.1

I believe it should be like this:
I have added the extra parentheses with bold

GET /tables/groups?$filter= MY_QUERY%20
and%20  **(**  __updatedAt%20gt%20(datetimeoffset'2015-05-29T13:25:07.312Z')%20
and%20(id%20ne%20('2E1487FC-D905-46B1-8B2D-FFB8D758553B'))%20
and%20(id%20ne%20('2E1487FC-D905-46B1-8B2D-FFB8D758553B'))%20
or%20(__updatedAt%20ge%20(datetimeoffset'2015-05-29T13:25:07.312Z')%20
and%20id%20gt%20('2E1487FC-D905-46B1-8B2D-FFB8D758553B'))  **)**
&$top=50&$orderby=__updatedAt%20asc,id%20asc&__includeDeleted=true&__systemproperties=__updatedAt,__version,__deleted HTTP/1.1

**Comment by phvannor** [comment]
Query should definitely add parens where shown or else it would break a custom query.

Also, the additional Id not equal to clauses need looked into.  I believe they introduce a bug if the record with that Id has changed in between calls, and I'm not sure why they are present at first glance.

**Comment by icsd** [comment]
Definately the incremental syncing is not working properly. 
Supposing that i want to change paging. Is changing defaultTop in PullStrategy enough? 
If so, i had an issue yesterday where syncing was not working properly and i ended up with (PageSize+1) records.

A question here is why you guys on Android an iOS dont use the same mechanism for incremental syncing?

Another question is why mobile services dont use version as reference for incremental sync? 
Because:
The whole updatedAt issue which by the way is a datetimeoffset(7) in SQL which mean that operators ge and gt are almost equal and creates a bunch of issues which must be solved seperately. 
If there was an implementation for version on the mobile service the query would be as easy as 
__version  >  maxLocalVersion
I know OData is not helping you here but thats so much pain for nothing.

Thanks

**Comment by phvannor** [comment]
Changing default top will not impact paging.  There is PR in progress in managed (and followup to the others) that will introduce control of paging sizes. 

We currently use __updatedAt over __version, as the backend we are talking to is not guaranteed to be SQL (it could be table storage, mongodb, etc)  As such, we can't assume version has the properties needed to do the query you mention.  We chose to use updatedAt as it would work generically across all our standard providers.  Yes it does have some shortcomings, especially against SQL where version would be more efficient.

That said, we are also working through some designs that let us better support each data source individually, so we can avoid the types of complications you mention with updatedAt, and get the best method for each type of data source. 

Finally, getting the logic the same between managed, iOS, and Android (and eventually JS) is a top priority.   Thanks for the feedback.

**Comment by nikatlas** [comment]
@phvannor : First serious answer from microsoft.+1

**Comment by soninaren** [comment]
Fixes released in Android SDK 2.0.3
