### ISSUE TITLE
Sync failure on Android 2.0.2

### ISSUE THREAD

**Issue by GabyB** [Azure/azure-mobile-services#722]
When database column “__updatedAt” is null (Empty) and sync is using Table.pull(mPullQuery, “query").get() will not sync and first and last item is null (with exception), while using Table.pull(mPullQuery).get() works well but do full sync.

**Comment by phvannor** [comment]
The __updatedAt column being populated (non-null) is a requirement for incremental sync workflows at this time.  By default, your column should have been created with a trigger to populate its value.  How did you create your column that it is null?

**Comment by GabyB** [comment]
2 simple steps:
1. Create Mobile service table with required columns, __updateAt / __createdAt / __version / ... created automatically on table creation.
2. import data with "SQL server Import and Export" tool. It is required since some of the data already exists from other system.

I did try to override it by the following server side read script:

function read(query, user, request) {
    request.execute({
        success: function(results) {
            results.forEach(function(item) {
                if (item.__updatedAt == null) {
                    item.__updatedAt = "2015-06-01T00:00:00.000+00:00"; 
                }
            });
            request.respond(); //Writes the response
        }
    });
} 
It did not worked, I got same page sync forever...

**Comment by phvannor** [comment]
The updatedAt needs to be populated in the SQL Db for the query to function as expected, since its evaluated in your request.execute call.
