### ISSUE TITLE
[iOS] NSOperation quality of service

### ISSUE THREAD

**Issue by damienpontifex** [Azure/azure-mobile-services#725]
Add a boolean parameter to push & pull operations to indicate the origin of the request.

With this information, set the [quality of service parameter](https://developer.apple.com/library/ios/documentation/Cocoa/Reference/NSOperation_class/#//apple_ref/occ/instp/NSOperation/qualityOfService) on NSOperation (available since iOS8) to `NSOperationQualityOfServiceUserInitiated` if true for user initiated and `NSOperationQualityOfServiceBackground` if false.

With this, the system would then be able to more aptly prioritise these operations. As an example pull with user initiated may occur for loading items to display in the UI. Whereas a pull occurring from a timer of some other background instigator could occur with a much lower priority.

To avoid a breaking change, the current `-[MSSyncTable pullWithQuery:queryId:completion:]` could stay and call the designated new method like `-[MSSyncTable pullWithQuery:queryId:userInitiated:completion:]` with a user initiated of `YES` to default behaviour like the current implementation holds

**Comment by phvannor** [comment]
With #723 there is a new config option param that this would make sense to live in for Pulls.  Could offer a config bundle for Push as well to incorporate other minor tweaks like this going forward.

**Comment by phvannor** [comment]
Moved to: https://github.com/Azure/azure-mobile-apps-ios-client/issues/13
