### ISSUE TITLE
Bad request when activating User Assignment on Azure AD Premium

### ISSUE THREAD

**Issue by cradle77** [Azure/azure-mobile-services#726]
Hi,

We're using the server side flow to authenticate an iOS mobile app against Azure AD Premium.
When we activate the User Assignment feature to authorise users and groups to the app 
![screen shot 2015-06-15 at 17 32 12](https://cloud.githubusercontent.com/assets/5619949/8164982/b27faf4a-1384-11e5-8679-b5ec5f6cefed.png)

and we login using a non-authorized user, we see a **bad request** message on the login screen
![ios simulator screen shot 15 jun 2015 17 30 05](https://cloud.githubusercontent.com/assets/5619949/8165067/37d3b42a-1385-11e5-9337-6620785f18d4.png)

Instead of this behaviour, the login screen should close and I should receive the error as a NSError parameter so I could trap it and display a meaningful message to the user.

**Comment by mattchenderson** [comment]
I believe that the ADAL SDK will do this, and it works with the Mobile Services .NET runtime (https://azure.microsoft.com/en-us/documentation/articles/mobile-services-dotnet-backend-ios-adal-sso-authentication/), so you may want to go that direction.

**Comment by cradle77** [comment]
Yes, but this would require switching to the client-driven authentication flow, which poses other issues, and that's why we switched to the server-driven flow.

I reckon this should be supported by the Mobile Services SDK.

**Comment by paulbatum** [comment]
We recommend using the client flow with ADAL for this scenario.
