### ISSUE TITLE
Use json as an alternative to SQLiteStore

### ISSUE THREAD

**Issue by cmatskas** [Azure/azure-mobile-services#729]
I would like to take this on and create a different, lightweight store based on json. Something like a NoSQL store that uses a local file to store all offline data. Could you advise whether this is a good idea and if I could start work on my fork or if there are reasons that I shouldn't be considering this solution? The goal is to move away from having a dependency to SQLite dlls etc

**Comment by phvannor** [comment]
It is possible, the idea of the MobileServiceLocalStore interface was to allow this kind of flexibility.

We've had someone make a SQL CE version before (see: https://jtabadero.wordpress.com/2014/10/09/using-sqlsqlcebased-offline-stores-with-azure-mobile-services/)  

The hardest part of making one, will most likely be the querying layer.  There will be at least a subset of queries you need to support for the sync fw to work.  The rest are optional really. 

As always, peformance/security/scalability etc are a concern as well, but its always possible to document those limits.
