### ISSUE TITLE
How to get latest SDK?

### ISSUE THREAD

**Issue by lordjesus** [Azure/azure-mobile-services#735]
You should make it much more obvious how to get the latest SDK (at least for Android).

Currently, going to the frontpage of this GitHub repo and scrolling down to the **Android SDK** gives a download link to version 1.1.5 of the SDK, even though the newest version is 2.0.2 (as stated in the changelog).

You should add instructions on how to download the SDK via Gradle, since you support it.

    compile 'com.microsoft.azure:azure-mobile-services-android-sdk:2.0.2'

I think this would help a lot of new developers get started with Android and get started using the newest version with the newest features instead of the old, non-compatible version you are promoting now.

**Comment by phvannor** [comment]
@ysxu @soninaren can one of you update the readme?

**Comment by phvannor** [comment]
The README should link to the changelog, see how its set up for iOS if you have questions.
