### ISSUE TITLE
GCM Deprecated Methods

### ISSUE THREAD

**Issue by ritdaw** [Azure/azure-mobile-services#737]
register() & unregister() methods are now deprecated. Consider using new methods.

https://developers.google.com/cloud-messaging/android/legacy-regid

**Comment by soninaren** [comment]
@ritdaw  We have ongoing work to replace the deprecated methods.

**Comment by ysxu** [comment]
@ritdaw We have updated our new SDK to delete these deprecated methods for currently supported ones at https://github.com/Azure/azure-mobile-apps-android-client.
