### ISSUE TITLE
Facebook login and access_denied

### ISSUE THREAD

**Issue by jakiiskinen** [Azure/azure-mobile-services#738]
There is an issue with Facebook login on Windows Phone 8.1. When the user selects Cancel on the app permission page, all subsequent login attempts fail.

The issue can be reproduced as follows:
1) Call MobileServiceClient.LoginAsync(MobileServiceAuthenticationProvider.Facebook)
2) In Facebook login page, enter credentials, and on next page, when Facebook asks the user to authorize the application, select Cancel
3) When the control returns to the application, in OnActivated method the ResponseData in  WebAuthenticationBrokerContinuationEventArgs argument does not contain a token string. The response is something like this: https://abc.azure-mobile.net/login/done#error=Error%3A%20access_denied%3A%20Permissions%20error

AuthenticationBroker.GetTokenStringFromResult called by MobileServiceClient.LoginComplete method then throws an InvalidOperationException. AuthenticationBroker.AuthenticationComplete leaves pendingLoginTask static member in Pending state, and all subsequent calls to LoginAsync will result in an error "Authentication is already in progress."

We have fixed this for our own purposes by changing the AuthenticationBroker.AuthenticationComplete as described below. Feel free to use this change if it seems OK.

```
public void AuthenticationComplete(WebAuthenticationResult result)
{
	if (pendingLoginTask == null)
	{
		throw new InvalidOperationException("Authentication has not been started.");
	}

	if (result.ResponseStatus != WebAuthenticationStatus.Success)
	{
		string message;
		if (result.ResponseStatus == WebAuthenticationStatus.UserCancel)
		{
			message = "Authentication was cancelled by the user.";
		}
		else
		{
			message = string.Format(CultureInfo.InvariantCulture,
									"Authentication failed with HTTP response code {0}.",
									result.ResponseErrorDetail);
		}
		pendingLoginTask.SetException(new InvalidOperationException(message));                
	}
	else
	{
		string tokenString;
		try
		{
			tokenString = GetTokenStringFromResult(result);
		}
		catch (InvalidOperationException)
		{
			//If the user selects Cancel in Facebook permission request dialog, token stríng is not present in the response
			pendingLoginTask = null;
			return;
		}
		pendingLoginTask.SetResult(tokenString);
	}
	pendingLoginTask = null;            
}
```

**Comment by ysazak** [comment]
This issue exists for javascript mobile service library as well. is there any workaround to fix it?

**Comment by paulbatum** [comment]
We will look at addressing this in the latest versions of our SDKs. I ported these bugs to both our new .net client repo and our JS client repo.
