### ISSUE TITLE
Javascript backend: Client login (Google) in IE can trigger small fixed popup 

### ISSUE THREAD

**Issue by jeroencusters** [Azure/azure-mobile-services#740]
Hi,

We have an issue with the Google OAuth popup when we trigger client.login('google') in Internet Explorer. The popup is fixed (no resizing possible) and there are no scrollbars. This happens if the original screen is small and when the original screen is maximized and the new screen is small (last known size). See below screenshot:

Google consent screen (not possible to accept):
![image](https://cloud.githubusercontent.com/assets/2187598/8549522/780e0106-24cb-11e5-86f3-626aa6d6b058.png)

This also is an issue when a user has to create a new account in this small popup. In Chrome it's possible to resize the popup, maximize screen and Chrome add scrollbars. In IE all these are not available. We use MobileServices.Web-1.2.7.min.js client library.

Regards,
Jeroen

**Comment by adrianhall** [comment]
Transitioned to azure-mobile-apps-js-client#2

**Comment by jeroencusters** [comment]
@adrianhall Is azure-mobile-apps-js-client a private repository? I can't find it on github.

**Comment by adrianhall** [comment]
@jeroencusters Right now, we are splitting up the azure-mobile-services into SDK specific repositories for easier handling.  The repositories will appear with the same membership as before once we get the builds working.
