### ISSUE TITLE
Using mobile service client SDK to access API App

### ISSUE THREAD

**Issue by damienpontifex** [Azure/azure-mobile-services#746]
With the new app service model, it seems mobile services is just another layer on top of Api Apps. Is this assumption correct?

If so, why does the new mobile app template include all the Owin security packages if the gateway will handle security in this setup? 

Also if we create plain ApiControllers that return data instances of ITableData and setup our routes to be /table/{controller} rather than the usual api route will the mobile services client SDK continue to work as expected? 

All this is just in an attempt to simplify my services if I have a couple of them running in Azure in the new AppService model.

**Comment by WiteCastle** [comment]
I'm working on moving my web and mobile service to the new app service model but there isn't a lot of documentation on migrating your existing mobile service. The documentation only shows how to create a new mobile service and add a web app to it. I think looking through the most up to date starter project you can download from your azure portal will probably help with the migration though. I wish there were better documentation/migration guides though.

**Comment by damienpontifex** [comment]
There is a [migration article](https://azure.microsoft.com/en-us/documentation/articles/app-service-mobile-dotnet-backend-migrating-from-mobile-services-preview/).

My question was more regarding using plain Api Apps if I don't need the application keys and push notifications, while still being able to utilise the mobile services client SDK in this repo.

**Comment by phvannor** [comment]
Did you see this http://azure.microsoft.com/blog/2015/07/17/updates-to-the-mobile-apps-server-sdk/

Standing up your own table endpoints is doable, a min client just requires an "id" column exposed and you to map that to your actual data model id column. 

If not using the table controller structure, you will lose some helper logic that we apply automatically, so the more complicated SDK logic used in Offline/Sync would probably not just work.  In theory it would be possible though for an API Controller to implement the required mechanics / translations.

**Comment by damienpontifex** [comment]
Yes I did see the update and looks like a good move towards more customisation. This is roughly what I was looking for, although I'm having some issues migrating my existing project to the new configuration/setup. Will continue to debug.
