### ISSUE TITLE
try/catch or rethrow needed in background thread (andoird sdk)

### ISSUE THREAD

**Issue by rothschild86** [Azure/azure-mobile-services#751]
This file https://github.com/Azure/azure-mobile-services/blob/master/sdk/android/src/sdk/src/main/java/com/microsoft/windowsazure/mobileservices/table/MobileServiceTableBase.java

Line 365 should be wrapped:

                    try{
                    	serverEntity = new JsonParser().parse(content).getAsJsonObject();
                    }
                    catch(JsonSyntaxException | IllegalStateException e){
                    	e.printStackTrace();
                    }

If not wrapped and exception is thrown, it never bubbles up to the top. In fact, onCompleted(Throwable throwable) is never even called on table operations.

**Comment by soninaren** [comment]
Fixed in #761

**Comment by soninaren** [comment]
@rothschild86 This is fixed in the referenced Pull Request, will be released with the next android SDK release
