### ISSUE TITLE
[iOS] NS_ASSUME_NONNULL_BEGIN

### ISSUE THREAD

**Issue by damienpontifex** [Azure/azure-mobile-services#757]
@phvannor previously I had made a PR adding nullability attributes, but there are macros for `NS_ASSUME_NONNULL_BEGIN` and `NS_ASSUME_NONNULL_END`.

All the nonnull annotations could be removed with these and would make it slightly cleaner and less to do for new code. Downside being if the author doesn't think about nullability, it will assume non-null which may be in error.

Thoughts on converting to the macros? Or continue to use explicit nonnull and nullable annotations?

**Comment by phvannor** [comment]
I believe Apple's doc officially recommends using them, so I see no reason not to.  Probably just something to do as files are touched.  Not worth changing on its own most likely.

**Comment by damienpontifex** [comment]
Agreed, will keep in mind with any future changes
