### ISSUE TITLE
Unhandled exception with Samsung Galaxy devices

### ISSUE THREAD

**Issue by rainergp** [Azure/azure-mobile-services#758]
In Xamarin Studio I'm getting this exception, it only happen with the Samsung Galaxy (S4, S5, S6) devices and when I link assemblies in the "Linker Options", if I "don't link" the problem disappear, on iOS it works perfect:

    [MonoDroid] UNHANDLED EXCEPTION:
    [MonoDroid] System.TypeInitializationException: An exception was thrown by the type initializer for Whisel.Mobile.App ---> System.InvalidOperationException: A Microsoft Azure Mobile Services assembly for the current platform was not found. Ensure that the current project references both Microsoft.WindowsAzure.Mobile and the following platform-specific assembly: Microsoft.WindowsAzure.Mobile.Ext.
    [MonoDroid]   at Microsoft.WindowsAzure.MobileServices.Platform.ThrowForMissingPlatformAssembly () [0x00047] in <filename unknown>:0 
    [MonoDroid]   at Microsoft.WindowsAzure.MobileServices.Platform.get_Instance () [0x00066] in <filename unknown>:0 
    [MonoDroid]   at Microsoft.WindowsAzure.MobileServices.MobileServiceClient.GetApplicationInstallationId () [0x00004] in <filename unknown>:0 
    [MonoDroid]   at Microsoft.WindowsAzure.MobileServices.MobileServiceClient..ctor (System.Uri applicationUri, System.String applicationKey, System.Net.Http.HttpMessageHandler[] handlers) [0x00028] in <filename unknown>:0 
    [MonoDroid]   at Microsoft.WindowsAzure.MobileServices.MobileServiceClient..ctor (System.Uri applicationUri, System.String applicationKey) [0x00000] in <filename unknown>:0 

I'm using WindowsAzure.MobileServices 1.3.2 from NuGet. Any idea what cause this problem?

**Comment by paulbatum** [comment]
Resolved by the fix for #855.

**Comment by rainergp** [comment]
Good to hear that. Thanks
