### ISSUE TITLE
No tags in push register call [C#]

### ISSUE THREAD

**Issue by bradley-dotnet** [Azure/azure-mobile-services#762]
The provided documentation shows the ability to send notifications to a specific user with the "_UserId" tag, but doesn't show how to register for general tags.

Previously I would just use:

`await client.GetPush().RegisterNativeAsync(uri, new string[] { "myTag" });`

To register, but I can't find a similar method in the current SDK. Please put this overload, or similar, back in.

**Comment by phvannor** [comment]
The plan is to allow the tag be part of the template that you pass in as the second parameter, following the same pattern as using the NH client SDK directly.  There are still some server hooks needed to allow verification of tags/etc as well on our server side yet.

As a workaround for now, you would need to either use the NH SDK directly or set up a custom API to send the tags and register them.

**Comment by chosl** [comment]
I have the same problem. Any update on this in the november update? How would the template be formed? Keep up the great work!

**Comment by phvannor** [comment]
Adding:
https://github.com/Azure/azure-mobile-apps-net-server/issues/36
https://github.com/Azure/azure-mobile-apps-node/issues/241

To track this on the server level.

Client side, we'd initially probably just pass them up via the template top level property, "tags".  For details on the template see: https://msdn.microsoft.com/en-us/library/azure/mt621153.aspx

Long term we need to add a nicer API for working with templates to all the clients as well.

**Comment by phvannor** [comment]
iOS: https://github.com/Azure/azure-mobile-apps-ios-client/issues/9
.Net: https://github.com/Azure/azure-mobile-apps-net-client/issues/12
JS: https://github.com/Azure/azure-mobile-apps-js-client/issues/22
Android: <pending seperate repo>

**Comment by phvannor** [comment]
closing base services issue, as now tracked in the new apps repos.

**Comment by danderson00** [comment]
Maybe this issue should be left open for discussion, rather than fragment the conversation. There is clearly some design work that needs to be done here, and the result should be consistent across platforms.

**Comment by phvannor** [comment]
It's mainly getting to parity with v1, but we can open a new issue on -apps if we think more design is needed as well.

Ignore the client issues, they are only tangentially related to this, those are placeholders for really a different discussion than tags support.
