### ISSUE TITLE
Cancel push pull requests while syncing

### ISSUE THREAD

**Issue by icsd** [Azure/azure-mobile-services#763]
Let's assume that i have started syncing, and i want to stop it. How can i cancel it?
I cancel the async task that contains the push and pull operations and then kill the activity, but i see from fiddler that the requests continue running.

Thank you in advance

**Comment by phvannor** [comment]
Cancellation can be done by passing in a cancellation token when you call the push or pull method.  Then calling cancel on that token source.  

Here's one of our unit tests for cancel as an example: https://github.com/Azure/azure-mobile-services/blob/master/sdk/Managed/test/Microsoft.WindowsAzure.MobileServices.Test/UnitTests/Table/Sync/MobileServiceSyncTable.Generic.Test.cs#L74-L97

If that is what you are doing & its not working, can you provide the details of which method you are calling (Push or Pull), what latform (Windows, WP8, Xamarin.iOS, etc), and the version of the SDK you have installed?

**Comment by fabiocav** [comment]
@icsd we haven't heard back, so I'm assuming that based on the information provided above, this is working as expected. Please feel free to open an issue with the additional details requested above if you're experiencing problems.
