### ISSUE TITLE
Memory Leak with Swift

### ISSUE THREAD

**Issue by egrimmius** [Azure/azure-mobile-services#768]
I'm getting a memory leak after calling readWithCompletion: in MSQuery.  I'm using swift.  After my own function, here's the stack trace from the Leak Instrument:         

   4 MyAppName +[MSClientConnection invokeNextFilter:withClient:withRequest:completion:] /Users/Shared/Jenkins/workspace/ZumoSDKBuild_Dev_iOS/sdk/iOS/src/MSClientConnection.m:179
   5 MyAppName -[MSClientConnection start] /Users/Shared/Jenkins/workspace/ZumoSDKBuild_Dev_iOS/sdk/iOS/src/MSClientConnection.m:86
   6 MyAppName -[MSTable readWithQueryStringInternal:features:completion:] /Users/Shared/Jenkins/workspace/ZumoSDKBuild_Dev_iOS/sdk/iOS/src/MSTable.m:222
   7 MyAppName -[MSQuery readInternalWithFeatures:completion:] /Users/Shared/Jenkins/workspace/ZumoSDKBuild_Dev_iOS/sdk/iOS/src/MSQuery.m:113

And here's my code:

        // Query Azure
        if let azure = client {
            
            let syncQueue = NSOperationQueue()
            azure.connectionDelegateQueue = syncQueue
            
            let store = EJGDataStore.sharedStore
            let predicate = NSPredicate(format: "lastModifiedDate > %@", argumentArray: [lastSyncedDate])
            let azureQuery = azure.tableWithName("tblSire").query()
            azureQuery.includeTotalCount = true
            azureQuery.fetchLimit = 1000
            if full == false {
                azureQuery.predicate = predicate // won't limit for full Sync
            }
            azureQuery.selectFields = ["id", "sireName", "sireCode"]
            
            azureQuery.readWithCompletion({
                [unowned self, unowned store]
                (result: MSQueryResult?, error: NSError?) -> Void in
                
                // Send results to the main queue
                dispatch_async(dispatch_get_main_queue(), {
                    // Error?
                    if let e = error {
                        // Log details of the failure
                        println("Azure Error: \(e) \(e.userInfo!)")
                        //self.countOfConnectionErrorsInSyncProcess++
                    }
                    // Success?
                    if let r = result {
                        println("Sire Count: \(r.totalCount)")
                    }
                    
                    if let r = result, items = r.items {
                        store.updatePulledSires(azureObjects: items, includesAll: full)
                    }
                    
                    // Progress..
                    //self.progressSync(newSyncedDate, isFull: full)
                })
            })
        }

What might I have missed?

**Comment by phvannor** [comment]
Thanks, let me run some tests and see if I can repro.  Do you know what what version you are using?

**Comment by egrimmius** [comment]
I'm using 2.2.  Also, I tried to see if I had the same problem trying it in objective-c, and I had the same leak show up there as well.  Thank you.

**Comment by phvannor** [comment]
Ok, I think it was related to the switch to NSURLSession in the 2.0 release, and prelim testing indicates we missed a call to finishAndInvalidateTasks call after starting the task.  In my simple repro, that seems to have addressed it, just running some more verification.

**Comment by egrimmius** [comment]
That would be great, thanks for looking into this.

**Comment by phvannor** [comment]
Fixed, and generally available via the 2.2.1 framework
