### ISSUE TITLE
Internal npe in  ServiceFilterResponse/ServiceFilterRequestImpl

### ISSUE THREAD

**Issue by rothschild86** [Azure/azure-mobile-services#774]
Keep bumping into this npe in getStatus:

There was an error executing the request Attempt to invoke interface method 'org.apache.http.StatusLine com.microsoft.windowsazure.mobileservices.http.ServiceFilterResponse.getStatus()' on a null object reference [com.microsoft.windowsazure.mobileservices.http.RequestAsyncTask.doInBackground(RequestAsyncTask.java:87), com.microsoft.windowsazure.mobileservices.http.RequestAsyncTask.doInBackground(RequestAsyncTask.java:1), android.os.AsyncTask$2.call(AsyncTask.java:288), java.util.concurrent.FutureTask.run(FutureTask.java:237), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587), java.lang.Thread.run(Thread.java:811)]

**Comment by rothschild86** [comment]
this also happens in the getUrl method:

08-21 20:03:41.523: W/System.err(30930): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.net.URI.toString()' on a null object reference
08-21 20:03:41.533: W/System.err(30930): 	at com.microsoft.windowsazure.mobileservices.http.ServiceFilterRequestImpl.getUrl(ServiceFilterRequestImpl.java:139)

**Comment by soninaren** [comment]
Could you provide us with some more information to help us reproduce this issue?

1) If you could share with code snippet or the scenario where you are running into this issue.
2) Could you capture the server request and response for which you are getting the Null pointer Exception. This tutorial below could be helpful in intercepting server responses via fiddler. 
http://blogs.msdn.com/b/visualstudioalm/archive/2015/05/06/using-fiddler-to-monitor-network-traffic-from-the-vs-emulator-for-android.aspx

Some common scenarios where you would run into Null Pointer Exception would be incorrectly casting the MobileServiceException in the onFailure Method. 
Here are some sample code snippets that might help.

```
public void onSuccess(ServiceFilterResponse response) {
                if (response != null) {
                    int responseCode = response.getStatus().getStatusCode();
                }
                resultFuture.set(response);
            }

@Override
public void onFailure(Throwable exception) {

                if (MobileServiceException.class.isInstance(exception)) {
                    MobileServiceException mEx = (MobileServiceException) exception;
                    int responseCode = mEx.getResponse().getStatus().getStatusCode();

                }
                resultFuture.setException(exception);
            }
```

**Comment by rothschild86** [comment]
getUrl() npe:

I did not directly reproduce this, but I see it my my crashlytics logs: http://crashes.to/s/cf27f8b5503

It's coming from my custom filter (EnvironmentRequestFilter). All I do in it is do getUrl() and append a couple of params to the url that go out to the endpoint. It's rare, but somehow url is null sometimes.

It's not a frequent bug, but something to keep an eye on.


getStatus() npe:

Can't find the trace for that one, but yes, that's exactly the snipet i'm using for casting.... Again, this one also seems to be rare.

Thank you for a thorough response!
