### ISSUE TITLE
[iOS] Relationship properties exposed in sync process

### ISSUE THREAD

**Issue by phvannor** [Azure/azure-mobile-services#779]
The coredata store is not supposed to currently expose the relationships on the tables.  Currently when using ReadWithId it does, which leads to an NSSet being present on the item, and the push process failing since those can't be converted to an NSDIctionary.

Issue appears to have been introduced by the fix for #733 to ensure null values where going up to the server.

Fix should be adding a call here:
https://github.com/Azure/azure-mobile-services/blob/master/sdk/iOS/src/MSCoreDataStore.m#L68

To use tableItemFromManagedObject: which will cause only the properties of the managed object to be exposed.  Long term, allowing a block / delegate to handle the conversion (so relationships could become an array of objects, etc) is ideal.

**Comment by charleyxiv** [comment]
Any news on this issue? I would like to be able to push entitites along with their relationships all at once.

**Comment by phvannor** [comment]
This is fixed with https://github.com/Azure/azure-mobile-services/commit/df672ddeb2d362938328fcec795c6a7b0f25b125

**Comment by frankzwang** [comment]
Great work, thanks pal!
