### ISSUE TITLE
Block functions do not seem to work with iOS 6

### ISSUE THREAD

**Issue by funnel20** [Azure/azure-mobile-services#780]
I'm using SDK version 2.2.0 and 2.2.1, but on iOS 6 for example method 'invokeAPI' doesn't do anything.
While for iOS 7 and 8 it works fine.

What is the minimum iOS version for SDK 2.2.x?

On https://github.com/Azure/azure-mobile-services/blob/master/CHANGELOG.ios.md is mentioned at 1.1.2: "Now requires iOS 6 or newer to use"

At higher versions, iOS minimum target is never mentioned.

**Comment by phvannor** [comment]
Yes, 2.0 should have called out it requires iOS 7.0, as we took a dependency on NSURLSession, which doesn't exist in iOS 6.

**Comment by phvannor** [comment]
Updated changelog to indicate dependency.
