### ISSUE TITLE
android 6: SecurityException on parsing results (issue in how gson is used - GsonConverter needed)

### ISSUE THREAD

**Issue by rothschild86** [Azure/azure-mobile-services#784]
at com.microsoft.windowsazure.mobileservices.table.serialization.JsonEntityParser.parseResults(JsonEntityParser.java:56)

See this discussion - https://github.com/google/gson/issues/648

This error will happen if a class that is being used for serialization extends some other base class (an ORM Entity, such as https://github.com/pardom/ActiveAndroid, for example).

Essentially, adding gsonBuilder.excludeFieldsWithModifiers(Modifier.FINAL, Modifier.TRANSIENT, Modifier.STATIC); in MobileServiceClient.createMobileServiceGsonBuilder() fixes the problem.

Perhaps, extend framework so that a developer can supply their own GsonBuilder?

**Comment by ysxu** [comment]
Moving over to Mobile Apps repo as there is a workaround. https://github.com/Azure/azure-mobile-apps-android-client/issues/10
