### ISSUE TITLE
i can't use this in my cocoa pod correctly

### ISSUE THREAD

**Issue by sandkee** [Azure/azure-mobile-services#786]
I want to call the azure's APIs in my cocoa pod. Unfortunately, I can't call the APIs correctly because the POD is pulling in the wrong version.

**Comment by phvannor** [comment]
At this time we don't currently have a cocoa pod for this project that we maintain.  To unblock yourself, you could make your own podspec file or you can grab our compiled framework file and put that into your project directly instead for now.

We'll look at creating/maintaining a proper pod as well.

**Comment by intellitour** [comment]
Willing to get back Cocoapods support back!

**Comment by mohamedmansour** [comment]
Can we add Cocoapods :) It is super easy to maintain, would make developing Mobile Service iOS apps easier for a pod project

**Comment by sandkee** [comment]
I fixed it by making a copy. I have heard that zumo is going to fix this soon.

**Comment by damienpontifex** [comment]
@mohamedmansour I believe the iOS library has been moved into its own repo and is at [Azure/azure-mobile-apps-ios-client](https://github.com/Azure/azure-mobile-apps-ios-client) and looking in that repo, there is now a podspec. I haven't tried it personally, but I was involved in this cocoa pods integration in the past.

**Comment by mohamedmansour** [comment]
Sweet will try it in a bit, didn't look at it.

**Comment by phvannor** [comment]
Yes I have put together a podspec in the new repo for Mobile Apps, I'm still looking at automated testing using it so we are sure its in good shape (and stays that way)  Once complete I will add it officially to CocoaPods.

**Comment by mohamedmansour** [comment]
Awesome thanks @phvannor

**Comment by phvannor** [comment]
Moved tracking to: https://github.com/Azure/azure-mobile-apps-ios-client/issues/12

We will probably not be adding a cocoa pod for the services (master) branch. Apps (MobileApp) branch is now moved to -ios-client and support added there (in progress now)
