### ISSUE TITLE
WinJS - azure mobile app 

### ISSUE THREAD

**Issue by iangithub** [Azure/azure-mobile-services#787]
MobileServices.min.js (2.0 beta) & MobileServices.min.js(1.2.5) support azure mobile app ( not mobile service )  ?

I tried use connect facebook auth , but have error , can't show login page .

If use azure mobile service , the  MobileServices.min.js(1.2.5)  is work .  MobileServices.min.js(2.0 beta) not work fine , the error is " Unexpected error " .

**Comment by phvannor** [comment]
For WinJS / Native, the 1.* is for services, the 2 - betas are for mobile apps.  For WinJS you should be using the nupkg (http://www.nuget.org/packages/WindowsAzure.MobileServices.WinJS/1.2.5) not the native JS version on the CDN.

**Comment by iangithub** [comment]
Yes, I tried use 2-* beta from nupkg , but it not work , always throw exception  " Unexpected error " .

My project : 

1) use visutal studio 2015 javascript uwp blank project template 
2) winjs 4.0 
3) use nuget install MobileServices.min.js 2-* 

not work fine for azure mobile app .

if use MobileServices.min.js 1.2.5 , that work for azure mobile service .

**Comment by adrianhall** [comment]
Transitioning to azure-mobile-apps-js-client.
