### ISSUE TITLE
Android-- update and then soft delete

### ISSUE THREAD

**Issue by rajeesh7** [Azure/azure-mobile-services#788]
In offline mode from mobile updated an item and then  made a soft delete.
Then in online mode made a incremental sync operation. 
The  corresponding changes in server side is- the deleted flag is set to one. but all other mobile updated changes are not reflected.

For example in offline mode i changed an element value from a to b. then soft deleted. then came online and made an incremental sync. The corresponding item change in the server is the deleted flag set to 1 but the item value is still a and not b.

**Comment by phvannor** [comment]
This is currently by design, a offline delete will replace a pending update.  Similarly, an offline Insert + Delete will result in no action being played to the server.

Can you outline your use case and why you would like to have the update done as well?

**Comment by rajeesh7** [comment]
i think you are wrong. 
An offline insert + delete and then online sync will upload the item with the flag deleted = 1 in server.

My use case is 
I want to answer a form of data and on filling all the questionnaire i want to mark it as completed and then to be deleted from my mobile db.
On completing the record i just marked it as completed and then made a soft delete. Now i want both complete and deleted flags to be updated in server.
But in server it is taking only the id and is marked as deleted by ignoring all the other questionnaire changes.

**Comment by phvannor** [comment]
If that's the case, it's a bug in the Android SDK.  The design called for that to be cancelled.

Looking at Android's source, it would appear the Insert/Update preceding the delete is removed from the queue:

The two collapsers for insert & update both return null or the new operation back out:
https://github.com/Azure/azure-mobile-services/blob/master/sdk/android/src/sdk/src/main/java/com/microsoft/windowsazure/mobileservices/table/sync/queue/OperationQueue.java#L220

https://github.com/Azure/azure-mobile-services/blob/master/sdk/android/src/sdk/src/main/java/com/microsoft/windowsazure/mobileservices/table/sync/queue/OperationQueue.java#L220

This causes the queue to remove the existing op and replace it with the new Delete operation only as shown here:
https://github.com/Azure/azure-mobile-services/blob/master/sdk/android/src/sdk/src/main/java/com/microsoft/windowsazure/mobileservices/table/sync/queue/OperationQueue.java#L220

For now, the cleanest way to do what you want, is to have your update script delete the item when it sees its been marked completed.  Then you could either let the next Pull() delete the record locally, or have update return a 404 and use a handler to clean it up asap.

We can also review the decision on how we collapse in regards to delete actions and see if long term we will change this to keep prev actions.

**Comment by rajeesh7** [comment]
I changed the code  to make a pull first and after successfully completing this syncing i made the delete call.
