### ISSUE TITLE
Xcode 7 Project WindowsAzureMobileServices.framework bitcode enabled

### ISSUE THREAD

**Issue by tahneesmith** [Azure/azure-mobile-services#794]
I am trying to update my iOS app to make it compatible with Xcode 7/iOS 9 and I get this build error:

WindowsAzureMobileServices.framework/WindowsAzureMobileServices(MSDateOffset.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

The WindowsAzureMobileServices framework needs to be rebuilt with bitcode enabled in the build settings. 

This is extremely urgent...please update your iOS framework as soon as possible.

**Comment by phvannor** [comment]
We will take a look at getting a build & release done. In the meantime, you can clone this repo and should be able to run bash build.command and get a framework generated for you.  (After making the necessary edit to the proj)

**Comment by tahneesmith** [comment]
Thanks!
