### ISSUE TITLE
SBNotificationHub unknown on Xcode 7 / IOS 9

### ISSUE THREAD

**Issue by nickplennox** [Azure/azure-mobile-services#803]
I'm trying to use Azure Notification Hub in my IOS project. I've done this successfully in the past on other projects but this time I am having a problem.

I added version 2.2.30921 of the framework to my IOS 9 project and following the tutorial I have hit a problem.

The tutorial suggests using registerNativeWithDeviceToken in the app delegate callback didRegisterForRemoteNotificationsWithDeviceToken; however, I'm getting a build error saying that SBNotificationHub is an unknown type (and  Xcode is unhelpfully making an incorrect recommendation that I replace with SBNotificationHub with NSNotification). 

Hopefully the attached screenshot is self explanatory.

![untitled](https://cloud.githubusercontent.com/assets/2352526/10019184/c9c869ec-6133-11e5-964d-c88cea71a8b0.png)

Is there a regression in build 30921? Does the tutorial need an update? Or is it my bad.

Nick

**Comment by nickplennox** [comment]
My bad - following an old tutorial. Looks like the supported way to do this is using the MSClient object to connect to an Azure Mobile Service??

**Comment by phvannor** [comment]
NH logic is built into mobile services, the SBNotificationHub, etc classes are part of this repo: https://github.com/Azure/azure-notificationhubs, if you want to create your issue over there.

**Comment by nickplennox** [comment]
Thanks very much for the redirect. Looks like my options are to use Mobile Services against an Azure Mobile app, or if I just want notifications and none of the other app goodness, use the other repo you've redirected me to.

Much obliged!

Nick
