### ISSUE TITLE
IOS Core Data relationships support

### ISSUE THREAD

**Issue by meoz** [Azure/azure-mobile-services#810]
Some time ago, you said there were no plans to support relationships on the client. Is there already been any change in plans ? I'd like to use Azure mobile services but not supporting relationships between tables limits very much the use of any advanced DB model.

**Comment by charleyxiv** [comment]
I am having the same concerns. Looking forward to see what are your solutions for this.

**Comment by phvannor** [comment]
Relationship support is planned, and is an ongoing work item, with the main blocker at the moment being getting support on the server to accept batched changes.  (so we can send the parents, children, etc in one server transaction without violating those constraints)

Depending on what relationships you need, there are ways we can get support for them now. Mainly if you only need to deal with 1:1 or 1:N relationships.

Technically nothing (is supposed) to stop them from being used on the client side if your server data model can deal with each table being synced by itself.  We have a bug atm that really needs fixed that is breaking the push action here.

If you let me  know what relationship types you are dealing with and main needs, I can see if there are some short term workarounds that may work for you.  (This would probably involving having a custom MSCoreDataStore to hide those from our SDK atm)

**Comment by attiqeurrehman** [comment]
I also need to resolve 1:1 and 1:N relationship. 

Thanks.

**Comment by phvannor** [comment]
1:1 relationships are easiest to handle by having the Client <-> Server treat it as one object.  Then in your table scripts on the server you actually separate it back out.  

For 1:N, again the simplest is if you can get away with having them as one entity on the client.  

Given you want to work with the model on the client the next question is, can your server handle inconsistent states or not (i.e is Parent allowed to point to a missing child, etc)  If so, you can just run things as they are.

In the more likely event that is not acceptable, the next step would involve customizing the action taken on push (via the delegate's per operation method) and/or making a custom MSCoreDataStore, whose upsert & read methods can separate & combine the item when dealing with the parent object.

It's a little hard to fully explain here, I'll see I can get a couple hours to whip up a simple prototype.  

What backend language are you working in (Node.js or Managed)?

**Comment by attiqeurrehman** [comment]
I am using Node.js, I am not worried about backend because this article
<http://blogs.msdn.com/b/carlosfigueira/archive/2013/08/23/complex-types-and-azure-mobile-services.aspx>
explains it very nicely. I need help/sample for iOS.

On Sat, Oct 3, 2015 at 3:29 AM, Phillip Van Nortwick <
notifications@github.com> wrote:

> 1:1 relationships are easiest to handle by having the Client <-> Server
> treat it as one object. Then in your table scripts on the server you
> actually separate it back out.
>
> For 1:N, again the simplest is if you can get away with having them as one
> entity on the client.
>
> Given you want to work with the model on the client the next question is,
> can your server handle inconsistent states or not (i.e is Parent allowed to
> point to a missing child, etc) If so, you can just run things as they are.
>
> In the more likely event that is not acceptable, the next step would
> involve customizing the action taken on push (via the delegate's per
> operation method) and/or making a custom MSCoreDataStore, whose upsert &
> read methods can separate & combine the item when dealing with the parent
> object.
>
> It's a little hard to fully explain here, I'll see I can get a couple
> hours to whip up a simple prototype.
>
> What backend language are you working in (Node.js or Managed)?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Azure/azure-mobile-services/issues/810#issuecomment-145170339>
> .
>



-- 
Attiqe Ur Rehman

**Comment by attiqeurrehman** [comment]
@phvannor any sample prototype ?

-A

**Comment by phvannor** [comment]
tracking now at: https://github.com/Azure/azure-mobile-apps-ios-client/issues/30

**Comment by phvannor** [comment]
@attiqeurrehman i Never got a chance to really work on any prototype yet.  I did put together half of what will be needed here: https://github.com/phvannor/azure-mobile-apps-ios-client/commit/9065be3c4e45b9c586871f5022305f35b0347d8b

Once in, that will allow an easy solution to the pull half (assuming your dont have cycles / can live ok w/portions of records) but leaves the push half left undone.

Closing this issue, as the ios-client will be the main repo going forward for this.

**Comment by kNeerajPro** [comment]
Even the simplest of backends need core data relationships. Can you please tell me how can I make this work? One solution I see is that I create independent tables with foreign key/primary keys concept and then do the same in Core Data. OfCourse it breaks the essence of Core Data but is it ok to go forward with that solution?

Please update me on this.
Thanks
