### ISSUE TITLE
Synchronization Error Handling in Client side

### ISSUE THREAD

**Issue by icsd** [Azure/azure-mobile-services#811]
In case that an error* occurs in synchronization, then this error will be reproduced in every
synchronization. How can the client handle this?

*For example: The mobile client adds a record in a table and then synchronizes. Suddenly during the POST request, internet cuts off and the client never gets the response from the server for 
that record, so this record stays in the __Operations table. In this case, everytime the client 
synchronizes, tries to push this record to the server and gets an error for Duplicate Primary ID because
this record already exists.
Should the client clear the __Operations table or what?

Thank you in advance

**Comment by phvannor** [comment]
Errors that occur during the push process do need to be handled, if the error was transient we abort the push process but do not return the error from push.

There are 3 main places to do this work,
- In your sync context's datasource / handler's on table operation: This puts your code around the actual server call and you can handle responses/etc in real time using a regular MSTable or your own http stack as desired until the error is resolved.  If you don't throw an error here, the FW considers it a success and removes it from the queue.

- In your synccontext's/datasources pushComplete: This gives you are array of MSTableOperationErrors, that you can loop through.  The error object has some baked in methods (cancelAndUpdateItem, cancelAndDiscardItem) that you can call to manipulate the stored item & cancel the action.

- After calling Push, the same array is given to the code, and can follow the pattern used above.

We recently added a new method to let you also update the queued action's type in managed, and that will come along to the other SDKs shortly which will make handling additional cases easier.


@lindydonna can you add a link to a conflict tutorial that would show the above in practice?

**Comment by lindydonna** [comment]
Here are tutorials that show how to do #1 that phvannor mentioned:

Managed client (Windows & Xamarin)
https://azure.microsoft.com/en-us/documentation/articles/mobile-services-windows-store-dotnet-handling-conflicts-offline-data/

iOS client
https://azure.microsoft.com/en-us/documentation/articles/mobile-services-ios-handling-conflicts-offline-data/

For a summary of how the offline sync feature works in general, see https://azure.microsoft.com/en-us/documentation/articles/app-service-mobile-offline-data-sync-preview/ The topic talks about the new version of our product (Mobile Apps on App Service) but all of the material applies to Mobile Services as well.

For an example of how to do option #3 (errors after calling PushAsync), see this C# managed client (Windows/Xamarin) example here: https://github.com/Azure/azure-mobile-services-quickstarts/blob/master/client/xamarin.forms/ZUMOAPPNAME/TodoItemManager.cs#L121

**Comment by lindydonna** [comment]
Closing this issue since it was more of a question on how to accomplish conflict handling.
