### ISSUE TITLE
 hub.mobileClient._request

### ISSUE THREAD

**Issue by honght0068** [Azure/azure-mobile-services#813]
I hit error "Not found" in the following method with cordova-android but proceed with no issue for cordova-ios.

Please advice...

var createRegistrationId = function (hub) {
		alert('createRegistrationId');
        // Variables needed to make the request to the mobile service.
        var method = "POST";
        var uriFragment = "/push/registrationids";

        var deferred = $.Deferred();
		alert('createRegistrationId2');
        // Send a Notification Hubs registration request to the Mobile Service.
        hub.mobileClient._request(method, uriFragment, null, null, null,
            function (error, response) {
            if (error) {
				//alert('Error: ' + error);
				alert('Error: ' + JSON.stringify(error));
                console.log("Error: " + error);
                deferred.reject("Error: " + error);
            } else {

                // Get the unique registration ID from the Location header.
                var location = response.getResponseHeader("Location");            
                var regex = /\S+\/registrations\/([^?]+).*/;
                var regId = regex.exec(location)[1];

                // Return the registration ID.
                deferred.resolve(regId);
            }
        });
        return deferred.promise();
    };

**Comment by phvannor** [comment]
Hmm, possibly you need to add the no cache header?  (see: https://github.com/Azure/azure-mobile-services/blob/dev/sdk/Javascript/src/Push/PushHttpClient.js#L10)

May I ask why you are calling registration directly yourself and not using the baked in push object for this?

(Also, beware that _request is a private variable)

**Comment by phvannor** [comment]
Closing as _request is meant to be private, reopen if it occurs using the default push object that makes these calls for you.
