### ISSUE TITLE
Please provide a version with latest dependencies

### ISSUE THREAD

**Issue by LooseContact** [Azure/azure-mobile-services#816]
I have permanent version conflicts, because of the restrictive, old dependencies. For example [Json.NET 6.0.4](https://www.nuget.org/packages/Newtonsoft.Json/6.0.4) which is older than 1 year.

**Comment by phvannor** [comment]
Is this for the managed SDK?  Looks like its only JSON that has a newer version available.  The dependencies are set to >=, so I take it that updating to 7.0.1 was causing some failures?

**Comment by infoloop** [comment]
It would seem many dependency issues are related to Microsoft.Owin = 3.0.0.
 3.0.1 is now out and many things use it.

**Comment by phvannor** [comment]
Ok, so this is for the server SDKs then.  Most of these types of issues are going to be resolved when Mobile Apps (https://github.com/Azure/azure-mobile-apps-net-server) leaves preview and hits GA.  The mobile apps nugets should compose easier with other dependencies and help avoid these kinds of issues.

**Comment by paulbatum** [comment]
Mobile Apps is now GA:
https://azure.microsoft.com/en-us/blog/announcing-general-availability-of-app-service-mobile-apps

This will not be addressed for mobile services.
