### ISSUE TITLE
74 duplicate symbols for architecture x86_64

### ISSUE THREAD

**Issue by DnJealt** [Azure/azure-mobile-services#821]
I'm using the mobile services framework version 3.0.0beta3, as it was provided by the download link in the Azure Portal. 

However, i get the following errors trying to get started with the SDK:
ld: 74 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Does anyone know a possible solution?

**Comment by phvannor** [comment]
Are you using the latest version of XCode?  I believe this how using a fw built with 7 and bit code enabled appears in older versions.

**Comment by phvannor** [comment]
Closing as I dont see this in XCOde 7, reopen if its happening there.
