### ISSUE TITLE
Unexpected MobileServicePushFailedException in IMobileServiceSyncHandler

### ISSUE THREAD

**Issue by Krumelur** [Azure/azure-mobile-services#831]
I'm providing a custom`IMobileServiceSyncHandler` which catches `MobileServicePreconditionFailedException`. 

* In my tests with the ToDo app sample, I added a new item and synced to Azure. I can see that the item is in the SQL DB and see that the version gets increased.
* I change the item's title in the server DB.
* In the client App (iOS, Xamarin) I change the item to "completed" state using the context menu actions.

When syncing, I see that calling `result = await operation.ExecuteAsync();` causes an exception in the sync handler. However it is a `MobileServicePushFailedException`. My understanding is that this should not happen.

Should I catch the `MobileServicePushFailedException ` in there too? How to handle it?

This happens with the 2.0.0-beta.

**Comment by phvannor** [comment]
Generally, any error your handler does not capture or that your handler throws will cause this one to happen at the end of the push process. 

Without seeing the code in your handler, its hard to say what should happen here.  It'd best to look at the errors contained in the PushFailedException and confirm that it is the ones you thought you handled.

Other types of errors (network access, timeouts, permission denied, SQL file writes, etc) may also be present.  Not all of them are handled vai the SyncHandler's onOperation methods.  They need handled at the sync complete level in the handler or the code calling Push() itself.

**Comment by pbosoa** [comment]
I also experience the same, having the error " table __errors has no column named operationkind" on my log.

**Comment by Krumelur** [comment]
I figured it out. Was too late yesterday to see it.

I was catching the `MobileServicePreconditionFailedException<T>` exception but the exception thrown in this case was a plain vanilla `MobileServicePreconditionFailedException` (non generic). That's why it wasn't caught and bubbled up.

I wonder if it is a good thing to use both types mixed? I don't see any added value of the generic version since I can always get the DTO by using `error.Value.ToObject<T> ();`
