### ISSUE TITLE
Query.deepClone() looses DateTimeOffset argument type.

### ISSUE THREAD

**Issue by dbychkov** [Azure/azure-mobile-services#838]
// Example:
DateTimeOffset maxUpdatedAt = new DateTimeOffset(mostRecent.getUpdatedAt());
Query query = QueryOperations.field(MobileServiceSystemColumns.UpdatedAt).ge(maxUpdatedAt);
query = query.deepClone(); 

// -- bug in ConstantNode.java,line 38, looses DateTimeOffset Type during cloning
//    so, I can't query services for createdAt and updatedAt columns

    public QueryNode deepClone() {
        ConstantNode clone = new ConstantNode();
        if (this.mValue instanceof Date) {
            clone.mValue = new Date(((Date) this.mValue).getTime());
        } else {
            clone.mValue = this.mValue;
        }
        return clone;
    }

**Comment by ysxu** [comment]
We will put the PR into the new repo https://github.com/azure/azure-mobile-apps-android-client.

**Comment by ysxu** [comment]
https://github.com/Azure/azure-mobile-apps-android-client/issues/7
