### ISSUE TITLE
DB Schema new Version - Android

### ISSUE THREAD

**Issue by icsd** [Azure/azure-mobile-services#839]
In case I want to make changes in the schema of my DB (e.g. add a table), should I use the onUpgrade() method that is in the SQLiteLocalStore class or do you have another mechanism implemented?
And after for example droping the existing tables in onUpgrade(),  which method should I use instead of onCreate() to initialize my DB with the new Schema?

**Comment by mamaso** [comment]
To have mobile services interact with the SQLite database you need to create SyncTables on the Android client corresponding to tables on the server side database.  Syncing the entire schema of your local SQLite db and your server db is not a use case we handle.  We only handle the tables declared in your client code.  

Hopefully that answers your question.  If you have any more questions we've moved to https://github.com/Azure/azure-mobile-apps-android-client, feel free to open an issue there
