### ISSUE TITLE
[iOS] Exception in Push.RegisterNativeAsync method

### ISSUE THREAD

**Issue by AlexS01** [Azure/azure-mobile-services#844]
When use library on iOS with Xamarin.Forms.

```
public class AzureNotificationHubService : IAzureNotificationHubService
{
    private readonly MobileServiceClient _mobileServiceClient;
    private readonly Push _push;

    public string CurrentDeviceId { get; private set; }

    public AzureNotificationHubService()
    {
        _mobileServiceClient = new MobileServiceClient(AzureMobileService.ApplicationURL, AzureMobileService.ApplicationKey);
        _push = _mobileServiceClient.GetPush();            
    }

    public async Task UnregisterNativeAsync()
    {
        await _push.UnregisterNativeAsync();
    }

    public async Task RegisterNativeAsync(string deviceId)
    {
        CurrentDeviceId = deviceId;
        
        try
        {
            await _push.RegisterNativeAsync(deviceId);
        }
        catch (Exception exception)
        {
            // EXCEPTION THERE
        }
    }
}
```

Nov 11 08:45:10 SOME-iPad XXXappiOS[1387] <Warning>: 11/11/15 8:45:10 - *** Push Notification - Device Registered - Token : 29b5b1bd03f1c22939e5515c388f7258964ba180393960dd849fe10f844eb1fd
Nov 11 08:45:11 SOME-iPad XXXappiOS[1387] <Warning>: 11/11/15 8:45:11 - *** RegisterNativeAsync exception
Nov 11 08:45:11 SOME-iPad XXXappiOS[1387] <Warning>: 11/11/15 8:45:11 - Source: mscorlib;
Nov 11 08:45:11 SOME-iPad XXXappiOS[1387] <Warning>: Message:Argument cannot be null.
Nov 11 08:45:11 SOME-iPad XXXappiOS[1387] <Warning>: Parameter name: key
Nov 11 08:45:11 SOME-iPad XXXappiOS[1387] <Warning>: StackTrace:  at System.ThrowHelper.ThrowArgumentNullException (ExceptionArgument argument) [0x00000] in /Users/builder/data/lanes/2320/bae2cdbe/source/maccore/_build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/src/mono/external/referencesource/mscorlib/system/throwhelper.cs:82
Nov 11 08:45:11 SOME-iPad XXXappiOS[1387] <Warning>:   at System.Collections.Generic.Dictionary`2[System.String,Microsoft.WindowsAzure.MobileServices.StoredRegistrationEntry].Insert (System.String key, Microsoft.WindowsAzure.MobileServices.StoredRegistrationEntry value, Boolean add) [0x00000] in <filename unknown>:0
Nov 11 08:45:11 SOME-iPad XXXappiOS[1387] <Warning>:   at System.Collections.Generic.Dictionary`2[System.String,Microsoft.WindowsAzure.MobileServices.StoredRegistrationEntry].set_Item (System.String key, Microsoft.WindowsAzure.MobileServices.StoredRegistrationEntry value) [0x00000] in <filename unknown>:0
Nov 11 08:45:11 SOME-iPad XXXappiOS[1387] <Warning>:   at Microsoft.WindowsAzure.MobileServices.LocalStorageManager.UpdateRegistrationByName (System.String registrationName, System.String registrationId, System.String registrationDeviceId) [0x00019] in <filename unknown>:0
Nov 11 08:45:11 SOME-iPad XXXappiOS[1387] <Warning>:   at Microsoft.WindowsAzure.MobileServices.LocalStorageManager.UpdateRegistrationByRegistrationId (System.String registrationId, System.String registrationName, System.String registrationDeviceId) [0x00078] in <filename unknown>:0
Nov 11 08:45:11 SOME-iPad XXXappiOS[1387] <Warning>:   at Microsoft.WindowsAzure.MobileServices.RegistrationManager+<RefreshRegistrationsForChannelAsync>d__1a.MoveNext () [0x000ff] in <filename unknown>:0
Nov 11 08:45:11 SOME-iPad XXXappiOS[1387] <Warning>: --- End of stack trace from previous location where exception was thrown ---
Nov 11 08:45:11 SOME-iPad XXXappiOS[1387] <Warning>:   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000b] in /Users/builder/data/lanes/2320/bae2cdbe/source/maccore/_build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/src/mono/mcs/class/corlib/System.Runtime.ExceptionServices/ExceptionDispatchInfo.cs:61
Nov 11 08:45:11 SOME-iPad XXXappiOS[1387] <Warning>:   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003b] in /Users/builder/data/lanes/2320/bae2cdbe/source/maccore/_build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/src/mono/external/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:199
Nov 11 08:45:11 SOME-iPad XXXappiOS[1387] <Warning>:   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in /Users/builder/data/lanes/2320/bae2cdbe/source/maccore/_build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/src/mono/external/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:170
Nov 11 08:45:11 SOME-iPad XXXappiOS[1387] <Warning>:   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in /Users/builder/data/lanes/2320/bae2cdbe/source/maccore/_build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/src/mono/external/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:142
Nov 11 08:45:11 SOME-iPad XXXappiOS[1387] <Warning>:   at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in /Users/builder/data/lanes/2320/bae2cdbe/source/maccore/_build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/src/mono/external/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:124
Nov 11 08:45:11 SOME-iPad XXXappiOS[1387] <Warning>:   at Microsoft.WindowsAzure.MobileServices.RegistrationManager+<RegisterAsync>d__0.MoveNext () [0x000d6] in <filename unknown>:0
Nov 11 08:45:11 SOME-iPad XXXappiOS[1387] <Warning>: --- End of stack trace from previous location where exception was thrown ---
Nov 11 08:45:11 SOME-iPad XXXappiOS[1387] <Warning>:   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000b] in /Users/builder/data/lanes/2320/bae2cdbe/source/maccore/_build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/src/mono/mcs/class/corlib/System.Runtime.ExceptionServices/ExceptionDispatchInfo.cs:61
Nov 11 08:45:11 SOME-iPad XXXappiOS[1387] <Warning>:   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003b] in /Users/builder/data/lanes/2320/bae2cdbe/source/maccore/_build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/src/mono/external/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:199
Nov 11 08:45:11 SOME-iPad XXXappiOS[1387] <Warning>:   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in /Users/builder/data/lanes/2320/bae2cdbe/source/maccore/_build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/src/mono/external/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:170
Nov 11 08:45:11 SOME-iPad XXXappiOS[1387] <Warning>:   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in /Users/builder/data/lanes/2320/bae2cdbe/source/maccore/_build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/src/mono/external/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:142
Nov 11 08:45:11 SOME-iPad XXXappiOS[1387] <Warning>:   at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in /Users/builder/data/lanes/2320/bae2cdbe/source/maccore/_build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/src/mono/external/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:124
Nov 11 08:45:11 SOME-iPad XXXappiOS[1387] <Warning>:   at XXXapp.iOS.BLL.AzureNotificationHubService+<RegisterNativeAsync>d__3.MoveNext () [0x00091] in <filename unknown>:0

**Comment by phvannor** [comment]
Note: This may be NH returning nulls, and this code base needs the same fix that was done over here: https://github.com/Azure/azure-mobile-services/commit/f2119af1849b87542efbe77bb027dfa168228d3d#diff-d7d786ab102158791637bc78f2069ce7

**Comment by AlexS01** [comment]
What is NH?
deviceId parameter is not null, I've checked.
Clarify, please, what is "this code base"? Azure library's code should be fixed or my code, that uses azure library?

**Comment by phvannor** [comment]
NH = Notification Hubs, which is the Azure service being used to do the registration on our side.  This was mainly a note to myself/whoever gets a chance to look at this one to figure out what is occurring.

In the iOS client, it was the templateName coming back from the server that was null and causing an issue in our code base.  

Looking at the error, it looks like it may be the same base cause, this line: 

https://github.com/Azure/azure-mobile-services/blob/master/sdk/Managed/src/Microsoft.WindowsAzure.MobileServices/Push/LocalStorageManager.cs#L102

Is the error above, and probably means registration.Name is null.  

The stack trace, means it should be null coming out of here:
https://github.com/Azure/azure-mobile-services/blob/8b176174c5d52c4ecd45450c89e91f06a423bdd6/sdk/Managed/src/Microsoft.WindowsAzure.MobileServices/Push/RegistrationManager.cs#L134

Which implies that the list call to the server is getting back a registration with no name here:
https://github.com/Azure/azure-mobile-services/blob/master/sdk/Managed/src/Microsoft.WindowsAzure.MobileServices/Push/PushHttpClient.cs#L27

So most likely we (Azure) need to update the list call (base Registration Class) to populate the name to "$Default" in this case.
