### ISSUE TITLE
Unable to install WindowsAzure.Storage

### ISSUE THREAD

**Issue by DnJealt** [Azure/azure-mobile-services#854]
Hi!
I don't know if this is the right place to post this issue, but:

I am currently following the tutorial on how to add Azure Storage to my mobile service, as described [here](https://azure.microsoft.com/nl-nl/documentation/articles/mobile-services-dotnet-backend-windows-universal-dotnet-upload-data-blob-storage/#install-the-storage-client-in-the-mobile-service-project). 

However, doing this step results in the following error:
___Updating 'Microsoft.Data.OData 5.6.2' to 'Microsoft.Data.OData 5.6.4' failed. Unable to find versions of 'WindowsAzure.MobileServices.Backend.Tables, WindowsAzure.MobileServices.Backend.Entity' that are compatible with 'Microsoft.Data.OData 5.6.4'.___

Is there going to be an updated version of MobileServices that supports Microsoft.Data.OData 5.6.4, or do I have to use WindowsAzure.Storage 4.3.0?

Thanks in advance

**Comment by phvannor** [comment]
This is the kind of issue that is being resolved with the work done of the Mobile Apps work (now open source: https://github.com/Azure/azure-mobile-apps-net-server)

If you can, I recommend looking at migrating over.  (Its table package is already using 5.6.4 so you shouldn't have this particular issue)

Right now, the dependency chain on the Services backend will probably not be updated in the near future.
