### ISSUE TITLE
In MobileServiceHttpClient class, remove the AssemblyFileVersion from the building of user agent string

### ISSUE THREAD

**Issue by jsauvexamarin** [Azure/azure-mobile-services#855]
In Xamarin.iOS, (where I believe this library is very commonly used) the linker strips away some `AssemblyInfo` attributes, including `AssemblyFileVersionInfo`. The value from this attribute is used [in the bowels of the MobileServiceHttpClient](https://github.com/Azure/azure-mobile-services/blob/master/sdk/Managed/src/Microsoft.WindowsAzure.MobileServices/Http/MobileServiceHttpClient.cs#L695), where it's used to buildup the user agent string; I presume so that MSFT can measure what versions of their client SDK are hitting their endpoints.

The problem is that when linking is enabled in a Xamarin.iOS solution (and presumably in other linkers as well), the `AssemblyFileVersionInfo` attribute is stripped off. So the result of the LINQ statement on line 695 is null. And then on the very next line, the method attempts to access the `Version ` property on the null `fileVersionAttribute` local variable.

I understand the reason for trying to grab the value: to track client SDK versions. But basing it on an attribute that gets stripped off with linking probably isn't a very good way to achieve it. Just my two cents! Thanks!

**Comment by fabiocav** [comment]
@jsauvexamarin thank you for reporting this! We're working on a fix and some enhancements to prevent linker related issues from happening in the future.

**Comment by phvannor** [comment]
@fabiocav will we only do the fix on the Apps side?  Or do you plan on doing it as well for services?

**Comment by fabiocav** [comment]
@phvannor we'll be doing this for Mobile Services as well.
