### ISSUE TITLE
On WP8, when calling client.login to open the Facebook dialog gives me "Cannot reach window opener. It may be on a different Internet Explorer zone"

### ISSUE THREAD

**Issue by henriksen** [Azure/azure-mobile-services#86]
I've made a small HTML/JS web application that uses Mobile Services as a backend and Facebook for authentication. This works fine on my computer and after deployment to Azure as long as I use my desktop browser. 

Browsing the site from my Windows Phone 8 (Lumia 920) and clicking my "Login with Facebook"-button however, that opens up a Facebook page, redirect back to my mobile services URL which gives me the error "Cannot reach windows opener. It may be on a different Internet Explorer zone.

I noticed someone else had the same problem a while ago on StackOverflow: http://stackoverflow.com/questions/16293341/how-to-authenticate-users-on-azure-mobile-services-from-windows-phone-8-using-ht

They were told to file a bug here, and since I couldn't find it I've created a new issue.

**Comment by paulbatum** [comment]
This is a pretty old bug. We recommend targeting WP81 (winRT) / Win10 UAP and using WAB which doesnt have the issues with popups.
