### ISSUE TITLE
ZumoDeploy.cmd & updateRepositoryItem timeouts

### ISSUE THREAD

**Issue by mamaso** [Azure/azure-mobile-services#861]
ZumoDeploy.cmd can run >45s causing RP updateRepositoryItem calls to timeout.  This is displayed as a 408 error in the portal.  Modifying the script to not use selectNodeVersion script should solve the problem

**Comment by phvannor** [comment]
@mamaso can you move this issue to the correct repo?

**Comment by paulbatum** [comment]
Moved to https://github.com/Azure/azure-mobile-services-pr/issues/238
