### ISSUE TITLE
PullAsync: Incremental sync will sync the last created item over and over because updatedAt uses ge

### ISSUE THREAD

**Issue by renzska** [Azure/azure-mobile-services#865]
I'm currently getting instances where PullAsync with a unique queryId returns the last item every time PullAsync is called because the filter for updatedAt uses ge (greater or equal) rather than just greater than). As you can see below, the requests have `(updatedAt ge datetimeoffset'2015-12-13T04:28:12.8160000%2B00:00')` while the updatedAt of the Response matches that `"updatedAt":"2015-12-13T04:28:12.816Z"` therefore always syncing the last created item and creating two requests to be sent from the one call as shown below.

This also causes to requests to be sent to the server which should be avoided.

Requests:
```
2015-12-22 11:55:01.147 AppiOS[1694:7409279]
Request: https://app-code.azurewebsites.net/tables/Child?$filter=(updatedAt ge datetimeoffset'2015-12-13T04:28:12.8160000%2B00:00')&$orderby=updatedAt&$skip=0&$top=50&__includeDeleted=true

2015-12-22 11:55:01.643 AppiOS[1694:7409279]
Response:   [{"deleted":false,"updatedAt":"2015-12-13T04:28:12.816Z","createdAt":"2015-11-17T22:45:21.475Z","version":"AAAAAAAAJyY=","id":"c1816d8d-046a-4144-9e30-1eba6fbf7888","photo":"51ec63a3-5a50-4e7b-82db-edc5bd13831e.jpg","displayOrder":0,"identityColor":"#ef222f","lastName":"Last","firstName":"First"}]

2015-12-22 11:55:01.659 AppiOS[1694:7409279]
Request: https://app-code.azurewebsites.net/tables/Child?$filter=(updatedAt ge datetimeoffset'2015-12-13T04:28:12.8160000%2B00:00')&$orderby=updatedAt&$skip=1&$top=50&__includeDeleted=true

2015-12-22 11:55:01.733 AppiOS[1694:7409279]
Response:   []
```

My method
```
public async Task<ObservableCollection<Child>> ChildrenGetAsync()
		{
			if (!initialized)
				await Init();
		
			if (await ConnectivityService.IsConnected())
			{
				var children = new ObservableCollection<Child>();

				using (new PerformanceTester("ChildrenGetAsync"))
				{
					await childSyncTable.PullAsync("ChildrenGet" + AzureService.Instance.CurrentMobileServiceUser.UserId, childSyncTable.CreateQuery());
					List<Child> items = await childSyncTable.ToListAsync();
					children = new ObservableCollection<Child>(items.OrderBy(x => x.FirstName));
				}
				return children;
			}
			return new ObservableCollection<Child>();
		}
```

**Comment by phvannor** [comment]
We currently use ge, as we can not guarantee we received all the data at the last updatedAt we got (could be more on page 2, etc)  see: https://github.com/Azure/azure-mobile-services/issues/680 for a better option, not sure where the tracking issue is on the -apps versions to link here

**Comment by paulbatum** [comment]
Tracking this in the new client SDK repo as Azure/azure-mobile-apps-net-client/issues/51
