### ISSUE TITLE
MobileServiceClient Signature changed

### ISSUE THREAD

**Issue by DominikErnst** [Azure/azure-mobile-services#866]
I want to use the Azure Mobile Client,

I updated to this Version:
  package id="Microsoft.Azure.Mobile.Client" version="2.0.1" targetFramework="win81" 

but the Signature of following method has changed, so that I cannot set the "application key":

  public static MobileServiceClient MobileService = new MobileServiceClient(
            "https://nameofapp.azure-mobile.net/", "xxxxxxxxxxxxxxxxxxxxxxxxxxxxx" );

1. What to do here?
2. When is a UWP - Version available?

**Comment by phvannor** [comment]
There is no longer a App Key built into the Azure Mobile Apps version, so it is not necessary to provide one.  @lindydonna , @adrianhall can one of you provide UWP information?

**Comment by phvannor** [comment]
Also the new .Net client now lives off of https://github.com/Azure/azure-mobile-apps-net-client for future issues/questions.

**Comment by paulbatum** [comment]
You might want to take a look at this document for more info on upgrading to the latest client and server:
https://azure.microsoft.com/en-us/documentation/articles/app-service-mobile-net-upgrading-from-mobile-services/

Have you run into problems using the 2.0.1 package in a UWP app? We are still in the process of doing full UWP testing and this is why we don't have a quickstart and full documentation for it yet, but we're not aware of any major blocking issues that should impact UWP scenarios. 

If you do run into any UWP specific issues/questions for the Microsoft.Azure.Mobile.Client package, please file them in the new repository that Phillip linked to above.

**Comment by DominikErnst** [comment]
Thank you for your help. I'm using at the moment:
    "SQLite.Net-PCL": "3.1.1",
    "SQLite.Net.Async-PCL": "3.1.1",
    "WindowsAzure.Messaging.managed": "0.1.7.9",
    "WindowsAzure.MobileServices": "2.0.0-beta-3",
    "WindowsAzure.MobileServices.SQLiteStore": "2.0.0-beta-2"
It works, but should I change any Package to stay up to date?

**Comment by phvannor** [comment]
You want to flip your client packages to the renamed "Microsoft.Azure.Mobile.Client : 2.0.1 and Microsoft.Azure.Mobile.Client.SQLiteStore : 2.0.1

**Comment by DominikErnst** [comment]
ok, thank you very much.
