### ISSUE TITLE
Azure Mobile Services version 2.0.0-beta source code

### ISSUE THREAD

**Issue by ltaljaard** [Azure/azure-mobile-services#867]
Please advise where I can get the source code for the Managed SDK version 2.0.0-beta? I've loaded this (Beta-channel) NuGet package into my Xamarin project but now I need to debug into something to see what's happening. The code at https://github.com/Azure/azure-mobile-services is only for version 1.3.2. There are significant differences between these versions and so I can't use the 1.3.2 code.

**Comment by phvannor** [comment]
The apps versions are now split out be client, the 2.0 source can be found here: https://github.com/Azure/azure-mobile-apps-net-client

Also, for managed you should have a 2.0 now you can use over the beta.

**Comment by ltaljaard** [comment]
Thanks, that helps a lot. Could you also clarify the development phase of the 2.0 version? Is it out of Beta? When I go to the "Add Packages..." context menu option in Xamarin Studio and search the "Official NuGet Gallery" only, I can only see version 1.3.2. I must first select "show pre-release packages" before I can see the 2.0 version, and then the highest version available there is 2.0.0-beta-3 (i.e. a beta version). Are you planning on releasing the 2.0 final release to the official NuGet gallery any time soon?

**Comment by phvannor** [comment]
Yes, because of the breaking client-server contract (ie you need to use a Mobile App Server SDK) we renamed the client.  So switching will be a little painful, as you will need to uninstall the services and intsall the app nuget.  The new nuget is this one: 
https://www.nuget.org/packages/Microsoft.Azure.Mobile.Client/

**Comment by ltaljaard** [comment]
Thanks for clarifying. May I suggest you add a note in the Readme of the Azure/azure-mobile-services Github project that Azure/azure-mobile-apps-net-client is actually the newer version, because for most users there will be no way of knowing about this.

**Comment by phvannor** [comment]
Yeah, it'd be a good idea to update all the -services to call out links back to the newer -apps branded repos.  It's pointed out on the https://github.com/Azure/azure-mobile-services/tree/MobileApp branch, which was were the betas lived before, but that isn't as visible for people who haven't been following along the whole time.

**Comment by ltaljaard** [comment]
Last question please. I see in the final Azure Mobile Client version (2.0.1) that the constructor for MobileServiceClient has changed since the 2.0.0-beta3 version. Previously the constructor took in the Application URL, Gateway URL and Application Key. Now I see the Gateway URL and Application Key have both been dropped from the constructor? I thought the whole point of the newer version was to go through the Gateway? How should I now be going about setting up a connection to the MobileServiceClient? There must now be another mechanism to pass the Gateway URL and Application Key into the mix before the connection can be made?

**Comment by phvannor** [comment]
With the last updates we flipped from using the gateway for authentication to the easy auth feature of websites (which was updated to provide the same core functionality as the gateway was).  @mattchenderson can you link to the blog posts / documentation on the changes made here?

**Comment by ltaljaard** [comment]
I've just come across this link: https://azure.microsoft.com/en-us/blog/announcing-app-service-authentication-authorization/

But is there more info available on the topic? Specifically, I need to still be able to run my mobile app against a locally running backend (as opposed to the live Azure site) for test purposes. Is there an example that I can look at of how I can get that working with the new 2.0.1 mobile client version?

Will my backend project (the one running the Azure test site locally) that I have been using to date (with the older 2.0.0-beta3 mobile client API) need any changes made to it?

**Comment by phvannor** [comment]
You are using https://www.nuget.org/packages/Microsoft.Azure.Mobile.Server/ for you server?  You will probably need to update to newer copies that have the auth changes included.

For local debugging (or to continue to use Gateway auth) you can use the following new properties: https://github.com/phvannor/azure-mobile-apps-net-client/blob/master/sdk/src/Microsoft.WindowsAzure.MobileServices/IMobileServiceClient.cs#L32-L40

When debugging, init the client to localhost, but set AlternateLoginHost to your normal mobile App URL.

Then in your server for local auth debug, add this line in app start
 app.UseAppServiceAuthentication(config, AppServiceAuthenticationMode.LocalOnly);

**Comment by ltaljaard** [comment]
I'm trying to do what you suggested in the Startup.MobileApp.cs file (class Startup, method ConfigureMobileApp): app.UseAppServiceAuthentication(config, AppServiceAuthenticationMode.LocalOnly);

But there is no definition for AppServiceAuthenticationMode. Method UseAppServiceAuthentication takes a parameter of type AppServiceAuthenticationOptions, but that class doesn't contain any definition for LocalOnly either... ?

**Comment by phvannor** [comment]
@brettsam can you comment?

**Comment by phvannor** [comment]
Looks like the code is now like so: 

https://github.com/Azure/azure-mobile-apps-quickstarts/blob/master/backend/dotnet/Quickstart/ZUMOAPPNAMEService/App_Start/Startup.MobileApp.cs#L36-L47  

            if (string.IsNullOrEmpty(settings.HostName))
            {
                // This middleware is intended to be used locally for debugging. By default, HostName will
                // only have a value when running in an App Service application.
                app.UseAppServiceAuthentication(new AppServiceAuthenticationOptions
                {
                    SigningKey = ConfigurationManager.AppSettings["SigningKey"],
                    ValidAudiences = new[] { ConfigurationManager.AppSettings["ValidAudience"] },
                    ValidIssuers = new[] { ConfigurationManager.AppSettings["ValidIssuer"] },
                    TokenHandler = config.GetAppServiceTokenHandler()
                });
            }

Brett, can you confirm thats right?

**Comment by brettsam** [comment]
Yes this is correct. You need to supply the SigningKey, issuer, and audience that App Service Auth uses to create tokens and then you'll be able to validate real tokens locally:

 - Signing key can be found by going to https://{yoursite}.scm.azurewebsites.net/env and looking for the WEBSITE_AUTH_SIGNING_KEY value.
 - Both audience and issuer will be https://{yoursite}.azurewebsites.net/ (including the trailing slash).

**Comment by brettsam** [comment]
Here's a blog post that can help: http://www.systemsabuse.com/2015/12/04/local-debugging-with-user-authentication-of-an-azure-mobile-app-service/
