### ISSUE TITLE
After a push, the value sent back by the server is not correctly handled if Id has been changed by server.

### ISSUE THREAD

**Issue by loyke0** [Azure/azure-mobile-services#868]
after calling "syncHandler.ExecuteTableOperationAsync (IMobileServiceTableOperation operation)"
the returned oject is upserted into the local store.
If the server changed the "Id" of the object (and thus "returned object" id is different from operation.Item id) the returned object is upserted but the operation.Item object is never deleted from the local store.

Shouldn't there be a check that compare both object Id and delete the operation.Item object in case they are different?

**Comment by phvannor** [comment]
Id mutation is not a currently supported workflow, none of the default logic will handle this case.  Can you outline why your need for this feature?

**Comment by loyke0** [comment]
I'll try to describe the use-case as well as possible.

There are tablets in different places with an app where users can chek-in.
In order to register/check-in, a user only has to provide a phone number or an email address.
The userid is autogenerated.

"The user" goes to place A and checks in for the first time ever in the system.
"The user" is saved in the local store and synched with the server which then dispatch the "The user" info(phone/email+id) to the other tablets .

"The user" goes to place B which has been offline since before he checked in at A (tablet in place B doesn't know about "The user") .
"The user" checks in but is not found.
So a new user is created locally with a different user id.
Then later, B comes back online and synchs.

On the server, I detect that a user is already registered with the same phone number and/or email address (A.K.A "The user").
Because I want to avoid duplicate user on the server, 
I send back "The user"  (the one with the original id) and ignore the version sent by tablet B.

On the tablet B, "The user" sent back by the server is saved locally.
but the version of the user originally sent by the app (the one ignored by the server) is never deleted locally which leads to a duplicate user locally.

I Hope this was clear enough.

I've implemented a workaround that consist in running a query that detect duplicate phone number/mail address and figures out the "real" version by querying the server table by id and delete the one with the key not found but this is not a very clean solution.

**Comment by phvannor** [comment]
moving to: https://github.com/Azure/azure-mobile-apps/issues/7
