### ISSUE TITLE
Failed to resolve: com.microsoft.azure:azure-mobile-services-android-sdk:2.0.3

### ISSUE THREAD

**Issue by Nyceane** [Azure/azure-mobile-services#870]
Hey guys, is server down or is it something wrong?  I can't seem to get this to compile with gradle

**Comment by soninaren** [comment]
I just tested the com.microsoft.azure:azure-mobile-services-android-sdk:2.0.3 with a quick start app. It worked for me. 
What is the exact compile error you are getting?

**Comment by soninaren** [comment]
Please re-opne if you are still seeing the error.
