### ISSUE TITLE
Cocoapods Versioning

### ISSUE THREAD

**Issue by joninsky** [Azure/azure-mobile-services#872]
Can you update the podspec file to let us update from version 1.2.4? I can't use any of the offline modes with the current version that cocoapods pulls.

**Comment by joninsky** [comment]
Here is the podspec I am pulling from: https://github.com/CocoaPods/Specs/blob/5e07088fac755758513e8533b934b779361fc3b1/Specs/AzureSDK-iOS/1.2.4/AzureSDK-iOS.podspec.json

**Comment by damienpontifex** [comment]
I'm not sure that the podspec you linked is actually maintained by MS as I had run into this in the past. 

The iOS client has moved to another repo here https://github.com/Azure/azure-mobile-apps-ios-client and until any official spec release, I have been able to use the dependency in my Podfile as

```ruby
pod 'MicrosoftAzureMobile', :git => 'https://github.com/Azure/azure-mobile-apps-ios-client.git'
```

I've been using this to get the latest for a while which is now 3.0.0 I believe
