### ISSUE TITLE
Have support swift? 

### ISSUE THREAD

**Issue by ingscjoshua** [Azure/azure-mobile-services#873]
do you have support for swift?

**Comment by paulbatum** [comment]
We do! [This tutorial](https://azure.microsoft.com/en-us/documentation/articles/app-service-mobile-ios-get-started/) should help you get started, we have a preconfigured swift project you can download.

A couple of additional notes:
- there is a known issue (see https://github.com/Azure/azure-mobile-apps/issues/15) with the download on Safari. We're trying to get it fixed, but in the meantime try Chrome if you can.
- this github repo is actually for an older version of our product. If you want the latest and greatest stuff you should check out https://github.com/Azure/azure-mobile-apps-ios-client
