### ISSUE TITLE
version capability issue in UWP App

### ISSUE THREAD

**Issue by programmersommer** [Azure/azure-mobile-services#876]
I have installed:
WindowsAzure.MobileServices  version 1.3.2
WindowsAzure.MobileServices.SQLiteStore  version 1.0.4
But exception is thrown on line:
await App.MobileService.SyncContext.PushAsync();
When I adding in Azure Mobile App setting MS_SkipVersionCheck - everything works.
Everything except incremental pull.
Here is topic on [MSDN forum](https://social.msdn.microsoft.com/Forums/en-US/1cdec17d-407e-4b3d-a3e7-d364002ea4bf/pullasync-doesnt-async-incremently?forum=azuremobile)

**Comment by fabiocav** [comment]
@programmersommer I have provided additional information on the forum. This is a problem with the package versions you're currently using.

**Comment by programmersommer** [comment]
Thank you very much! Now it's clear! )
