### ISSUE TITLE
Adding an event driven backend function

### ISSUE THREAD

**Issue by Jackson0111** [Azure/azure-mobile-services#879]
After days of frustration with AWS, I decided to try out Azure Mobile Services. However, I'm not sure what I can do to have a backend function that gets triggered to run a full text search algorithm in the database. When new data is added to the database, I want this function to be invoked and do a search action in the database, then send notifications according to the search result. 

What I want to do is like Parse Cloud Code, or AWS Lambda + S3. In this tutorial : "Add Push Notifications to iOS App and JavaScript Backend" (https://azure.microsoft.com/en-us/documentation/articles/mobile-services-javascript-backend-ios-get-started-push/), it says "In TodoItem, click the Script tab and select Insert. This displays the function that is invoked when an insert occurs in the TodoItem table." Does this mean any function can be triggered by adding data to the database? 

Please help, I'm desperate, any suggestions would be highly appreciated.

**Comment by paulbatum** [comment]
One quick suggestion first. I highly recommend you try out Azure Mobile Apps (its basically the new version of mobile services). You'll be using and learning our latest and greatest stuff that way. 

To get started with Mobile Apps go [here](https://azure.microsoft.com/en-us/documentation/articles/app-service-mobile-ios-get-started). Once you complete that tutorial, you will have a todoitem table. You can work with it, including adding scripts, using the Easy tables option in the settings:

![image](https://cloud.githubusercontent.com/assets/10663/13407303/99464e02-dedc-11e5-8af6-9c7a44fd382f.png)

From here, hit the Edit Script button and then you will be taken to an online IDE for working with your server code:

![image](https://cloud.githubusercontent.com/assets/10663/13407340/cc65f21a-dedc-11e5-8ede-ff4ae0dde334.png)

As you can see, we generate you a default script that has examples commented out for running code when reading, inserting etc.

The Mobile Apps version of the tutorial you were looking at is [here](https://azure.microsoft.com/en-us/documentation/articles/app-service-mobile-ios-get-started-push). That tutorial includes an example todoitem.js script that sends a push notification. 

Hopefully that will help you get started! Closing this as answered, feel free to reopen if I didnt answer your question properly.
