### ISSUE TITLE
[iOS] So many warning when build WindowsAzureMobileServices on XCode 7.2.1 (7C1002)

### ISSUE THREAD

**Issue by TranChuong** [Azure/azure-mobile-services#880]
I have problem like photo when I build the static library WindowsAzureMobileServices
How to solve it?

<img width="802" alt="screen shot 2016-02-28 at 13 53 28" src="https://cloud.githubusercontent.com/assets/7924855/13377918/c3da54a2-de22-11e5-9f1c-2511e3207b8e.png">

**Comment by shrishrirang** [comment]
The missing symbols you are seeing are types from the Foundation framework. This seems something to do with your project settings. 

You can use https://github.com/Azure/azure-mobile-apps-quickstarts/tree/master/client/iOS/ZUMOAPPNAME as a reference project. Clone the repository and open the project in XCode. The project has a reference to the Azure Mobile Apps framework which will be missing from the project. You can download the framework from https://go.microsoft.com/fwLink/?LinkID=529823.

**Comment by shrishrirang** [comment]
The missing symbols you are seeing are types from the Foundation framework. This seems something to do with your project settings.

You can use https://github.com/Azure/azure-mobile-services-quickstarts/tree/master/client/iOS/ZUMOAPPNAME as a reference project. Clone the repository and open the project in XCode. The project has a reference to the Azure Mobile Services framework which will be missing from the project. You can download the framework from http://aka.ms/gc6fex.

Also, I would recommend you to consider moving from Azure Mobile Services to Azure Mobile Apps. Here are some useful links: https://azure.microsoft.com/en-us/documentation/articles/app-service-mobile-value-prop/ and https://azure.microsoft.com/en-us/documentation/articles/app-service-mobile-value-prop-migration-from-mobile-services/

**Comment by TranChuong** [comment]
Thanks @shrishrirang
