### ISSUE TITLE
Offline support for js SDK

### ISSUE THREAD

**Issue by izaaz** [Azure/azure-mobile-services#882]
Is there a plan for offline data support in the JS SDK?

**Comment by paulbatum** [comment]
For Cordova, yes. We actually began this work several months ago but we had to put it on hold temporarily while we worked on getting our Cordova support up to date with the latest Azure Mobile Apps changes, and with that work almost complete we will be soon resuming work on offline support. 

You'll be able to track the work as it happens in the offline branch for our JS SDK:
https://github.com/Azure/azure-mobile-apps-js-client/tree/offline

At this time we do not have any concrete plans to get offline scenarios working in other JS based environments (such as the browser).
