### ISSUE TITLE
UpdatedAt date parsing error on the last item in Android

### ISSUE THREAD

**Issue by dimeilof** [Azure/azure-mobile-services#884]
I encoutered a problem while syncing tables. When the updatedAt field in the last item in the json does not have milliseconds, it is not parse properly and the SDK keep asking the server for new items without the new DateTimeOffset.

There's the problem in IncrementalPullStrategy.java
```java
SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSS'Z'");
sdf.setTimeZone(TimeZone.getTimeZone("UTC"));

try {
    return new DateTimeOffset(sdf.parse(stringValue));
} catch (ParseException e) {
    return null;
}
```

This code can't parse date formatted with `yyyy-MM-dd'T'HH:mm:ss'Z'` which is a valid ISO 8601 format.

This would be a good solution
```java
SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSS'Z'");
sdf.setTimeZone(TimeZone.getTimeZone("UTC"));

try {
    return new DateTimeOffset(sdf.parse(stringValue));
} catch (ParseException e) {
    try {
        // Didn't work, trying without ms
        sdf = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss'Z'");
        sdf.setTimeZone(TimeZone.getTimeZone("UTC"));

        return new DateTimeOffset(sdf.parse(stringValue));
    } catch (ParseException e) {
        return null;
    }
}
```

**Comment by soninaren** [comment]
@dimeilof have moved the issue to Azure mobile apps.
https://github.com/Azure/azure-mobile-apps-android-client/issues/54

This looks like a valid fix. Testing the changes to see if this causes any issues in the incremental sync algorithm.

**Comment by adrianhall** [comment]
Closing for lack of response.
