### ISSUE TITLE
Better support of usual linq queries

### ISSUE THREAD

**Issue by FrancoisM** [Azure/azure-mobile-services#886]
Hi,

It's not an issue but rather a request.
It would be great to have more querying methods for IMobileServiceSyncTable.
Any or First are really missing for example.

Right now I'm writing extensions like this one:

```
public static async Task<bool> Any<T>(this IMobileServiceSyncTable<T> table, Expression<Func<T, bool>> predicate)
        {
            return (await table.Where(predicate).Take(1).ToEnumerableAsync().ConfigureAwait(false)).Any();
        }
```

Tks.

François

**Comment by adrianhall** [comment]
If this is still an issue with Azure Mobile Apps (it shouldn't be), then please file an issue in the appropriate repo - probably azure/azure-mobile-apps-net-client
