### ISSUE TITLE
Support NativeScript

### ISSUE THREAD

**Issue by georgeedwards** [Azure/azure-mobile-services#887]
[Nativescript](https://github.com/NativeScript/NativeScript) is proving a very popular and rapidly growing JavaScript framework for Mobile development, which with the release of Angular 2.0 is only likely to increase. It would be great to support this new platform and I know there is a community demand for a NativeScript Plugin for Azure Mobile Services. Is this something which you would be willing to support? I would be more than happy to help write a wrapper etc. and I am sure much of the NativeScript community would too. 

What do you think?

**Comment by paulbatum** [comment]
@georgeedwards I moved this issue to https://github.com/Azure/azure-mobile-apps as that is where we are tracking new work.

**Comment by paulbatum** [comment]
Closing this issue as we are not taking any new features for the legacy mobile services client. See the issue above for discussion of NativeScript support for azure mobile apps.
