### ISSUE TITLE
Server no longer reports URL too long error

### ISSUE THREAD

**Issue by jmichas** [Azure/azure-mobile-services#892]
Hi, I spent a day trying to debug a 404 error when my mobile app called my server with a filter that was large. In the old version (Azure Mobile Services) the failure error reported to the client was something like "Request Uri Too Long". The current server just reports a 404 and the request fails to hit the table controller so there is no debugging that you can do.

I probably should have thought of it sooner, but if I had seen the uri too long error I would have increased the querystring and url size in the web.config and been done with it. It would be nice if this was documented somewhere or if the error could be more descriptive than just a 404.

**Comment by paulbatum** [comment]
@jmichas I'd like to file this issue in the right location. Am I correct in assuming you were using the Azure Mobile Apps .NET server SDK when you hit this?

**Comment by jmichas** [comment]
Yeah previously I had a Azure Mobile Services backend, I upgraded that to a Mobile Apps .NET backend. In WAMS it gave me the request uri too long error, in Mobile Apps it does not, just a 404. Did I post this in the wrong place?

**Comment by paulbatum** [comment]
This repo covers mobile services. For Mobile Apps, we created a separate repository for each component. I filed https://github.com/Azure/azure-mobile-apps-net-server/issues/119
