### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by icsd** [Azure/azure-mobile-services#895]
In SQLiteLocalStore.java, the `upsert` method makes the following computation `int pageCounts = (itemsCount / pageSize) + 1;` which produces a wrong `pageCounts` value in case that
`(itemsCount / pageSize)` is an integer (has 0 fractional-part). More specifically the `pageCounts` variable 
will have a value of +1 than the actual value and this produces the following error 
`java.util.concurrent.ExecutionException:myPackageName.azure.table.sync.localstore.MobileServiceLocalStoreException: java.lang.ArrayIndexOutOfBoundsException: length=0; index=0` in the `generateUpsertStatement` method.

The correct computation is `int pageCounts = (int) Math.ceil((double)itemsCount / (double)pageSize);`

**Comment by adrianhall** [comment]
This repo is no longer maintained.  If the issue is within Azure Mobile Apps (not mobile services), then please file the issue in azure/azure-mobile-apps-android-client
