### ISSUE TITLE
Rename the repo description to say deprecated

### ISSUE THREAD

**Issue by ggailey777** [Azure/azure-mobile-services#896]
Because the description of this repo shows up so high in Google searches for _azure mobile_, we should change the description to mention the pending deprecation and a link to the blog post--something like this:
![mobileservicesrepodeprecation](https://cloud.githubusercontent.com/assets/1388263/15630849/51368f26-2501-11e6-8b6d-0a8801256ff4.PNG)

**Comment by dhei** [comment]
@adrianhall: We should do this.

**Comment by dhei** [comment]
@jvano You have the permission (as team maintainer) to update the repository description. Can you update it? Thanks.

**Comment by jvano** [comment]
Done!
