### ISSUE TITLE
PullAsync for a single item

### ISSUE THREAD

**Issue by FrancoisM** [Azure/azure-mobile-services#897]
When I need to pull one item from the server, I have to do something like:

`localTable.PullAsync($"{tableName}_{itemId}", table.Where(x => x.Id == itemId) )`

This leads to up to 3 queries:
1) skip=0, top=50 updatedAt > minDate (when __config table has no entry for the max updatedAt value yet) => it returns the item
2) skip= 0, top=50 updatedAt>maxUpdatedAt (now that there is a maxUpdatedAt in __config) => it returns the item
3) skip=1, top=50 updatedAt>maxUpdatedAt => it returns nothing and it confirms the query is complete

I tried to be clever and to call remoteTable.LookUpAsync(itemId) and then localTable.UpdateAsync(item) (InsertAsync would lead to a violation PK conflict in the next push) but that leads to a Patch query in the next push. So 2 communications with the server instead of 3. And the Patch is not awaited at the time of the query (but will be some other time when I push).

Does anyone have a better way of doing it?
Tks.

**Comment by shrishrirang** [comment]
Ending the pull when the result size (number of records) is smaller than the requested page size will make only 1 network call. However, that will need a change in the SDK pull logic and is not helpful for your immediate requirement.

When you say you perform update on the local table, do you assume that a previous pull would have fetched the record already? UpdateAsync would fail otherwise.

Also, are you trying to optimize the latency of fetching the item on the client or something more than that?

**Comment by FrancoisM** [comment]
In his blog: https://shellmonger.com/2016/05/02/30-days-of-zumo-v2-azure-mobile-apps-day-15-understanding-offline-sync/
Adrian says: "The OData subsystem is allowed to return less than the requested value and will do so for a variety of reasons.".
While I don't know these reasons I guess changing the SDK to end the query when results are less tab the page size is not recommended.

In my workaround I T'as

Task<T> GetItem(itemId)
{
var localTable = client.GetSyncTable();
var remoteTable = client.GetTable();
var item = localTable.LookupAsync(itemId);
if(item!=null) return item;
item = remoteTable.LookupAsync(itemId);
localTable.UpdateAsync(item);
return item;
}

Sorry for the pseudo code, not in the office anymore, answering on mobile 😀

**Comment by shrishrirang** [comment]
Good point about the result size possibly being less than the requested page size. This can happen depending on the server's page size or max $top size.

With the current pull logic, I cannot think of a better way than what you are already doing!
