### ISSUE TITLE
[Android] Bug in OperationErrorList.java

### ISSUE THREAD

**Issue by MonRoyals** [Azure/azure-mobile-services#900]
Hi,

the following line in OperationErrorList.deserialize is wrong in the case of a null response of the server:

`String serverResponse = element.get("serverresponse") != null ? element.get("serverresponse").getAsString() : null;`

It returns a jsonNull and the getAsString() method fails with an UnsupportedOperationException.

**Comment by adrianhall** [comment]
This repo is no longer maintained.  If the issue is still valid in the Azure Mobile Apps realm (which requires a different server), then please file on azure/azure-mobile-apps-android-client.
