### ISSUE TITLE
Add support for patch custom api calls

### ISSUE THREAD

**Issue by InquisitorJax** [Azure/azure-mobile-services#902]
If my understanding is correct, one can patch an object that has been hooked up using a server tablecontroller, but there is not current way of calling a patch httpMethod via the InvokeApiAsync interface to a custom controller on the server.

If it is possible - is there documentation on how to do this?

**Comment by paulbatum** [comment]
One of the overloads for InvokeApiAsync takes a HttpMethod. However for some reason, the [HttpMethod type in .NET](https://msdn.microsoft.com/en-us/library/system.net.http.httpmethod(v=vs.118).aspx) does not have a built in Patch property (so you cannot do `HttpMethod.Patch`). But the good news is that HttpMethod has a constructor that takes a string, so we can use that:

`client.InvokeApiAsync("foo", new HttpMethod("PATCH"), new Dictionary<string, string>());`

**Comment by angusbreno** [comment]
Or just extend HttpMethod

```
    public class HttpMethod : System.Net.Http.HttpMethod
    {
        public HttpMethod(string method)
            : base(method)
        {
        }

        public static System.Net.Http.HttpMethod Patch { get { return new System.Net.Http.HttpMethod("PATCH"); } }
    }
```

and use:

`...InvokeApiAsync<IList<Data.DataModels.CompanySubscription>>("Administrative/SubscriptionManager/GetCompanySubscriptions", HttpMethod.Patch, null);`

**Comment by InquisitorJax** [comment]
@angusbreno Am I missing something - is there not supposed to be an input for a Patch call?
I tried calling a patch custom web api, and got an error about the ContentType not being correct.

Server WebApi:
        [Route("user/{id:guid}")]
        [HttpPatch]        
        [Authorize]
        public async Task<IHttpActionResult> PatchUser(string id, UpdateApplicationUserDto request)
        {
        ....code
             return Ok(updatedUser);
        }
Client call:
                var args = new Dictionary<string, string>();
                args.Add("request", JsonConvert.SerializeObject(updatedUserDto));
                ApplicationUser result = await Service.InvokeApiAsync<ApplicationUser>(serviceRoute, new HttpMethod("PATCH"), args);

**Comment by angusbreno** [comment]
Your calling it wrong. Don't pass objects in dictionary parameters.
From your API method i believe it's something like:

```
var dic = new Dictionary();
dic.Add("id",updatedUserDto.Id);

var returnedobj = await MobileServiceClient.InvokeApiAsync<UpdateApplicationUserDto , ReturnType>("api/.../user", updatedUserDto, HttpMethod.Patch, dic);
```

Objects always in body.

**Comment by InquisitorJax** [comment]
ah of course - thx!
