### ISSUE TITLE
Inc Sync: Xamarin IOS: queryid needs to be unique to work

### ISSUE THREAD

**Issue by Vasanth19** [Azure/azure-mobile-services#903]
Not sure if this is an issue or i am doing anything wrong.

I wanted to check how offline sync works and downloaded the todo sample for xamarin.ios.
Full sync works when I make the queryid = null, but for incremental sync to work, i need to make the queryid unique for everycall, something like this 

await todoTable.PullAsync("allTodoItems" + counter, todoTable.CreateQuery()); 
counter = counter + 1;

i am incrementing the counter everytime, i refresh.

All the documentation out there does not say anything about the queryid being unique for inc sync to work. 

Any explanation would be much appreciated.

**Comment by adrianhall** [comment]
Incremental Sync requires the query to be unique for it to work.  It's documented :-)
