### ISSUE TITLE
Cordova: logging out does not clear session/cookies in inappbrowser

### ISSUE THREAD

**Issue by bjartebore** [Azure/azure-mobile-services#906]
Using client.login() after logging out makes the login go through again without user interactions (new credentials). This could be solved with adding the clearcache=yes or the clearsessioncache=yes into the window.open() options argument.

e.g.
var loginWindow = window.open(startPage, "_blank", "location=no,clearcache=yes")

**Comment by adrianhall** [comment]
This repo is no longer maintained.  Please move this issue to azure/azure-mobile-apps-js-client.
