### ISSUE TITLE
abandoned? alternatives?

### ISSUE THREAD

**Issue by rothschild86** [Azure/azure-mobile-services#907]
What's the current recommended way of connecting to azure app service from a native andoid studio app (no xamarin)?

**Comment by rothschild86** [comment]
For anyone looking... https://github.com/Azure/azure-mobile-apps-android-client

**Comment by danderson00** [comment]
Azure Mobile Services has been deprecated in favor of the newer implementation, Azure Mobile Apps. More details [here](https://azure.microsoft.com/en-us/blog/transition-of-azure-mobile-services/)
