### ISSUE TITLE
Unable to utilize MobileServicesClient.InvokeApiAsync() in Xamarin application 

### ISSUE THREAD

**Issue by michael-watson** [Azure/azure-mobile-services#908]
Utilizing the Microsoft.aAzure.Mobile.Client 3.0.1 package, I am unable to utilize InvokeApiAsync() to call an API living in a Azure Mobile App. The results always return null, but I can successfully get what I need by manually building the string and using HttpClient to get a json response. 

If you have any questions, I'm a Xamarin and happy to help figure this out. 

It could be something to do with how the managed http handled is implemented on Xamarin.iOS; I did only test this on Xamarin.iOS and will try testing on Xamarin.Android next. Currently using the Managed (default) HttpClient implementation, will also try the Native NSUrlSession HttpClient implementation when testing Android.

**Comment by adrianhall** [comment]
This is the wrong repository.  Please use the azure/azure-mobile-apps-net-client repo for this.
